import { Certification } from '@/types';

export const CERTIFICATIONS: Certification[] = [
  {
    id: 'ai-performance-ads-1',
    title: 'AI-Powered Performance Ads Certification',
    issuer: 'Google Skillshop',
    issueDate: '2026-07-16',
    expiryDate: '2027-07-16',
    credentialUrl: 'https://www.credential.net/8fe73bad-d0b7-4a10-aef1-efca931a3386',
  },
  {
    id: 'ai-performance-ads-2',
    title: 'AI-Powered Performance Ads Certification',
    issuer: 'Google Skillshop',
    issueDate: '2026-07-16',
    expiryDate: '2027-07-16',
    credentialUrl: 'https://www.credential.net/6185076b-3c05-4916-abfd-3ae205c92cdb',
  },
  {
    id: 'google-ads-search',
    title: 'Google Ads Search Professional Certification (2026)',
    issuer: 'Google Skillshop',
    issueDate: '2026-07-16',
    expiryDate: '2027-07-16',
    credentialUrl: 'https://www.credential.net/327a9f94-7605-44fe-8237-f9ae705f7ec8',
  },
  {
    id: 'ai-shopping-ads',
    title: 'AI-Powered Shopping Ads Certification',
    issuer: 'Google Skillshop',
    issueDate: '2026-07-17',
    expiryDate: '2027-07-17',
    credentialUrl: 'https://www.credential.net/df4ab345-1a92-4f1d-9a32-de0ba8032d5a',
  },
  {
    id: 'meta-intro-frontend',
    title: 'Introduction to Front-End Development',
    issuer: 'Meta (via Coursera)',
    issueDate: '2026-07-26',
    expiryDate: '',
    credentialUrl: 'https://coursera.org/verify/1G6ZB303XNAY',
    image: '/certifications/meta-intro-frontend.png',
  },
  {
    id: 'scrimba-deploy-ai-cloudflare',
    title: 'Deploy AI Apps with Cloudflare',
    issuer: 'Scrimba (via Coursera)',
    issueDate: '2026-07-31',
    expiryDate: '',
    credentialUrl: 'https://coursera.org/verify/XT00EO361JTM',
    image: '/certifications/scrimba-deploy-ai-cloudflare.png',
  },
  {
    id: 'scrimba-intro-ai-engineering',
    title: 'Intro to AI Engineering',
    issuer: 'Scrimba (via Coursera)',
    issueDate: '2026-07-31',
    expiryDate: '',
    credentialUrl: 'https://coursera.org/verify/FQY4PSQZ99XN',
    image: '/certifications/scrimba-intro-ai-engineering.png',
  },
];
