import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { Language } from '../types';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  dir: 'ltr' | 'rtl';
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    hireMe: "Let's Create the Future",
    letsTalk: "Let's Talk",

    // Hero
    hero_badge: "Available for New Projects",
    hero_title_1: "I craft digital ",
    hero_title_2: "experiences",
    hero_title_3: "that ",
    hero_title_4: "feel alive.",
    hero_subtitle: "Full-Stack Developer & AI Specialist bridging the gap between complex logic and intuitive design.",
    hero_cta_start: "Start a Project",
    hero_cta_view: "View Work",
    hero_trust: "Trusted by 10+ happy clients",
    hero_card_role: "Developer",
    hero_card_desc: "Turning coffee into code.",
    hero_badge_perf: "High Perf",
    hero_badge_ai: "AI Automation",

    // Services
    services_badge: "Expertise",
    services_title_1: "High-Impact ",
    services_title_2: "Services.",
    services_subtitle: "Scalable solutions tailored to your business goals.",
    services_cta_title: "Have a custom idea?",
    services_cta_desc: "Let's build a solution specifically for you.",
    services_cta_btn: "Book a Consultation",
    modal_btn: "Got it, let's build! 🚀",
    modal_whatsapp: "Or discuss via WhatsApp",

    // Service Items
    service_1_title: "Full Stack Dev",
    service_1_desc: "End-to-end web applications using Next.js, React, and Node.js. Scalable, secure, and fast.",
    service_2_title: "Digital Products",
    service_2_desc: "Converting ideas into profitable SaaS platforms and e-commerce solutions.",
    service_3_title: "AI Automation",
    service_3_desc: "Custom AI chatbots, workflow automation, and intelligent data processing.",
    service_4_title: "Websites",
    service_4_desc: "High-performance marketing sites that convert visitors into loyal customers.",
    service_5_title: "3D Animated Frontend",
    service_5_desc: "Immersive 3D experiences and fluid animations that bring your digital presence to life.",
    service_marketing_title: 'Performance Marketing',
    service_marketing_desc: 'Data-driven campaigns on Google, Meta, TikTok, & Instagram that target your ideal audience and maximize ROI.',
    service_marketing_modal_title: 'Performance Marketing & PPC',
    service_marketing_modal_desc: "Maximize your ROI with data-driven campaigns across Google, Meta, TikTok, and Instagram. I offer tailored packages to suit your growth stage:\n\n**1. The Launch (3,000 ₪/mo):** Perfect for starters. 1 Platform, Campaign Setup, AI Copywriting, Weekly Optimization.\n\n**2. The Growth (5,500 ₪/mo):** Recommended for scaling. 2 Platforms, A/B Testing, Retargeting, Bi-Weekly Strategy.\n\n**3. The Dominance (9,000 ₪/mo):** Full-stack management. All Platforms, Advanced Automation, Video Editing assistance, 24/7 Support.\n\nWhy me? I combine marketing with technical expertise (Pixel API, Event Tracking) to ensure every cent is tracked.",

    // AI Section
    ai_badge: "Next-Gen Automation",
    ai_title_start: "Automate Your Business with",
    ai_title_highlight: "Intelligent AI",
    ai_desc: "Stop wasting time on repetitive tasks. I build custom AI solutions that handle customer support, scheduling, and content generation 24/7.",
    ai_card_1_title: "Smart Chatbots",
    ai_card_1_desc: "Customer support agents that learn from your business data and answer instantly.",
    ai_card_2_title: "Auto Scheduling",
    ai_card_2_desc: "AI that negotiates times and books appointments directly into your calendar.",
    ai_chat_name: "Waseem AI",
    ai_chat_status: "Online",
    ai_chat_msg_1: "How can I help optimize your workflow today?",
    ai_chat_msg_2: "I need a system to sort my incoming leads automatically.",
    ai_chat_msg_3: "I can build a Python-based automation using OpenAI API to classify emails and push high-value leads to your CRM instantly.",

    // Vibe Coding
    vibe_badge: "The Philosophy",
    vibe_title_1: "VIBE",
    vibe_title_2: "CODING",
    vibe_text_1: "Code isn't just logic;",
    vibe_text_2: "it's a feeling.",
    vibe_text_3: "It's finding the rhythm where functionality meets intuition.",
    vibe_text_4: "I craft experiences that feel right.",

    // About Timeline
    about_badge: "Verified Expert",
    about_title_1: "I don't just write code.",
    about_title_2: "I build the certainty your business needs.",
    about_trusted_title: "The Technical Partner You Can Trust",
    about_trusted_desc: "In a world of uncertainty, I provide the solid technical foundation your vision requires. When you work with me, you aren't just getting a developer; you are getting a guarantee of quality, security, and scalability.",
    about_card_lvl: "LVL 5 FULL STACK DEV",
    about_attr: "Attributes",
    about_class: "Class: Architect",
    about_stat_1: "Problem Solving",
    about_stat_2: "Innovation",
    about_stat_3: "Reliability",
    about_btn_cv: "Download CV",
    about_narrative_1: "I started with a simple question: \"How can we build better?\". That question drove me to master the entire stack, from the database to the pixel-perfect animation.",
    about_narrative_2: "Today, I leverage that mastery to help businesses like yours scale. My mission is simple:",
    about_mission: "To eliminate technical risk and deliver a product that just works.",

    // Timeline Items
    timeline_1_title: "Vibe Coding & Design",
    timeline_1_desc: "Professing the art of vibe coding and design, merging aesthetics with high-performance engineering.",
    timeline_2_title: "Senior Full Stack Dev",
    timeline_2_desc: "Architected scalable SaaS solutions serving 10k+ daily users.",
    timeline_3_title: "Started Journey",
    timeline_3_desc: "Began freelancing and building custom web solutions for local businesses.",

    // Projects
    projects_title_1: "Featured",
    projects_title_2: "Projects.",
    projects_subtitle: "A curated selection of work where design meets engineering.",
    projects_filter_all: "All",
    projects_filter_web: "Web",
    projects_filter_ai: "AI",
    projects_filter_mobile: "Mobile",
    projects_hint: "Tap to Flip",
    projects_details: "Details",
    projects_demo: "Live Demo",
    projects_code: "Code",
    project_1_desc: "A comprehensive analytics dashboard for AI model performance tracking.",
    project_2_desc: "Luxury jewelry e-commerce platform with 3D product viewer.",
    project_3_desc: "Real-time messaging app with instant translation features.",

    // Process
    process_step_1_title: "🧭 Discovery & Strategy",
    process_step_1_desc: "We start by mapping the unknown 🗺️. I dive deep into your business goals 🎯, target audience 👥, and market positioning to define a clear roadmap for success.\n\nThis stage includes research 🔍, competitor analysis 📊, user understanding 🧠, and defining measurable KPIs 📈 that guide every decision forward.\n\nThe result is a strong strategic foundation 🧱 that aligns vision 💡, users 👤, and technology ⚙️ before any design or code begins.",
    process_step_2_title: "🎨 Design & Prototyping",
    process_step_2_desc: "Ideas become visual ✨. I transform concepts into wireframes 🧩 and interactive prototypes 🖱️ that simulate real user experiences.\n\nUsing modern tools like Framer ⚡, Figma 🎨, and scalable Design Systems 🧱, I design intuitive user flows that feel natural and purposeful.\n\nResponsive layouts 📱, motion 🎞️, and micro-interactions ✨ ensure the product feels alive, clear, and easy to use across all devices.",
    process_step_3_title: "⚙️ Development",
    process_step_3_desc: "This is the engine of the product 🔥—where strategy 🧠 and design 🎨 turn into a real, working system.\n\nI build with Next.js 🚀 and React ⚛️, writing clean 🧼, secure 🔐, and scalable 📈 code ready for production.\n\nDevelopment focuses on performance ⚡, SEO 🔍, AEO 🤖 (Answer Engine Optimization), GEO 📍 targeting, accessibility ♿, and Core Web Vitals 🧪.\n\nI integrate Google Analytics 📊, Google Search Console 🔎, and performance monitoring tools ⏱️ to track real user behavior and support data-driven growth 📈 from day one.",
    process_step_4_title: "🧪 Testing & Quality Assurance",
    process_step_4_desc: "Excellence lives in the details 🧠. I test the product across devices 📱💻, browsers 🌐, and screen sizes to ensure a smooth experience.\n\nThis includes usability testing 🖱️, performance checks ⚡, responsiveness 📐, and edge-case validation 🧩.\n\nThe goal is not just functionality ✅—but confidence, stability, and polish ✨ before launch.",
    process_step_5_title: "🚀 Launch & Growth",
    process_step_5_desc: "Takeoff 🚀. The product is deployed in a secure 🔐, production-ready environment with proper configuration ⚙️ and monitoring 👀.\n\nI handle deployment 📦, basic security setup 🛡️, and performance validation ⚡ to ensure a stable launch.\n\nAfter launch, I provide documentation 📘, guidance 🧭, and ongoing support 🤝—so the product can evolve 🔄, scale 📈, and grow alongside your business 🌱.\n\n⭐ Final Result: A digital product that is strategic 🧠, measurable 📊, scalable 📈, and built to grow 🌍—not just a website.",
    process_read_specs: "Read Specs",
    process_mobile_title: "How I Work",
    process_mobile_desc: "From idea to launch — a smooth journey.",
    process_step_prefix: "Step",

    // Tech Stack (Game)
    tech_title_1: "Are you ",
    tech_title_2: "Ready ",
    tech_title_3: "to step in?",
    tech_score: "Total Score",
    tech_weapon: "Weapon System",
    tech_combo: "Combo",
    tech_boss_anomaly: "ANOMALY DETECTED",
    tech_boss_name: "TECH DEBT",
    tech_boss_eliminate: "CLICK TO ELIMINATE",
    tech_win_title: "MISSION COMPLETE",
    tech_win_desc: "You've mastered the stack.",
    tech_win_code: "Exclusive Code",
    tech_win_btn: "Continue",

    // Contact
    contact_avail: "Available for new projects",
    contact_title_1: "Let’s build something ",
    contact_title_2: "extraordinary.",
    contact_desc: "You have the vision, I have the stack. Drop me a line, and let's turn your abstract ideas into a tangible, high-performance digital reality.",
    contact_email_btn: "Email Me 📧",
    contact_whatsapp_btn: "Chat on WhatsApp 💬",

    // FAQ
    faq_badge: "Knowledge Base",
    faq_title_1: "Common ",
    faq_title_2: "Questions.",
    faq_desc: "Transparency is key. Here is everything you need to know about the process, pricing, and what it's like to work together.",
    faq_cta_unsure: "Still unsure?",
    faq_cta_ask: "Ask me on WhatsApp",
    faq_q1: "How long does a typical project take?",
    faq_a1: "Timeline varies by complexity. A standard brochure site takes 1-2 weeks, while complex SaaS platforms can take 1-3 months.",
    faq_q2: "Do you offer ongoing support?",
    faq_a2: "Yes, I offer maintenance packages to ensure your software remains secure, updated, and performant.",
    faq_q3: "What is \"Vibe Coding\"?",
    faq_a3: "It is my philosophy of blending technical precision with intuitive, user-centric design flow to create software that feels \"alive\".",
    faq_q4: "Can you work with existing teams?",
    faq_a4: "Absolutely. I have extensive experience integrating into existing workflows, using Jira, GitHub, and Agile methodologies.",
    faq_q5: "What is your pricing model?",
    faq_a5: "I typically work on a project-based pricing model, but I am open to hourly billing for consultation or maintenance tasks.",
    faq_q6: "Do you handle hosting and domain setup?",
    faq_a6: "Yes, I can handle the entire deployment process, including server setup, domain configuration, and SSL certificates.",
    faq_q7: "Are your websites SEO / AEO / GEO optimized?",
    faq_a7: "Yes! I build with modern Search Engine Optimization (SEO), Answer Engine Optimization (AEO), and Generative Engine Optimization (GEO) in mind. This means your site is ready for Google, ChatGPT, and the future of AI search.",

    // Footer
    footer_desc: "Crafting robust digital solutions at the intersection of design and artificial intelligence.",
    footer_links: "Quick Links",
    footer_services: "Services",
    footer_stay_updated: "Stay Updated",
    footer_sub_text: "Join 2,000+ subscribers for the latest on AI & Web Dev.",
    footer_email_placeholder: "Enter your email",
    footer_sub_btn: "Subscribe",
    footer_rights: "All rights reserved.",
    footer_privacy: "Privacy Policy",
    footer_terms: "Terms of Service",
    footer_made_with: "Made with",
    footer_tel_aviv: "in Tel Aviv",

    // Legal
    legal_close: "Close",
    legal_privacy_title: "Privacy Policy",
    legal_privacy_content: "1. Information Collection\nWe collect personal information such as name, email address, and project details when you submit the contact form. This data is used solely for communication and project estimation purposes.\n\n2. Use of Information\nYour data is used to respond to inquiries, provide services, and improve our website experience. We do not sell, trade, or rent your personal identification information to others.\n\n3. Data Security\nWe adopt appropriate data collection, storage, and processing practices and security measures to protect against unauthorized access, alteration, disclosure, or destruction of your personal information.\n\n4. Third-Party Services\nWe may use third-party service providers (like hosting partners) to help us operate our business. We may share your information with these third parties for those limited purposes.\n\n5. Contact\nIf you have any questions about this Privacy Policy, please contact us via the form on this website.",
    legal_terms_title: "Terms of Service",
    legal_terms_content: "1. Acceptance of Terms\nBy accessing this website, you agree to be bound by these Terms of Service and all applicable laws and regulations.\n\n2. Intellectual Property\nAll content on this website (code, design, text, graphics) is the property of Waseem unless otherwise stated. You may not reproduce or redistribute content without permission.\n\n3. Services\nWe provide web development and AI automation services. Specific terms, deliverables, and payment schedules for projects will be outlined in separate service agreements signed by both parties.\n\n4. Limitation of Liability\nIn no event shall Waseem be liable for any damages (including, without limitation, damages for loss of data or profit) arising out of the use or inability to use the materials on this website.\n\n5. Governing Law\nThese terms and conditions are governed by and construed in accordance with the laws of Israel and you irrevocably submit to the exclusive jurisdiction of the courts in that location.",

    // Cookie Banner
    cookie_title: "Privacy & Cookies",
    cookie_desc: "We use cookies to personalize your experience and analyze our traffic. In compliance with the Protection of Privacy Law, we respect your data sovereignty.",
    cookie_accept: "Accept All",
    cookie_decline: "Decline All",
    cookie_customize: "Customize",
    cookie_save: "Save Preferences",
    cookie_cat_necessary: "Strictly Necessary",
    cookie_cat_necessary_desc: "Essential for the website to function. Cannot be disabled.",
    cookie_cat_analytics: "Analytics & Performance",
    cookie_cat_analytics_desc: "Helps us understand how you use the site.",
    cookie_cat_marketing: "Marketing & Targeting",
    cookie_cat_marketing_desc: "Used to deliver relevant advertisements.",

    share: "Share",
    shareVia: "Share via",
    socialHub: "Social Hub",
    connectSocials: "Connect on Socials",
    followMe: "Follow Me",
    latestUpdates: "Catch the latest updates and behind-the-scenes.",
    followers: "Followers",
    likes: "Likes",
    posts: "Posts",
    // Contact Form
    formTitle: "Send me a message",
    formSubtitle: "Get a response within 24 hours",
    secureForm: "Secure form",
    autoReply: "Auto-reply",
    noSpam: "No spam",
    nameLabel: "Name",
    emailLabel: "Email",
    projectTypeLabel: "Project Type",
    budgetLabel: "Budget Range",
    messageLabel: "Message",
    minChars: "min chars",
    sendMessage: "Send Message",
    sending: "Sending...",
    successMessage: "Message sent!",
    successDescription: "I'll be in touch soon.",
    sendAnother: "Send another message",
    selectOption: "Select an option",
    // Options
    optWebsite: "Website",
    optLanding: "Landing Page",
    optFullStack: "Full Stack App",
    optAI: "AI Tool",
    optMaintenance: "Maintenance & Support",
    optOther: "Other",
    // Budget
    budgetUnder5k: "Under $1,500",
    budget5k10k: "$1,500 - $3,000",
    budget10k25k: "$3,000 - $7,500",
    budget25k50k: "$7,500 - $15,000",
    budget50kPlus: "$15,000+",
    // Validation
    required: "Required",
    invalidEmail: "Invalid email",
    tooShort: "Too short",
    // Wizard
    wizard_step_count: "Step {current} of {total}",
    wizard_step1_title: "What are we building?",
    wizard_step2_title: "What's the vibe?",
    wizard_step3_title: "What's the budget?",
    wizard_final_title: "Final Details",
    wizard_final_desc: "Tell me a bit more about your vision.",
    wizard_opt_web: "Web App",
    wizard_opt_app: "Mobile App",
    wizard_opt_ai: "AI Tool",
    wizard_opt_ecom: "E-Commerce",
    wizard_opt_minimal: "Minimalist",
    wizard_opt_bold: "Bold & Wild",
    wizard_opt_corp: "Corporate",
    wizard_opt_future: "Futuristic",
    wizard_opt_small: "< $5k",
    wizard_opt_medium: "$5k - $15k",
    wizard_opt_large: "$15k - $50k",
    wizard_opt_ent: "$50k+",
    wizard_detail_placeholder: "Describe your project in a few words...",
    wizard_btn_send: "Launch Project Request",
    wizard_success_title: "Request Received!",
    wizard_success_desc: "I've received your project specs. I'll review them and get back to you within 24 hours.",
    wizard_start_over: "Start New Request",
  },
  he: {
    // Navigation
    hireMe: "בוא ניצור את העתיד",
    letsTalk: "בוא נדבר",

    // Hero
    hero_badge: "פנוי לפרויקטים חדשים",
    hero_title_1: "אני יוצר חוויות ",
    hero_title_2: "דיגיטליות",
    hero_title_3: "שמרגישות ",
    hero_title_4: "חיות.",
    hero_subtitle: "מפתח פול-סטאק ומומחה AI המגשר על הפער בין לוגיקה מורכבת לעיצוב אינטואיטיבי.",
    hero_cta_start: "התחל פרויקט",
    hero_cta_view: "צפה בעבודות",
    hero_trust: "בשימוש ע״י 10+ לקוחות מרוצים",
    hero_card_role: "מפתח",
    hero_card_desc: "הופך קפה לקוד.",
    hero_badge_perf: "ביצועים",
    hero_badge_ai: "אוטומציה",

    // Services
    services_badge: "מומחיות",
    services_title_1: "שירותים ",
    services_title_2: "משנים משחק.",
    services_subtitle: "פתרונות סקלביליים המותאמים ליעדים העסקיים שלך.",
    services_cta_title: "יש לך רעיון?",
    services_cta_desc: "בוא נבנה פתרון שמותאם בדיוק בשבילך.",
    services_cta_btn: "קבע שיחת ייעוץ",
    modal_btn: "הבנתי, בוא נבנה! 🚀",
    modal_whatsapp: "או נדבר בווטסאפ",

    // Service Items
    service_1_title: "פיתוח פול-סטאק",
    service_1_desc: "אפליקציות ווב מקצה לקצה בשימוש Next.js, React ו-Node.js. מאובטח ומהיר.",
    service_2_title: "מוצרים דיגיטליים",
    service_2_desc: "המרת רעיונות לפלטפורמות SaaS רווחיות ופתרונות איקומרס.",
    service_3_title: "אוטומציה ו-AI",
    service_3_desc: "צ'אטבוטים חכמים, אוטומציה של תהליכים ועיבוד נתונים חכם.",
    service_4_title: "אתרי אינטרנט",
    service_4_desc: "אתרי שיווק מהירים שממירים מבקרים ללקוחות נאמנים.",
    service_5_title: "פרונט-אנד תלת-ממדי",
    service_5_desc: "חוויות תלת-ממד ואנימציות שמפיחות חיים בנוכחות הדיגיטלית שלך.",
    service_marketing_title: 'שיווק ביצועים (PPC)',
    service_marketing_desc: 'קמפיינים מבוססי נתונים בגוגל, פייסבוק, טיקטוק ואינסטגרם שמכוונים לקהל היעד שלך וממקסמים החזר השקעה.',
    service_marketing_modal_title: 'שיווק דיגיטלי ו-PPC',
    service_marketing_modal_desc: "מקסם את החזר ההשקעה שלך עם קמפיינים מבוססי נתונים בגוגל, פייסבוק, טיקטוק ואינסטגרם. חבילות מותאמות אישית:\n\n**1. חבילת ההשקה (3,000 ₪/חודש):** מתאימה למתחילים. פלטפורמה אחת, הקמת קמפיין, קופירייטינג מבוסס AI, אופטימיזציה שבועית.\n\n**2. חבילת הצמיחה (5,500 ₪/חודש):** מומלצת לגדילה. 2 פלטפורמות, בדיקות A/B, ריטרגטינג, אסטרטגיה דו-שבועית.\n\n**3. חבילת השליטה (9,000 ₪/חודש):** ניהול מלא. כל הפלטפורמות, אוטומציה מתקדמת, עריכת וידאו, תמיכה 24/7.",

    // AI Section
    ai_badge: "אוטומציה מתקדמת",
    ai_title_start: "הפוך את העסק שלך לאוטומטי עם",
    ai_title_highlight: "בינה מלאכותית",
    ai_desc: "הפסק לבזבז זמן על משימות חוזרות. אני בונה פתרונות AI שמטפלים בשירות לקוחות, תיאום פגישות ויצירת תוכן 24/7.",
    ai_card_1_title: "צ'אטבוטים חכמים",
    ai_card_1_desc: "נציגי שירות שלומדים מהנתונים העסקיים שלך ועונים מיידית.",
    ai_card_2_title: "תיאום אוטומטי",
    ai_card_2_desc: "AI שמנהל משא ומתן על זמנים וקובע פגישות ישירות ביומן.",
    ai_chat_name: "וסים AI",
    ai_chat_status: "מחובר",
    ai_chat_msg_1: "איך אני יכול לעזור לייעל את העבודה שלך היום?",
    ai_chat_msg_2: "אני צריך מערכת למיון לידים נכנסים באופן אוטומטי.",
    ai_chat_msg_3: "אני יכול לבנות אוטומציה ב-Python המשתמשת ב-OpenAI למיון אימיילים ושליחת לידים חשובים ל-CRM.",

    // Vibe Coding
    vibe_badge: "הפילוסופיה",
    vibe_title_1: "VIBE",
    vibe_title_2: "CODING",
    vibe_text_1: "קוד הוא לא רק לוגיקה;",
    vibe_text_2: "זו הרגשה.",
    vibe_text_3: "זה למצוא את הקצב שבו פונקציונליות פוגשת אינטואיציה.",
    vibe_text_4: "אני יוצר חוויות שמרגישות נכון.",

    // About Timeline
    about_badge: "מומחה מאומת",
    about_title_1: "אני לא רק כותב קוד.",
    about_title_2: "אני בונה את הוודאות שהעסק שלך צריך.",
    about_trusted_title: "השותף הטכני שאפשר לסמוך עליו",
    about_trusted_desc: "בעולם של אי-ודאות, אני מספק את הבסיס הטכני המוצק שהחזון שלך דורש. כשאתה עובד איתי, אתה מקבל התחייבות לאיכות, אבטחה וסקלביליות.",
    about_card_lvl: "מפתח שלב 2",
    about_attr: "תכונות",
    about_class: "מחלקה: ארכיטקט",
    about_stat_1: "פתרון בעיות",
    about_stat_2: "חדשנות",
    about_stat_3: "אמינות",
    about_narrative_1: "התחלתי עם שאלה פשוטה: \"איך בונים טוב יותר?\". השאלה הזו דחפה אותי לשלוט בכל הסטאק.",
    about_narrative_2: "היום, אני משתמש בידע הזה כדי לעזור לעסקים לצמוח. המשימה שלי פשוטה:",
    about_mission: "להסיר סיכון טכני ולספק מוצר שפשוט עובד.",

    // Timeline Items
    timeline_1_title: "Vibe Coding & Design",
    timeline_1_desc: "שילוב אומנות הקוד והעיצוב, מיזוג אסתטיקה עם הנדסה בביצועים גבוהים.",
    timeline_2_title: "מפתח פול-סטאק בכיר",
    timeline_2_desc: "ארכיטקטורת פתרונות SaaS המשרתים 1,000+ משתמשים יומיים.",
    timeline_3_title: "תחילת הדרך",
    timeline_3_desc: "התחלת עבודה כפרילנסר ובניית פתרונות ווב לעסקים מקומיים.",

    // Projects
    projects_title_1: "פרויקטים",
    projects_title_2: "נבחרים.",
    projects_subtitle: "מבחר עבודות בהן עיצוב פוגש הנדסה.",
    projects_filter_all: "הכל",
    projects_filter_web: "ווב",
    projects_filter_ai: "AI",
    projects_filter_mobile: "מובייל",
    projects_hint: "לחץ להיפוך",
    projects_details: "פרטים",
    projects_demo: "דמו חי",
    projects_code: "קוד",
    project_1_desc: "לוח בקרה אנליטי מקיף למעקב אחר ביצועי מודלים של AI.",
    project_2_desc: "פלטפורמת איקומרס יוקרתית לתכשיטים עם צפייה במוצרים בתלת-ממד.",
    project_3_desc: "אפליקציית הודעות בזמן אמת עם תכונות תרגום מיידי.",

    // Process
    process_step_1_title: "🧭 גילוי ואסטרטגיה",
    process_step_1_desc: "מתחילים במיפוי הלא נודע 🗺️. אני צולל לעומק היעדים העסקיים שלך 🎯, הקהל היעד 👥 והמיקום בשוק כדי להגדיר מפת דרכים ברורה להצלחה.\n\nשלב זה כולל מחקר 🔍, ניתוח מתחרים 📊, הבנת משתמשים 🧠 והגדרת KPIs מדידים 📈 שמנחים כל החלטה לפנים.\n\nהתוצאה היא יסוד אסטרטגי חזק 🧱 שמיישר קו בין חזון 💡, משתמשים 👤 וטכנולוגיה ⚙️ לפני שמתחילים עיצוב או קוד.",
    process_step_2_title: "🎨 עיצוב ואבטיפוס",
    process_step_2_desc: "רעיונות הופכים לויזואליים ✨. אני מפתח קונספטים ל-wireframes 🧩 ואבטיפוסים אינטראקטיביים 🖱️ שמדמים חוויות משתמש אמיתיות.\n\nבאמצעות כלים מודרניים כמו Framer ⚡, Figma 🎨 ו-Design Systems סקלביליים 🧱, אני מעצב זרימות משתמש אינטואיטיביות שמרגישות טבעיות ומכוונות.\n\nפריסות רספונסיביות 📱, אנימציות 🎞️ ו-micro-interactions ✨ מבטיחים שהמוצר ירגיש חי, ברור וקל לשימוש בכל המכשירים.",
    process_step_3_title: "⚙️ פיתוח",
    process_step_3_desc: "זהו המנוע של המוצר 🔥—כאן אסטרטגיה 🧠 ועיצוב 🎨 הופכים למערכת עובדת ואמיתית.\n\nאני בונה עם Next.js 🚀 ו-React ⚛️, כותב קוד נקי 🧼, מאובטח 🔐 וסקלבילי 📈 מוכן לפרודקשן.\n\nהפיתוח מתמקד בביצועים ⚡, SEO 🔍, AEO 🤖 (אופטימיזציה למנועי תשובות), GEO 📍, נגישות ♿ ו-Core Web Vitals 🧪.\n\nאני משלב Google Analytics 📊, Google Search Console 🔎 וכלי ניטור ביצועים ⏱️ כדי לעקוב אחר התנהגות משתמשים אמיתית ולתמוך בצמיחה מבוססת נתונים 📈 מהיום הראשון.",
    process_step_4_title: "🧪 בדיקות ובקרת איכות",
    process_step_4_desc: "המצוינות נמצאת בפרטים 🧠. אני בודק את המוצר במכשירים 📱💻, דפדפנים 🌐 וגדלי מסך כדי להבטיח חוויה חלקה.\n\nזה כולל בדיקות שמישות 🖱️, בדיקות ביצועים ⚡, רספונסיביות 📐 ואימות edge-cases 🧩.\n\nהמטרה היא לא רק פונקציונליות ✅—אלא ביטחון, יציבות וליטוש ✨ לפני ההשקה.",
    process_step_5_title: "🚀 השקה וצמיחה",
    process_step_5_desc: "המראה 🚀. המוצר מוצב בסביבה מאובטחת 🔐 מוכנה לפרודקשן עם קונפיגורציה נכונה ⚙️ וניטור 👀.\n\nאני מטפל ב-deployment 📦, הגדרת אבטחה בסיסית 🛡️ וולידציית ביצועים ⚡ כדי להבטיח השקה יציבה.\n\nאחרי ההשקה, אני מספק תיעוד 📘, הדרכה 🧭 ותמיכה מתמדת 🤝—כך שהמוצר יכול להתפתח 🔄, לגדול 📈 ולצמוח לצד העסק שלך 🌱.\n\n⭐ תוצאה סופית: מוצר דיגיטלי שהוא אסטרטגי 🧠, מדיד 📊, סקלבילי 📈 ובנוי לצמיחה 🌍—לא רק אתר.",
    process_read_specs: "קרא מפרט",
    process_mobile_title: "איך אני עובד",
    process_mobile_desc: "מרעיון לקוד, מסע חלק.",
    process_step_prefix: "שלב",

    // Tech Stack
    tech_title_1: "האם אתה ",
    tech_title_2: "מוכן ",
    tech_title_3: "להיכנס?",
    tech_score: "ניקוד",
    tech_weapon: "נשק",
    tech_combo: "קומבו",
    tech_boss_anomaly: "זוהתה אנומליה",
    tech_boss_name: "חוב טכני",
    tech_boss_eliminate: "לחץ לחיסול",
    tech_win_title: "משימה הושלמה",
    tech_win_desc: "שלטת בטכנולוגיה.",
    tech_win_code: "קוד בלעדי",
    tech_win_btn: "המשך",

    // Contact
    contact_avail: "פנוי לפרויקטים חדשים",
    contact_title_1: "בוא נבנה משהו ",
    contact_title_2: "יוצא דופן.",
    contact_desc: "לך יש את החזון, לי יש את הכלים. שלח הודעה ונהפוך את הרעיונות למציאות דיגיטלית.",
    contact_email_btn: "שלח אימייל 📧",
    contact_whatsapp_btn: "דבר איתי בווטסאפ 💬",

    // FAQ
    faq_badge: "מרכז ידע",
    faq_title_1: "שאלות ",
    faq_title_2: "נפוצות.",
    faq_desc: "שקיפות היא המפתח. הנה כל מה שצריך לדעת על התהליך, המחיר והעבודה המשותפת.",
    faq_cta_unsure: "עדיין לא בטוח?",
    faq_cta_ask: "שאל אותי בווטסאפ",
    faq_q1: "כמה זמן לוקח פרויקט טיפוסי?",
    faq_a1: "הזמן משתנה בהתאם למורכבות. אתר תדמית לוקח 1-2 שבועות, פלטפורמות מורכבות יכולות לקחת 1-3 חודשים.",
    faq_q2: "האם אתה מציע תמיכה שוטפת?",
    faq_a2: "כן, אני מציע חבילות תחזוקה כדי להבטיח שהתוכנה תישאר מאובטחת ומעודכנת.",
    faq_q3: "מה זה \"Vibe Coding\"?",
    faq_a3: "זו הפילוסופיה שלי לשילוב דיוק טכני עם זרימה עיצובית אינטואיטיבית ליצירת תוכנה שמרגישה \"חיה\".",
    faq_q4: "האם אתה יכול לעבוד עם צוותים קיימים?",
    faq_a4: "בהחלט. יש לי ניסיון רב בהשתלבות בצוותים קיימים ועבודה עם Jira ו-GitHub.",
    faq_q5: "מה מודל התמחור שלך?",
    faq_a5: "בדרך כלל אני עובד לפי פרויקט, אך פתוח גם לחיוב שעתי לייעוץ או תחזוקה.",
    faq_q6: "האם אתה מטפל באחסון ודומיין?",
    faq_a6: "כן, אני יכול לטפל בכל תהליך ההעלאה לאוויר, כולל שרתים ותעודות אבטחה.",
    faq_q7: "האם האתרים מותאמים ל-SEO / AEO / GEO?",
    faq_a7: "כן! אני בונה עם דגש על קידום במנועי חיפוש (SEO), אופטימיזציה למנועי תשובות (AEO), ואופטימיזציה למנועים גנרטיביים (GEO). זה אומר שהאתר שלך מוכן לגוגל, ל-ChatGPT ולעתיד החיפוש ב-AI.",

    // Footer
    footer_desc: "בניית פתרונות דיגיטליים חזקים במפגש שבין עיצוב לבינה מלאכותית.",
    footer_links: "קישורים מהירים",
    footer_services: "שירותים",
    footer_stay_updated: "הישאר מעודכן",
    footer_sub_text: "הצטרף ל-2,000+ מנויים לחדשות בנושאי AI ופיתוח.",
    footer_email_placeholder: "הכנס אימייל",
    footer_sub_btn: "הרשמה",
    footer_rights: "כל הזכויות שמורות.",
    footer_privacy: "מדיניות פרטיות",
    footer_terms: "תנאי שימוש",
    footer_made_with: "נוצר עם",
    footer_tel_aviv: "בתל אביב",

    // Legal
    legal_close: "סגור",
    legal_privacy_title: "מדיניות פרטיות",
    legal_privacy_content: "1. איסוף מידע\nאנו אוספים מידע אישי כגון שם, כתובת דוא\"ל ופרטי פרויקט כאשר אתה שולח את טופס יצירת הקשר. נתונים אלה משמשים אך ורק לתקשורת והערכת פרויקטים.\n\n2. שימוש במידע\nהנתונים שלך משמשים למענה לפניות, אספקת שירותים ושיפור חווית האתר שלנו. איננו מוכרים, סוחרים או משכירים את פרטי הזיהוי האישיים שלך לאחרים.\n\n3. אבטחת מידע\nאנו נוקטים באמצעים הולמים לאיסוף, אחסון ועיבוד נתונים ואמצעי אבטחה להגנה מפני גישה בלתי מורשית, שינוי, חשיפה או הרס של המידע האישי שלך.\n\n4. שירותי צד שלישי\nאנו עשויים להשתמש בספקי שירות צד שלישי (כמו שותפי אחסון) כדי לעזור לנו להפעיל את העסק שלנו. אנו עשויים לשתף את המידע שלך עם צדדים שלישיים אלה למטרות מוגבלות אלה.\n\n5. יצירת קשר\nאם יש לך שאלות לגבי מדיניות פרטיות זו, אנא צור איתנו קשר באמצעות הטופס באתר זה.",
    legal_terms_title: "תנאי שימוש",
    legal_terms_content: "1. קבלת התנאים\nעל ידי גישה לאתר זה, אתה מסכים להיות כפוף לתנאי שימוש אלה ולכל החוקים והתקנות הרלוונטיים.\n\n2. קניין רוחני\nכל התוכן באתר זה (קוד, עיצוב, טקסט, גרפיקה) הוא קניינו של וסים אלא אם צוין אחרת. אין לשכפל או להפיץ מחדש תוכן ללא רשות.\n\n3. שירותים\nאנו מספקים שירותי פיתוח ווב ואוטומציה ב-AI. תנאים ספציפיים, תוצרים ולוחות זמנים לתשלום עבור פרויקטים יפורטו בהסכמי שירות נפרדים החתומים על ידי שני הצדדים.\n\n4. הגבלת אחריות\nבשום מקרה לא יהיה וסים אחראי לכל נזק (לרבות, ללא הגבלה, נזקים בגין אובדן נתונים או רווח) הנובע מהשימוש או חוסר היכולת להשתמש בחומרים באתר זה.\n\n5. הדין החל\nתנאים אלה כפופים לחוקי מדינת ישראל ואתה מסכים באופן בלתי חוזר לסמכות השיפוט הבלעדית של בתי המשפט במיקום זה.",

    // Cookie Banner
    cookie_title: "פרטיות ועוגיות",
    cookie_desc: "אנו משתמשים בעוגיות כדי להתאים אישית את החוויה שלך ולנתח את התנועה באתר. בהתאם לחוק הגנת הפרטיות, אנו מכבדים את השליטה שלך במידע.",
    cookie_accept: "קבל הכל",
    cookie_decline: "דחה הכל",
    cookie_customize: "התאמה אישית",
    cookie_save: "שמור העדפות",
    cookie_cat_necessary: "הכרחי לחלוטין",
    cookie_cat_necessary_desc: "חיוני לפעילות האתר. לא ניתן לביטול.",
    cookie_cat_analytics: "ניתוח וביצועים",
    cookie_cat_analytics_desc: "עוזר לנו להבין כיצד אתה משתמש באתר.",
    cookie_cat_marketing: "שיווק ופרסום",
    cookie_cat_marketing_desc: "משמש להצגת מודעות רלוונטיות.",

    share: "שתף",
    shareVia: "שתף דרך",
    socialHub: "רשתות חברתיות",
    connectSocials: "התחבר ברשתות",
    followMe: "עקוב אחרי",
    latestUpdates: "קבל את העדכונים האחרונים ומאחורי הקלעים.",
    followers: "עוקבים",
    likes: "לייקים",
    posts: "פוסטים",
    formTitle: "שלח לי הודעה",
    formSubtitle: "קבל תגובה תוך 24 שעות",
    secureForm: "טופס מאובטח",
    autoReply: "מענה אוטומטי",
    noSpam: "ללא ספאם",
    nameLabel: "שם",
    emailLabel: "אימייל",
    projectTypeLabel: "סוג פרויקט",
    budgetLabel: "תקציב משוער",
    messageLabel: "הודעה",
    minChars: "תווים לפחות",
    sendMessage: "שלח הודעה",
    sending: "שולח...",
    successMessage: "הודעה נשלחה!",
    successDescription: "אצור קשר בקרוב.",
    sendAnother: "שלח הודעה נוספת",
    selectOption: "בחר אפשרות",
    optWebsite: "אתר אינטרנט",
    optLanding: "דף נחיתה",
    optFullStack: "אפליקציית פול-סטאק",
    optAI: "כלי AI",
    optMaintenance: "תחזוקה ותמיכה",
    optOther: "אחר",
    budgetUnder5k: "מתחת ל-3,000 ₪",
    budget5k10k: "3,000 ₪ - 10,000 ₪",
    budget10k25k: "10,000 ₪ - 25,000 ₪",
    budget25k50k: "25,000 ₪ - 50,000 ₪",
    budget50kPlus: "50,000 ₪+",
    required: "נדרש",
    invalidEmail: "אימייל לא תקין",
    tooShort: "קצר מדי",
    // Wizard
    wizard_step_count: "שלב {current} מתוך {total}",
    wizard_step1_title: "מה בונים?",
    wizard_step2_title: "מה הוויב?",
    wizard_step3_title: "מה התקציב?",
    wizard_final_title: "פרטים אחרונים",
    wizard_final_desc: "ספר לי עוד קצת על החזון שלך.",
    wizard_opt_web: "אפליקציית ווב",
    wizard_opt_app: "אפליקציית מובייל",
    wizard_opt_ai: "כלי AI",
    wizard_opt_ecom: "חנות אינטרנטית",
    wizard_opt_minimal: "מינימליסטי",
    wizard_opt_bold: "נועז ופראי",
    wizard_opt_corp: "פורמלי/עסקי",
    wizard_opt_future: "עתידני",
    wizard_opt_small: "עד 5,000₪",
    wizard_opt_medium: "5,000₪ - 15,000₪",
    wizard_opt_large: "15,000₪ - 50,000₪",
    wizard_opt_ent: "50,000₪+",
    wizard_detail_placeholder: "תאר את הפרויקט בכמה מילים...",
    wizard_btn_send: "שגר בקשה לפרויקט",
    wizard_success_title: "הבקשה התקבלה!",
    wizard_success_desc: "קיבלתי את המפרט שלך. אעבור עליו ואחזור אליך תוך 24 שעות.",
    wizard_start_over: "התחל בקשה חדשה",
  },
  ar: {
    // Navigation
    hireMe: "لنصنع المستقبل",
    letsTalk: "تحدث معي",

    // Hero
    hero_badge: "متاح لمشاريع جديدة",
    hero_title_1: "أصمم تجارب ",
    hero_title_2: "رقمية",
    hero_title_3: "تشعر بأنها ",
    hero_title_4: "حية.",
    hero_subtitle: "مطور شامل ومختص بالذكاء الاصطناعي، أربط بين المنطق المعقد والتصميم البديهي.",
    hero_cta_start: "ابدأ مشروعاً",
    hero_cta_view: "شاهد أعمالي",
    hero_trust: "موثوق من قبل 10+ عملاء سعداء",
    hero_card_role: "مطور",
    hero_card_desc: "أحول القهوة إلى كود.",
    hero_badge_perf: "أداء عالي",
    hero_badge_ai: "أتمتة ذكية",

    // Services
    services_badge: "الخبرات",
    services_title_1: "خدمات ",
    services_title_2: "عالية التأثير.",
    services_subtitle: "حلول قابلة للتوسع مصممة خصيصاً لأهداف عملك.",
    services_cta_title: "لديك فكرة مخصصة؟",
    services_cta_desc: "دعنا نبني حلاً مخصصاً لك.",
    services_cta_btn: "احجز استشارة",
    modal_btn: "فهمت، لنبدأ البناء! 🚀",
    modal_whatsapp: "أو ناقش عبر واتساب",

    // Service Items
    service_1_title: "تطوير شامل (Full Stack)",
    service_1_desc: "تطبيقات ويب متكاملة باستخدام Next.js و React و Node.js. قابلة للتوسع، آمنة، وسريعة.",
    service_2_title: "منتجات رقمية",
    service_2_desc: "تحويل الأفكار إلى منصات SaaS مربحة وحلول تجارة إلكترونية.",
    service_3_title: "أتمتة الذكاء الاصطناعي",
    service_3_desc: "روبوتات دردشة مخصصة، أتمتة سير العمل، ومعالجة ذكية للبيانات.",
    service_4_title: "مواقع إلكترونية",
    service_4_desc: "مواقع تسويقية عالية الأداء تحول الزوار إلى عملاء مخلصين.",
    service_5_title: "واجهات ثلاثية الأبعاد",
    service_5_desc: "تجارب ثلاثية الأبعاد غامرة ورسوم متحركة سلسة تبث الحياة في تواجدك الرقمي.",
    service_marketing_title: 'التسويق الرقمي والأداء',
    service_marketing_desc: 'حملات مدفوعة تعتمد على البيانات عبر Google و Meta و TikTok و Instagram تستهدف جمهورك المثالي وتحقق أعلى عائد استثمار.',
    service_marketing_modal_title: 'إدارة الحملات الإعلانية (PPC)',
    service_marketing_modal_desc: "حقق أقصى عائد على الاستثمار من خلال حملات تعتمد على البيانات عبر Google و Meta و TikTok و Instagram. باقات مصممة لتناسب مرحلة نموك:\n\n**1. باقة الانطلاق (3,000 شيكل/شهرياً):** مثالية للمبتدئين. منصة واحدة، إعداد الحملة، كتابة إعلانات بالذكاء الاصطناعي، تحسين أسبوعي.\n\n**2. باقة النمو (5,500 شيكل/شهرياً):** موصى بها للتوسع. منصتان، اختبار A/B، إعادة الاستهداف، استراتيجية نصف شهرية.\n\n**3. باقة السيطرة (9,000 شيكل/شهرياً):** إدارة شاملة. جميع المنصات، أتمتة متقدمة، مساعدة في تحرير الفيديو، دعم 24/7.",

    // AI Section
    ai_badge: "أتمتة الجيل القادم",
    ai_title_start: "أتمت عملك مع",
    ai_title_highlight: "الذكاء الاصطناعي الذكي",
    ai_desc: "توقف عن إضاعة الوقت في المهام المتكررة. أبني حلول ذكاء اصطناعي مخصصة تتعامل مع دعم العملاء، الجدولة، وإنشاء المحتوى على مدار الساعة.",
    ai_card_1_title: "روبوتات دردشة ذكية",
    ai_card_1_desc: "وكلاء دعم عملاء يتعلمون من بيانات عملك ويجيبون فورياً.",
    ai_card_2_title: "جدولة تلقائية",
    ai_card_2_desc: "ذكاء اصطناعي يتفاوض على الأوقات ويحجز المواعيد مباشرة في تقويمك.",
    ai_chat_name: "وسيم AI",
    ai_chat_status: "متصل",
    ai_chat_msg_1: "كيف يمكنني المساعدة في تحسين سير عملك اليوم؟",
    ai_chat_msg_2: "أحتاج نظاماً لفرز العملاء المحتملين تلقائياً.",
    ai_chat_msg_3: "يمكنني بناء أتمتة باستخدام Python و OpenAI API لتصنيف رسائل البريد الإلكتروني ودفع العملاء ذوي القيمة العالية إلى نظام CRM الخاص بك فوراً.",

    // Vibe Coding
    vibe_badge: "الفلسفة",
    vibe_title_1: "VIBE",
    vibe_title_2: "CODING",
    vibe_text_1: "الكود ليس مجرد منطق؛",
    vibe_text_2: "إنه شعور.",
    vibe_text_3: "إنه إيجاد الإيقاع حيث تلتقي الوظيفة مع الحدس.",
    vibe_text_4: "أصمم تجارب تبدو صحيحة.",

    // About Timeline
    about_badge: "خبير معتمد",
    about_title_1: "أنا لا أكتب الكود فقط.",
    about_title_2: "أبني اليقين الذي يحتاجه عملك.",
    about_trusted_title: "الشريك التقني الذي يمكنك الوثوق به",
    about_trusted_desc: "في عالم من عدم اليقين، أوفر الأساس التقني الصلب الذي تتطلبه رؤيتك. عندما تعمل معي، لا تحصل فقط على مطور؛ بل تحصل على ضمان الجودة، الأمان، والقابلية للتوسع.",
    about_card_lvl: "مطور شامل مستوى 5",
    about_attr: "السمات",
    about_class: "الفئة: مهندس معماري",
    about_stat_1: "حل المشكلات",
    about_stat_2: "الابتكار",
    about_stat_3: "الموثوقية",
    about_btn_cv: "تحميل السيرة الذاتية",
    about_narrative_1: "بدأت بسؤال بسيط: \"كيف يمكننا البناء بشكل أفضل؟\". قادني هذا السؤال لإتقان التقنيات بالكامل، من قاعدة البيانات إلى الرسوم المتحركة الدقيقة.",
    about_narrative_2: "اليوم، أستفيد من هذا الإتقان لمساعدة شركات مثل شركتك على النمو. مهمتي بسيطة:",
    about_mission: "إزالة المخاطر التقنية وتقديم منتج يعمل ببساطة.",

    // Timeline Items
    timeline_1_title: "Vibe Coding & Design",
    timeline_1_desc: "ممارسة فن الكود والتصميم، دمج الجماليات مع الهندسة عالية الأداء.",
    timeline_2_title: "مطور شامل أول",
    timeline_2_desc: "هندسة حلول SaaS قابلة للتوسع تخدم أكثر من 10 آلاف مستخدم يومياً.",
    timeline_3_title: "بداية الرحلة",
    timeline_3_desc: "بدأت العمل الحر وبناء حلول ويب مخصصة للشركات المحلية.",

    // Projects
    projects_title_1: "مشاريع",
    projects_title_2: "مميزة.",
    projects_subtitle: "مجموعة مختارة من الأعمال حيث يلتقي التصميم بالهندسة.",
    projects_filter_all: "الكل",
    projects_filter_web: "ويب",
    projects_filter_ai: "ذكاء اصطناعي",
    projects_filter_mobile: "موبايل",
    projects_hint: "انقر للقلب",
    projects_details: "تفاصيل",
    projects_demo: "عرض حي",
    projects_code: "كود",
    project_1_desc: "لوحة تحكم تحليلية شاملة لتتبع أداء نماذج الذكاء الاصطناعي.",
    project_2_desc: "منصة تجارة إلكترونية للمجوهرات الفاخرة مع عارض منتجات ثلاثي الأبعاد.",
    project_3_desc: "تطبيق مراسلة فوري مع ميزات ترجمة فورية.",

    // Process
    process_step_1_title: "🧭 الاكتشاف والاستراتيجية",
    process_step_1_desc: "نبدأ برسم خريطة للمجهول 🗺️. أغوص بعمق في أهداف عملك 🎯، والجمهور المستهدف 👥، والموقع في السوق لبناء خريطة طريق واضحة للنجاح.\n\nيشمل هذا المرحلة البحث 🔍، وتحليل المنافسين 📊، وفهم المستخدمين 🧠، وتحديد مؤشرات الأداء الرئيسية القابلة للقياس 📈 التي ترشد كل قرار إلى الأمام.\n\nالنتيجة هي أساس استراتيجي قوي 🧱 يوائم بين الرؤية 💡، والمستخدمين 👤، والتكنولوجيا ⚙️ قبل أي تصميم أو كود.",
    process_step_2_title: "🎨 التصميم والنماذج الأولية",
    process_step_2_desc: "تصبح الأفكار بصرية ✨. أحول المفاهيم إلى wireframes 🧩 ونماذج أولية تفاعلية 🖱️ تحاكي تجارب المستخدم الحقيقية.\n\nباستخدام أدوات حديثة مثل Framer ⚡، وFigma 🎨، وأنظمة تصميم قابلة للتوسع 🧱، أصمم تدفقات مستخدم بديهية تشعر بالطبيعة والهدف.\n\nالتخطيطات المتجاوبة 📱، والحركة 🎞️، والتفاعلات الدقيقة ✨ تضمن أن المنتج يبدو حياً، واضحاً، وسهلاً للاستخدام عبر جميع الأجهزة.",
    process_step_3_title: "⚙️ التطوير",
    process_step_3_desc: "هذا هو محرك المنتج 🔥—حيث تتحول الاستراتيجية 🧠 والتصميم 🎨 إلى نظام حقيقي وعامل.\n\nأبني باستخدام Next.js 🚀 وReact ⚛️، أكتب كوداً نظيفاً 🧼، آمناً 🔐، وقابلاً للتوسع 📈 جاهز للإنتاج.\n\nالتركيز على الأداء ⚡، والتحسين لمحركات البحث 🔍، وتحسين محركات الإجابة 🤖، والاستهداف الجغرافي 📍، وإمكانية الوصول ♿، ومؤشرات الويب الأساسية 🧪.\n\nأكامل Google Analytics 📊، وGoogle Search Console 🔎، وأدوات مراقبة الأداء ⏱️ لتتبع سلوك المستخدم الحقيقي ودعم النمو المدعوم بالبيانات 📈 من اليوم الأول.",
    process_step_4_title: "🧪 الاختبار وضمان الجودة",
    process_step_4_desc: "التميز يكمن في التفاصيل 🧠. أختبر المنتج عبر الأجهزة 📱💻، والمتصفحات 🌐، وأحجام الشاشات لضمان تجربة سلسة.\n\nيشمل ذلك اختبار سهولة الاستخدام 🖱️، وفحوصات الأداء ⚡، والتجاوب 📐، والتحقق من الحالات الحدية 🧩.\n\nالهدف ليس فقط الوظائف ✅—بل الثقة، والاستقرار، واللمسات النهائية ✨ قبل الإطلاق.",
    process_step_5_title: "🚀 الإطلاق والنمو",
    process_step_5_desc: "الإقلاع 🚀. يتم نشر المنتج في بيئة إنتاج آمنة 🔐 مع التكوين الصحيح ⚙️ والمراقبة 👀.\n\nأتعامل مع النشر 📦، وإعداد الأمان الأساسي 🛡️، والتحقق من الأداء ⚡ لضمان إطلاق مستقر.\n\nبعد الإطلاق، أقدم التوثيق 📘، والإرشاد 🧭، والدعم المستمر 🤝—حتى يتمكن المنتج من التطور 🔄، والنمو 📈، والازدهار مع عملك 🌱.\n\n⭐ النتيجة النهائية: منتج رقمي استراتيجي 🧠، قابل للقياس 📊، قابل للتوسع 📈، ومبني للنمو 🌍—ليس مجرد موقع.",
    process_read_specs: "قراءة المواصفات",
    process_mobile_title: "كيف أعمل",
    process_mobile_desc: "من المفهوم إلى الكود، رحلة سلسة.",
    process_step_prefix: "خطوة",

    // Tech Stack (Game)
    tech_title_1: "هل أنت ",
    tech_title_2: "مستعد ",
    tech_title_3: "للدخول؟",
    tech_score: "النتيجة",
    tech_weapon: "السلاح",
    tech_combo: "كومبو",
    tech_boss_anomaly: "تم اكتشاف خلل",
    tech_boss_name: "ديون تقنية",
    tech_boss_eliminate: "انقر للإزالة",
    tech_win_title: "المهمة اكتملت",
    tech_win_desc: "لقد أتقنت التقنيات.",
    tech_win_code: "كود حصري",
    tech_win_btn: "استمرار",

    // Contact
    contact_avail: "متاح لمشاريع جديدة",
    contact_title_1: "لنبدأ بناء شيء ",
    contact_title_2: "استثنائي.",
    contact_desc: "لديك الرؤية، ولدي الأدوات. راسلني، ولنحول أفكارك المجردة إلى واقع رقمي ملموس وعالي الأداء.",
    contact_email_btn: "راسلني 📧",
    contact_whatsapp_btn: "تحدث عبر واتساب 💬",

    // FAQ
    faq_badge: "قاعدة المعرفة",
    faq_title_1: "أسئلة ",
    faq_title_2: "شائعة.",
    faq_desc: "الشفافية هي المفتاح. إليك كل ما تحتاج معرفته عن العملية، الأسعار، وكيفية العمل معاً.",
    faq_cta_unsure: "لا تزال غير متأكد؟",
    faq_cta_ask: "اسألني عبر واتساب",
    faq_q1: "كم يستغرق المشروع النموذجي؟",
    faq_a1: "الجدول الزمني يختلف حسب التعقيد. الموقع التعريفي القياسي يستغرق 1-2 أسبوع، بينما المنصات المعقدة قد تستغرق 1-3 أشهر.",
    faq_q2: "هل تقدم دعماً مستمراً؟",
    faq_a2: "نعم، أقدم باقات صيانة لضمان بقاء برمجياتك آمنة، محدثة، وذات أداء عالي.",
    faq_q3: "ما هو \"Vibe Coding\"؟",
    faq_a3: "إنها فلسفتي في دمج الدقة التقنية مع تدفق التصميم البديهي لإنشاء برمجيات تشعر بأنها \"حية\".",
    faq_q4: "هل يمكنك العمل مع فرق موجودة؟",
    faq_a4: "بالتأكيد. لدي خبرة واسعة في الاندماج في سير العمل الحالي، باستخدام Jira و GitHub ومنهجيات Agile.",
    faq_q5: "ما هو نموذج التسعير الخاص بك؟",
    faq_a5: "عادة ما أعمل بنظام التسعير القائم على المشروع، لكنني منفتح على الفوترة بالساعة للاستشارات أو مهام الصيانة.",
    faq_q6: "هل تتعامل مع الاستضافة وإعداد النطاق؟",
    faq_a6: "نعم، يمكنني التعامل مع عملية النشر بأكملها، بما في ذلك إعداد الخادم، تكوين النطاق، وشهادات SSL.",
    faq_q7: "هل مواقعك مهيئة لـ SEO / AEO / GEO؟",
    faq_a7: "نعم! أنا أبني مع وضع تحسين محركات البحث (SEO)، وتحسين محركات الإجابة (AEO)، وتحسين المحركات التوليدية (GEO) في الاعتبار. هذا يعني أن موقعك جاهز لـ Google و ChatGPT ومستقبل البحث بالذكاء الاصطناعي.",

    // Footer
    footer_desc: "صياغة حلول رقمية قوية في تقاطع التصميم والذكاء الاصطناعي.",
    footer_links: "روابط سريعة",
    footer_services: "خدمات",
    footer_stay_updated: "ابق على اطلاع",
    footer_sub_text: "انضم إلى أكثر من 1000 مشترك للحصول على أحدث أخبار الذكاء الاصطناعي وتطوير الويب.",
    footer_email_placeholder: "أدخل بريدك الإلكتروني",
    footer_sub_btn: "اشتراك",
    footer_rights: "جميع الحقوق محفوظة.",
    footer_privacy: "سياسة الخصوصية",
    footer_terms: "شروط الخدمة",
    footer_made_with: "صنع بـ",
    footer_love: " באהבה",

    // Legal
    legal_close: "إغلاق",
    legal_privacy_title: "سياسة الخصوصية",
    legal_privacy_content: "1. جمع المعلومات\nنجمع المعلومات الشخصية مثل الاسم، عنوان البريد الإلكتروني، وتفاصيل المشروع عند إرسال نموذج الاتصال. تستخدم هذه البيانات فقط للتواصل وتقدير المشروع.\n\n2. استخدام المعلومات\nتستخدم بياناتك للرد على الاستفسارات، تقديم الخدمات، وتحسين تجربة موقعنا. لا نبيع أو نتاجر أو نؤجر معلومات هويتك الشخصية للآخرين.\n\n3. أمن البيانات\nنعتمد ممارسات مناسبة لجمع البيانات وتخزينها ومعالجتها وتدابير أمنية للحماية من الوصول غير المصرح به أو التغيير أو الإفصاح أو إتلاف معلوماتك الشخصية.\n\n4. خدمات الطرف الثالث\nقد نستخدم مزودي خدمات طرف ثالث (مثل شركاء الاستضافة) لمساعدتنا في تشغيل أعمالنا. قد نشارك معلوماتك مع هذه الأطراف الثالثة لتلك الأغراض المحدودة.\n\n5. الاتصال\nإذا كان لديك أي أسئلة حول سياسة الخصوصية هذه، يرجى الاتصال بنا عبر النموذج الموجود في هذا الموقع.",
    legal_terms_title: "شروط الخدمة",
    legal_terms_content: "1. قبول الشروط\nمن خلال الوصول إلى هذا الموقع، فإنك توافق على الالتزام بشروط الخدمة هذه وجميع القوانين واللوائح المعمول بها.\n\n2. الملكية الفكرية\nجميع المحتويات الموجودة على هذا الموقع (الكود، التصميم، النصوص، الرسومات) هي ملك لوسيم ما لم يذكر خلاف ذلك. لا يجوز لك إعادة إنتاج أو إعادة توزيع المحتوى دون إذن.\n\n3. الخدمات\nنقدم خدمات تطوير الويب وأتمتة الذكاء الاصطناعي. سيتم توضيح الشروط المحددة والتسليمات وجداول الدفع للمشاريع في اتفاقيات خدمة منفصلة موقعة من قبل الطرفين.\n\n4. حدود المسؤولية\nلا يتحمل وسيم بأي حال من الأحوال المسؤولية عن أي أضرار (بما في ذلك، على سبيل المثال لا الحصر، الأضرار الناجمة عن فقدان البيانات أو الربح) الناشئة عن استخدام أو عدم القدرة على استخدام المواد الموجودة على هذا الموقع.\n\n5. القانون الحاكم\nتخضع هذه الشروط والأحكام وتفسر وفقاً لقوانين إسرائيل وتخضع بشكل غير قابل للنقض للاختصاص القضائي الحصري للمحاكم في ذلك الموقع.",

    // Cookie Banner
    cookie_title: "الخصوصية وملفات تعريف الارتباط",
    cookie_desc: "نستخدم ملفات تعريف الارتباط لتخصيص تجربتك وتحليل حركة المرور لدينا. امتثالاً لقانون حماية الخصوصية، نحترم سيادة بياناتك.",
    cookie_accept: "قبول الكل",
    cookie_decline: "رفض الكل",
    cookie_customize: "تخصيص",
    cookie_save: "حفظ التفضيلات",
    cookie_cat_necessary: "ضرورية للغاية",
    cookie_cat_necessary_desc: "أساسية لعمل الموقع. لا يمكن تعطيلها.",
    cookie_cat_analytics: "التحليلات والأداء",
    cookie_cat_analytics_desc: "تساعدنا في فهم كيفية استخدامك للموقع.",
    cookie_cat_marketing: "التسويق والاستهداف",
    cookie_cat_marketing_desc: "تستخدم لتقديم إعلانات ذات صلة.",

    share: "مشاركة",
    shareVia: "مشاركة عبر",
    socialHub: "تواصل اجتماعي",
    connectSocials: "تواصل معي",
    followMe: "تابعني",
    latestUpdates: "تابع آخر التحديثات وكواليس العمل.",
    followers: "متابعين",
    likes: "إعجابات",
    posts: "منشورات",
    formTitle: "أرسل لي رسالة",
    formSubtitle: "احصل على رد خلال 24 ساعة",
    secureForm: "نموذج آمن",
    autoReply: "رد تلقائي",
    noSpam: "لا للبريد المزعج",
    nameLabel: "الاسم",
    emailLabel: "البريد الإلكتروني",
    projectTypeLabel: "نوع المشروع",
    budgetLabel: "الميزانية المتوقعة",
    messageLabel: "الرسالة",
    minChars: "أحرف كحد أدنى",
    sendMessage: "إرسال الرسالة",
    sending: "جاري الإرسال...",
    successMessage: "تم الإرسال!",
    successDescription: "سأتواصل معك قريباً.",
    sendAnother: "أرسل رسالة أخرى",
    selectOption: "اختر خياراً",
    optWebsite: "موقع إلكتروني",
    optLanding: "صفحة هبوط",
    optFullStack: "تطبيق متكامل",
    optAI: "أداة ذكاء اصطناعي",
    optMaintenance: "صيانة ودعم",
    optOther: "آخر",
    budgetUnder5k: "أقل من 3,000 ₪",
    budget5k10k: "3,000 ₪ - 10,000 ₪",
    budget10k25k: "10,000 ₪ - 25,000 ₪",
    budget25k50k: "25,000 ₪ - 50,000 ₪",
    budget50kPlus: "50,000 ₪+",
    required: "مطلوب",
    invalidEmail: "بريد غير صالح",
    tooShort: "قصير جداً",
    // Wizard
    wizard_step_count: "خطوة {current} من {total}",
    wizard_step1_title: "ماذا سنبني؟",
    wizard_step2_title: "ما هو الأسلوب؟",
    wizard_step3_title: "ما هي الميزانية؟",
    wizard_final_title: "تفاصيل أخيرة",
    wizard_final_desc: "أخبرني المزيد عن رؤيتك.",
    wizard_opt_web: "تطبيق ويب",
    wizard_opt_app: "تطبيق موبايل",
    wizard_opt_ai: "أداة ذكاء اصطناعي",
    wizard_opt_ecom: "متجر إلكتروني",
    wizard_opt_minimal: "بسيط (Minimalist)",
    wizard_opt_bold: "جريء وقوي",
    wizard_opt_corp: "رسمي/شركات",
    wizard_opt_future: "مستقبلي",
    wizard_opt_small: "أقل من 5,000 ₪",
    wizard_opt_medium: "5,000 ₪ - 15,000 ₪",
    wizard_opt_large: "15,000 ₪ - 50,000 ₪",
    wizard_opt_ent: "50,000 ₪+",
    wizard_detail_placeholder: "صف مشروعك بكلمات قليلة...",
    wizard_btn_send: "إرسال طلب المشروع",
    wizard_success_title: "تم استلام الطلب!",
    wizard_success_desc: "لقد استلمت مواصفات مشروعك. سأراجعها وأعود إليك خلال 24 ساعة.",
    wizard_start_over: "بدء طلب جديد",
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('vibe_lang') as Language;
    if (saved && (saved === 'en' || saved === 'he' || saved === 'ar')) {
      return saved;
    }
    const browserLang = navigator.language.split('-')[0];
    return (browserLang === 'he' || browserLang === 'ar') ? (browserLang as Language) : 'en';
  });

  const dir = language === 'en' ? 'ltr' : 'rtl';

  useEffect(() => {
    localStorage.setItem('vibe_lang', language);
    document.documentElement.lang = language;
    document.documentElement.dir = dir;
  }, [language, dir]);

  const t = (key: string) => {
    return TRANSLATIONS[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, dir, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};