import type { Language } from '@/types';

export const VIDEO_AD = {
  src: '/assets/video-ads/greentouch-house.mp4',
  poster: '/assets/video-ads/greentouch-poster.webp',
  thumbnail: '/assets/video-ads/greentouch-thumbnail.webp',
  duration: 27,
};

export const videoAdsCopy = {
  en: {
    title: 'Video Ads for Brands | Waseem',
    heading: 'Your products.\nA story in motion.',
    intro: 'Social video ads made from your product photos. Thoughtful pacing, clear captions, and a reason to get in touch.',
    category: 'Video ads for brands',
    watch: 'Watch the 27-second ad',
    sound: 'Music on. Press play to watch with sound.',
    cta: 'Get a video for your business',
    prefill: 'Hi Waseem, I saw your GreenTouch video concept and would like a social video ad for my business.',
    concept: 'Portfolio concept',
    disclosure: 'A self-initiated portfolio concept, not a commissioned campaign. No campaign results are claimed.',
    project: 'GreenTouch',
    summary: 'Six product photos. One short story.',
    detail: 'An artificial-plant ad built around a simple reveal: it looks real, without the maintenance. The edit moves from cactus interiors to green walls, ending with the installation message.',
    brief: 'The idea',
    craft: 'The edit',
    craftText: 'Original photos kept intact, gentle motion, Hebrew captions, and Beach House Beat by AbsoluteSound, edited to a 27-second soundtrack.',
    format: 'The format',
    formatText: '27 seconds · Vertical 9:16 · 1080p',
    platforms: 'For Instagram Reels, TikTok, and Meta placements.',
    ask: 'Have the photos? Let’s make them move.',
    askText: 'Send your product photos and tell me what you want people to notice. We’ll shape the message, edit, and final call to action around your business.',
    previewTitle: 'Product photos, made for the feed.',
    previewText: 'Explore GreenTouch: a 27-second concept ad with motion, Hebrew captions, and music.',
    explore: 'Explore video ads',
    back: 'Back to portfolio',
    unavailable: 'The video could not play. You can open the MP4 directly below.',
    direct: 'Open video file',
    transcript: 'Read the ad’s message',
    lines: ['Wait… are these real?', 'None of them are.', 'All artificial.', 'No water. No light. No maintenance.', 'And this? Also us.', 'Green walls for every space.', 'Looks alive, 365 days a year.', 'GreenTouch — installation nationwide.'],
  },
  he: {
    title: 'סרטוני פרסום לעסקים | Waseem',
    heading: 'המוצרים שלכם.\nסיפור בתנועה.',
    intro: 'סרטוני סושיאל מתמונות המוצרים שלכם. עריכה קצבית, כיתובים ברורים ומסר שמזמין ליצור קשר.',
    category: 'סרטוני פרסום לעסקים',
    watch: 'צפו בסרטון — 27 שניות',
    sound: 'כולל מוזיקה. לחצו להפעלה עם סאונד.',
    cta: 'רוצים סרטון לעסק שלכם?',
    prefill: 'היי ואסים, ראיתי את סרטון הקונספט של GreenTouch ואשמח לסרטון סושיאל לעסק שלי.',
    concept: 'קונספט לתיק עבודות',
    disclosure: 'פרויקט קונספט עצמאי לתיק העבודות, ולא קמפיין שהוזמן מהמותג. לא מוצגות תוצאות קמפיין.',
    project: 'GreenTouch',
    summary: 'שש תמונות מוצר. סיפור קצר אחד.',
    detail: 'סרטון לצמחים מלאכותיים עם טוויסט פשוט: נראים אמיתיים, בלי התחזוקה. העריכה עוברת מקקטוסים בחלל פנימי לקירות ירוקים, ומסתיימת במסר ההתקנה.',
    brief: 'הרעיון',
    craft: 'העריכה',
    craftText: 'התמונות המקוריות בשלמותן, תנועה עדינה, כיתובים בעברית וקטע מתוך Beach House Beat של AbsoluteSound בעריכה ל־27 שניות.',
    format: 'הפורמט',
    formatText: '27 שניות · אנכי 9:16 · 1080p',
    platforms: 'לרילס באינסטגרם, לטיקטוק ולמודעות Meta.',
    ask: 'יש לכם תמונות? בואו ניתן להן תנועה.',
    askText: 'שלחו את תמונות המוצרים וספרו מה תרצו להבליט. נתאים לעסק שלכם את המסר, העריכה וההנעה לפעולה.',
    previewTitle: 'תמונות מוצר שמקבלות תנועה.',
    previewText: 'הכירו את GreenTouch: סרטון קונספט של 27 שניות עם תנועה, כיתובים בעברית ומוזיקה.',
    explore: 'לצפייה בסרטוני הפרסום',
    back: 'חזרה לתיק העבודות',
    unavailable: 'לא ניתן להפעיל את הסרטון. אפשר לפתוח את קובץ הווידאו בקישור למטה.',
    direct: 'פתיחת קובץ הסרטון',
    transcript: 'לקריאת הטקסט שבסרטון',
    lines: ['רגע… אלה אמיתיים?', 'אף אחד מהם לא.', 'הכל מלאכותי.', 'בלי מים. בלי אור. בלי טיפול.', 'וזה? גם אנחנו.', 'קירות ירוקים לכל חלל.', 'נראה חי — 365 ימים בשנה.', 'GreenTouch — התקנה בכל הארץ.'],
  },
  ar: {
    title: 'إعلانات فيديو للأعمال | Waseem',
    heading: 'منتجاتكم.\nقصة تتحرّك.',
    intro: 'إعلانات للسوشيال ميديا من صور منتجاتكم. مونتاج بإيقاع مدروس، نصوص واضحة ورسالة تشجّع على التواصل.',
    category: 'إعلانات فيديو للأعمال',
    watch: 'شاهد الإعلان — 27 ثانية',
    sound: 'مع موسيقى. اضغط للتشغيل بالصوت.',
    cta: 'تريدون فيديو لمشروعكم؟',
    prefill: 'مرحباً وسيم، شاهدت نموذج إعلان GreenTouch وأرغب بفيديو للسوشيال ميديا لمشروعي.',
    concept: 'نموذج لملف الأعمال',
    disclosure: 'نموذج مستقل لعرض المهارات، وليس حملة بتكليف من العلامة التجارية. لا نعرض نتائج حملة إعلانية.',
    project: 'GreenTouch',
    summary: 'ست صور منتجات. قصة قصيرة واحدة.',
    detail: 'إعلان للنباتات الاصطناعية بفكرة بسيطة: مظهر طبيعي دون عناية. ينتقل المونتاج من الصبّار الداخلي إلى الجدران الخضراء، وينتهي برسالة التركيب.',
    brief: 'الفكرة',
    craft: 'المونتاج',
    craftText: 'الصور الأصلية كاملة، حركة هادئة، نصوص بالعبرية ومقطع من Beach House Beat للمؤلف AbsoluteSound، بمونتاج موسيقي مدته 27 ثانية.',
    format: 'الصيغة',
    formatText: '27 ثانية · عمودي 9:16 · 1080p',
    platforms: 'لريلز إنستغرام وتيك توك وإعلانات Meta.',
    ask: 'لديكم الصور؟ لنمنحها الحركة.',
    askText: 'أرسلوا صور المنتجات وأخبروني بما تريدون إبرازه. نطوّر الرسالة والمونتاج والدعوة للتواصل بما يناسب مشروعكم.',
    previewTitle: 'صور منتجات تنبض بالحركة.',
    previewText: 'اكتشفوا GreenTouch: نموذج إعلان مدته 27 ثانية مع حركة ونصوص بالعبرية وموسيقى.',
    explore: 'استكشف إعلانات الفيديو',
    back: 'العودة إلى ملف الأعمال',
    unavailable: 'تعذّر تشغيل الفيديو. يمكنكم فتح ملف الفيديو مباشرة من الرابط أدناه.',
    direct: 'فتح ملف الفيديو',
    transcript: 'اقرأ رسالة الإعلان',
    lines: ['لحظة… هل هذه حقيقية؟', 'ولا واحدة منها.', 'كلها اصطناعية.', 'بلا ماء. بلا ضوء. بلا عناية.', 'وهذا؟ أيضاً منّا.', 'جدران خضراء لكل مساحة.', 'تبدو حيّة، 365 يوماً في السنة.', 'GreenTouch — تركيب في جميع أنحاء البلاد.'],
  },
} satisfies Record<Language, Record<string, string | string[]>>;
