// Blog content, separated from the generator (scripts/generate-blog.mjs) so the
// templating and the copy live apart. Each article has a shared `slug` and an
// `i18n` map with one block per language it exists in:
//   { title, desc, excerpt, category, tldr, body[], faq[], sources[] }
// body block: { p } | { h2 } | { ul:[] } | { cta }
// An article renders only in the languages present in its `i18n`.
//
// Accuracy note: factual claims here are kept verifiable and, where a claim
// benefits from backing, `sources[]` links an authoritative primary reference
// (Google, web.dev, Three.js, MDN). No invented statistics.

export const ARTICLES = [
  // === PILLAR: 3D / interactive / "wow" web design (he / en / ar) ===========
  {
    slug: 'itzuv-atarim-3d',
    i18n: {
      he: {
        category: 'עיצוב',
        title: 'עיצוב אתרים תלת-ממדי (3D): מתי זה מכפיל המרות ומתי זה פוגע',
        desc: 'מה זה עיצוב אתרים תלת-ממדי, מתי כדאי אתר 3D אינטראקטיבי לעסק, ואיך בונים חוויית "וואו" בלי לפגוע במהירות וב-SEO.',
        excerpt: 'אתר תלת-ממדי יכול להשאיר רושם בלתי נשכח — או להרוס את המהירות. הנה מתי זה שווה, ואיך עושים את זה נכון.',
        tldr: 'עיצוב אתרים תלת-ממדי משתמש ב-WebGL (בדרך כלל דרך Three.js / React Three Fiber) כדי ליצור חוויות אינטראקטיביות שמגדילות זכירוּת מותג וזמן שהייה. זה שווה כשהבידול חשוב (מותג יוקרתי, מוצר להצגה, פורטפוליו) — אבל חייבים תקציב ביצועים, גרסת גיבוי לנייד ונגישות, אחרת זה פוגע במהירות וב-SEO. הכלל: הפאנץ׳ הויזואלי קודם, אף פעם לא על חשבון טעינה מהירה.',
        body: [
          { p: 'רוב האתרים נראים אותו דבר. עיצוב תלת-ממדי (3D) הוא אחת הדרכים הבודדות לגרום למבקר לעצור ולהגיד "וואו" — אלמנט שמסתובב, סצנה שמגיבה לגלילה, מוצר שאפשר לסובב בעצמך. אבל בדיוק כמו כל כלי חזק, הוא יכול גם להזיק אם משתמשים בו לא נכון. הנה התמונה המלאה.' },
          { h2: 'מה זה בעצם עיצוב אתרים תלת-ממדי' },
          { p: 'תלת-ממד באתר מבוסס על WebGL — טכנולוגיה שמריצה גרפיקה בזמן אמת ישירות בדפדפן, באמצעות כרטיס המסך של המבקר, בלי שום תוסף. בפועל בונים את זה עם ספריות כמו Three.js, ולרוב React Three Fiber שמחבר את זה לאתר React. זה מה שמאפשר מונוגרמה זכוכיתית שמסתובבת, קרוסלת פרויקטים תלת-ממדית או רקע שמגיב לתנועת העכבר — הכל חלק, בלי סרטון כבד.' },
          { h2: 'מתי 3D באמת שווה לעסק' },
          { p: 'תלת-ממד הוא לא קישוט — הוא כלי מיתוגי. הוא משתלם כשהמטרה היא להיתפס כפרימיום, שונה וזכיר:' },
          { ul: [
            'מותג יוקרתי או פרימיום שרוצה להיבדל מהמתחרים.',
            'מוצר פיזי שכדאי להציג מכל זווית (רהיטים, תכשיטים, גאדג׳טים).',
            'פורטפוליו של מעצב/סטודיו שבו האתר עצמו הוא ההוכחה ליכולת.',
            'עמוד נחיתה לקמפיין שבו "עצירה של שנייה" שווה זהב.',
          ] },
          { h2: 'מתי דווקא לא כדאי' },
          { p: 'לא כל אתר צריך 3D. אם המטרה היא מידע מהיר — אתר תדמית מקומי, בלוג, אתר שירות שבו הלקוח רק רוצה מספר טלפון — תלת-ממד כבד רק יאט ויסיח את הדעת. במקרים האלה עדיף אתר מהיר, נקי, עם אולי מגע 3D קטן אחד בכותרת, לא יותר.' },
          { h2: 'הסכנה האמיתית: מהירות ו-SEO' },
          { p: 'זו הנקודה שבה רוב אתרי ה-3D נכשלים. גרפיקה תלת-ממדית כבדה יכולה להאט את הטעינה, וגוגל מדרג לפי חוויית עמוד ומהירות (Core Web Vitals). אתר מרשים שנטען לאט יפסיד בדירוג — ובלקוחות שעוזבים לפני שהעמוד עלה. הפתרון הוא לא לוותר על 3D, אלא לבנות אותו עם תקציב ביצועים: טעינה עצלה, הגבלת רזולוציה בנייד, וקוד שנטען רק כשצריך.' },
          { h2: 'איך עושים "וואו" בלי לשבור את המהירות' },
          { ul: [
            'גרסת גיבוי אמיתית: מכשירים חלשים, חוסכי-סוללה או מי שביקש "פחות תנועה" מקבלים אתר קלאסי מהיר — לא מסך שחור.',
            'נגישות: כל התוכן חייב להיות קיים גם כטקסט אמיתי (לקוראי מסך ולגוגל), מעבר לסצנה הויזואלית.',
            'תקציב ביצועים: הגבלת פיקסלים בנייד, טעינה מדורגת, ומדידה מול Core Web Vitals לפני עלייה לאוויר.',
            'ריסון: אפקט אחד חזק ומדויק מנצח עשרה אפקטים שמעמיסים על העמוד.',
          ] },
          { p: 'האתר הזה עצמו הוא דוגמה חיה: חוויה תלת-ממדית מלאה עם גיבוי קלאסי מלא לכל מי שלא יכול להריץ אותה — כדי שהמהירות וה-SEO אף פעם לא נפגעים. ככה בונים "וואו" שגם עובד.' },
          { cta: 'רוצים אתר שגורם ללקוחות לעצור? בואו נדבר' },
        ],
        faq: [
          { q: 'האם אתר תלת-ממדי פוגע ב-SEO?', a: 'לא בהכרח. הוא פוגע רק אם הוא בנוי לא נכון ומאט את הטעינה. עם טעינה עצלה, גרסת גיבוי וטקסט אמיתי מאחורי הסצנה — אתר 3D יכול להישאר מהיר, נגיש ומדורג היטב בגוגל.' },
          { q: 'האם זה עובד בנייד?', a: 'כן, אם בונים נכון. בנייד מגבילים את הרזולוציה ואת עוצמת האפקטים, ומכשירים חלשים מקבלים גרסה קלה יותר — כך שהחוויה נשארת חלקה בלי לרוקן סוללה.' },
          { q: 'כמה יותר יקר אתר 3D מאתר רגיל?', a: 'הוא דורש יותר עבודת פיתוח ועיצוב, ולכן יקר יותר מאתר תדמית סטנדרטי. הכי חכם להתחיל במגע 3D ממוקד במקום אחד מרכזי, ולהרחיב לפי הצורך.' },
          { q: 'האם צריך תוסף או אפליקציה כדי לראות 3D באתר?', a: 'לא. תלת-ממד באתר מבוסס WebGL ורץ ישירות בכל דפדפן מודרני, בלי שום התקנה מצד המבקר.' },
        ],
        sources: [
          { name: 'Google — Core Web Vitals ודירוג', url: 'https://developers.google.com/search/docs/appearance/page-experience' },
          { name: 'web.dev — Web Vitals', url: 'https://web.dev/articles/vitals' },
          { name: 'Three.js', url: 'https://threejs.org/' },
          { name: 'MDN — WebGL', url: 'https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API' },
        ],
      },
      en: {
        category: 'Design',
        title: '3D Web Design: When It Doubles Conversions — and When It Hurts',
        desc: 'What 3D web design is, when an interactive 3D website is worth it for a business, and how to build a "wow" experience without hurting speed or SEO.',
        excerpt: 'A 3D website can leave an unforgettable impression — or wreck your load time. Here is when it is worth it, and how to do it right.',
        tldr: '3D web design uses WebGL (usually via Three.js / React Three Fiber) to build interactive experiences that raise brand recall and time on page. It is worth it when differentiation matters — a premium brand, a product to showcase, a portfolio — but it needs a performance budget, a mobile fallback and real accessibility, or it hurts speed and SEO. The rule: the visual punch never comes at the cost of a fast load.',
        body: [
          { p: 'Most websites look the same. 3D design is one of the few ways to make a visitor stop and say "wow" — an element that rotates, a scene that reacts to scroll, a product you can spin yourself. But like any powerful tool, it can also do damage when used wrong. Here is the full picture.' },
          { h2: 'What 3D web design actually is' },
          { p: 'On the web, 3D runs on WebGL — technology that renders real-time graphics directly in the browser using the visitor\'s GPU, with no plugin. In practice it is built with libraries like Three.js, and often React Three Fiber, which wires it into a React site. That is what powers a rotating glass monogram, a 3D project carousel, or a background that reacts to the cursor — all smooth, with no heavy video.' },
          { h2: 'When 3D is genuinely worth it' },
          { p: '3D is not decoration — it is a branding tool. It pays off when the goal is to feel premium, distinct and memorable:' },
          { ul: [
            'A luxury or premium brand that wants to stand apart from competitors.',
            'A physical product worth showing from every angle (furniture, jewelry, gadgets).',
            'A designer/studio portfolio where the site itself is the proof of skill.',
            'A campaign landing page where a one-second pause is worth gold.',
          ] },
          { h2: 'When to skip it' },
          { p: 'Not every site needs 3D. If the goal is fast information — a local business site, a blog, a service site where the client just wants a phone number — heavy 3D only slows things down and distracts. There, a fast, clean site with maybe one small 3D touch in the header is the better call.' },
          { h2: 'The real risk: speed and SEO' },
          { p: 'This is where most 3D sites fail. Heavy 3D graphics can slow the load, and Google ranks on page experience and speed (Core Web Vitals). An impressive site that loads slowly loses rankings — and loses visitors who leave before the page appears. The fix is not to drop 3D, but to build it with a performance budget: lazy loading, capped resolution on mobile, and code that loads only when needed.' },
          { h2: 'How to get the "wow" without breaking speed' },
          { ul: [
            'A real fallback: weak devices, battery-savers, or anyone who asked for "reduced motion" get a fast classic site — never a black screen.',
            'Accessibility: all content must also exist as real text (for screen readers and Google), beyond the visual scene.',
            'A performance budget: capped pixels on mobile, staged loading, and measuring against Core Web Vitals before launch.',
            'Restraint: one strong, precise effect beats ten that bog the page down.',
          ] },
          { p: 'This very site is a live example: a full 3D experience with a complete classic fallback for anyone who cannot run it — so speed and SEO are never sacrificed. That is how you build a "wow" that also works.' },
          { cta: 'Want a site that makes clients stop? Let\'s talk' },
        ],
        faq: [
          { q: 'Does a 3D website hurt SEO?', a: 'Not inherently. It only hurts if it is built badly and slows the load. With lazy loading, a fallback and real text behind the scene, a 3D site can stay fast, accessible and rank well on Google.' },
          { q: 'Does it work on mobile?', a: 'Yes, when built right. On mobile you cap the resolution and effect intensity, and weak devices get a lighter version — so the experience stays smooth without draining the battery.' },
          { q: 'How much more expensive is a 3D site?', a: 'It takes more development and design work, so it costs more than a standard brochure site. The smart move is to start with one focused 3D touch and expand as needed.' },
          { q: 'Do visitors need a plugin or app to see 3D?', a: 'No. Web 3D is WebGL-based and runs directly in any modern browser, with nothing to install on the visitor\'s side.' },
        ],
        sources: [
          { name: 'Google — Page experience & Core Web Vitals', url: 'https://developers.google.com/search/docs/appearance/page-experience' },
          { name: 'web.dev — Web Vitals', url: 'https://web.dev/articles/vitals' },
          { name: 'Three.js', url: 'https://threejs.org/' },
          { name: 'MDN — WebGL', url: 'https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API' },
        ],
      },
      ar: {
        category: 'تصميم',
        title: 'تصميم المواقع ثلاثي الأبعاد (3D): متى يضاعف التحويلات ومتى يضرّ',
        desc: 'ما هو تصميم المواقع ثلاثي الأبعاد، متى يستحق موقع 3D تفاعلي لعملك، وكيف تبني تجربة "واو" دون الإضرار بالسرعة و-SEO.',
        excerpt: 'الموقع ثلاثي الأبعاد قد يترك انطباعًا لا يُنسى — أو يدمّر سرعة التحميل. إليك متى يستحق، وكيف تفعله بشكل صحيح.',
        tldr: 'تصميم المواقع ثلاثي الأبعاد يستخدم WebGL (عادةً عبر Three.js / React Three Fiber) لبناء تجارب تفاعلية ترفع تذكّر العلامة ووقت البقاء. يستحق حين يكون التميّز مهمًا — علامة فاخرة، منتج للعرض، بورتفوليو — لكنه يحتاج ميزانية أداء ونسخة بديلة للجوال وإتاحة حقيقية، وإلا أضرّ بالسرعة و-SEO. القاعدة: التأثير البصري لا يأتي أبدًا على حساب تحميل سريع.' ,
        body: [
          { p: 'معظم المواقع تبدو متشابهة. التصميم ثلاثي الأبعاد هو أحد الطرق القليلة لجعل الزائر يتوقف ويقول "واو" — عنصر يدور، مشهد يتفاعل مع التمرير، منتج تديره بنفسك. لكن كأي أداة قوية، قد يضرّ إن استُخدم بشكل خاطئ. إليك الصورة الكاملة.' },
          { h2: 'ما هو تصميم المواقع ثلاثي الأبعاد فعليًا' },
          { p: 'على الويب، يعمل الـ3D عبر WebGL — تقنية تعرض رسومات في الوقت الفعلي مباشرة في المتصفح باستخدام كرت الشاشة لدى الزائر، دون أي إضافة. عمليًا يُبنى بمكتبات مثل Three.js وغالبًا React Three Fiber التي تربطه بموقع React. هذا ما يتيح شعارًا زجاجيًا يدور، أو معرض مشاريع ثلاثي الأبعاد، أو خلفية تتفاعل مع المؤشر — كل ذلك بسلاسة ودون فيديو ثقيل.' },
          { h2: 'متى يستحق الـ3D فعلاً' },
          { p: 'الـ3D ليس زينة — إنه أداة علامة تجارية. يؤتي ثماره حين يكون الهدف الظهور كعلامة راقية ومميزة ولا تُنسى:' },
          { ul: [
            'علامة فاخرة تريد التميّز عن المنافسين.',
            'منتج مادي يستحق العرض من كل زاوية (أثاث، مجوهرات، أجهزة).',
            'بورتفوليو لمصمّم/استوديو حيث الموقع نفسه دليل المهارة.',
            'صفحة هبوط لحملة، حيث توقّف لثانية يساوي ذهبًا.',
          ] },
          { h2: 'متى يُفضّل تجنّبه' },
          { p: 'ليس كل موقع يحتاج 3D. إن كان الهدف معلومة سريعة — موقع محلي، مدونة، موقع خدمة يريد فيه العميل رقم هاتف فقط — فالـ3D الثقيل يُبطئ ويشتّت فقط. هنا الأفضل موقع سريع ونظيف، مع ربما لمسة 3D صغيرة في الترويسة، لا أكثر.' },
          { h2: 'الخطر الحقيقي: السرعة و-SEO' },
          { p: 'هنا تفشل معظم مواقع الـ3D. الرسومات الثقيلة قد تُبطئ التحميل، وجوجل يرتّب حسب تجربة الصفحة والسرعة (Core Web Vitals). موقع مبهر يُحمّل ببطء يخسر الترتيب — ويخسر زوارًا يغادرون قبل ظهور الصفحة. الحل ليس التخلي عن الـ3D، بل بناؤه بميزانية أداء: تحميل كسول، تحديد الدقة على الجوال، وكود يُحمّل عند الحاجة فقط.' },
          { h2: 'كيف تحصل على "الواو" دون كسر السرعة' },
          { ul: [
            'نسخة بديلة حقيقية: الأجهزة الضعيفة أو موفّرات الطاقة أو من طلب "حركة أقل" يحصلون على موقع كلاسيكي سريع — لا شاشة سوداء.',
            'الإتاحة: يجب أن يوجد كل المحتوى كنص حقيقي أيضًا (لقارئات الشاشة ولجوجل)، إلى جانب المشهد البصري.',
            'ميزانية أداء: تحديد البكسلات على الجوال، تحميل متدرّج، وقياس مقابل Core Web Vitals قبل الإطلاق.',
            'الاعتدال: تأثير واحد قوي ودقيق يتفوّق على عشرة تُثقل الصفحة.',
          ] },
          { p: 'هذا الموقع نفسه مثال حيّ: تجربة ثلاثية الأبعاد كاملة مع نسخة كلاسيكية بديلة كاملة لمن لا يستطيع تشغيلها — كي لا تتأثر السرعة و-SEO أبدًا. هكذا تُبنى "واو" تعمل أيضًا.' },
          { cta: 'تريد موقعًا يجعل العملاء يتوقفون؟ لنتحدث' },
        ],
        faq: [
          { q: 'هل الموقع ثلاثي الأبعاد يضرّ بـ SEO؟', a: 'ليس بالضرورة. يضرّ فقط إن بُني بشكل خاطئ وأبطأ التحميل. مع التحميل الكسول ونسخة بديلة ونص حقيقي خلف المشهد، يبقى موقع الـ3D سريعًا ومتاحًا ويحتل ترتيبًا جيدًا في جوجل.' },
          { q: 'هل يعمل على الجوال؟', a: 'نعم، إن بُني بشكل صحيح. على الجوال تُحدَّد الدقة وشدة التأثيرات، وتحصل الأجهزة الضعيفة على نسخة أخف — فتبقى التجربة سلسة دون استنزاف البطارية.' },
          { q: 'كم يزيد سعر موقع 3D عن موقع عادي؟', a: 'يتطلب عمل تطوير وتصميم أكثر، لذا يكلّف أكثر من موقع تعريفي قياسي. الأذكى البدء بلمسة 3D مركّزة والتوسّع حسب الحاجة.' },
          { q: 'هل يحتاج الزائر إضافة أو تطبيقًا لرؤية الـ3D؟', a: 'لا. الـ3D على الويب قائم على WebGL ويعمل مباشرة في أي متصفح حديث، دون تثبيت أي شيء لدى الزائر.' },
        ],
        sources: [
          { name: 'Google — تجربة الصفحة و Core Web Vitals', url: 'https://developers.google.com/search/docs/appearance/page-experience' },
          { name: 'web.dev — Web Vitals', url: 'https://web.dev/articles/vitals' },
          { name: 'Three.js', url: 'https://threejs.org/' },
          { name: 'MDN — WebGL', url: 'https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API' },
        ],
      },
    },
  },

  // === CLUSTER: AI automation / WhatsApp for business (he / en / ar) =========
  {
    slug: 'automatzia-esek-ai',
    i18n: {
      he: {
        category: 'אוטומציה ו-AI',
        title: 'אוטומציה עסקית עם AI: איך לחסוך שעות ולתת שירות 24/7',
        desc: 'מה זו אוטומציה עסקית מבוססת בינה מלאכותית, אילו תהליכים כדאי להפוך לאוטומטיים, ואיך זה חוסך שעות עבודה ומגדיל מכירות — בלי להחליף את הצוות.',
        excerpt: 'צ׳אטבוט שעונה לבד, תיאום תורים אוטומטי, מעקב לידים — איך AI עושה את העבודה החוזרת במקומכם, מסביב לשעון.',
        tldr: 'אוטומציה עסקית עם AI מעבירה משימות חוזרות — מענה ראשוני ללקוחות, תיאום פגישות, מעקב לידים ויצירת תוכן — ליד רובוטית שעובדת 24/7. התוצאה: פחות שעות על עבודה שחוזרת על עצמה, מענה מיידי שמונע נטישת לקוחות, ועקביות. הכי חכם להתחיל מנקודת הכאב הכי גדולה (למשל מענה בוואטסאפ) ולהרחיב משם.',
        body: [
          { p: 'רוב העסקים הקטנים מאבדים זמן וכסף על אותן משימות חוזרות: לענות שוב ושוב לאותן שאלות, לתאם פגישות בטלפון, לרדוף אחרי לידים. אוטומציה מבוססת בינה מלאכותית לוקחת את החלק החוזר הזה ומריצה אותו לבד — כדי שתתפנו לעבודה שבאמת מזיזה את העסק.' },
          { h2: 'מה זו בעצם אוטומציה עסקית עם AI' },
          { p: 'זה חיבור של כלים חכמים (צ׳אטבוט, מערכת תיאום, אינטגרציות) שמבצעים תהליך שלם בלי התערבות ידנית. לדוגמה: לקוח שולח הודעה בוואטסאפ ← הבוט עונה, מבין מה הוא צריך, קובע לו תור ביומן ושולח תזכורת — הכל אוטומטית. ה-AI הוא מה שמאפשר לבוט להבין שפה חופשית, לא רק תפריט לחצנים.' },
          { h2: 'אילו תהליכים הכי משתלם להפוך לאוטומטיים' },
          { ul: [
            'מענה ראשוני ללקוחות — שאלות נפוצות, שעות פעילות, מחירים, זמינות — 24/7.',
            'תיאום וזימון תורים — הלקוח קובע לבד ביומן שלכם, בלי שיחות הלוך-ושוב.',
            'מעקב לידים — תיוג, שליחת הודעת המשך אוטומטית, והתראה כשליד חם דורש טיפול.',
            'יצירת תוכן — טיוטות לפוסטים, תשובות, תיאורי מוצר — במהירות ובטון אחיד.',
          ] },
          { h2: 'למה זה שווה כסף אמיתי' },
          { p: 'שני דברים: זמן ולקוחות. כל שעה שהבוט עונה במקומכם היא שעה שחוזרת אליכם. וחשוב מזה — מהירות תגובה. לקוח שמקבל תשובה תוך שניות נשאר; לקוח שמחכה שעה כבר פנה למתחרה. מענה מיידי, גם ב-3 בלילה, הוא לרוב ההבדל בין ליד שנסגר לליד שאבד.' },
          { h2: 'מאיפה מתחילים' },
          { p: 'לא צריך להפוך הכל לאוטומטי ביום אחד. מתחילים מנקודת הכאב הכי גדולה — לרוב זה המענה בוואטסאפ — מטמיעים שם בוט חכם, מודדים כמה זמן ולידים זה מחזיר, ומרחיבים משם לתיאום תורים ומעקב. ככה רואים החזר מהיר בלי פרויקט ענק.' },
          { cta: 'רוצים לראות אילו תהליכים בעסק שלכם אפשר להפוך לאוטומטיים?' },
        ],
        faq: [
          { q: 'האם אוטומציה עם AI מחליפה עובדים?', a: 'לא. היא מסירה מהצוות את העבודה החוזרת והמתישה (מענה לאותן שאלות, תיאומים ידניים) כדי שיתפנו למה שדורש בן אדם — סגירת עסקאות, יחס אישי ומקרים מורכבים. המטרה היא להעצים את הצוות, לא להחליף אותו.' },
          { q: 'כמה זמן לוקח להטמיע אוטומציה בעסק?', a: 'תהליך ממוקד אחד — למשל בוט וואטסאפ שעונה על שאלות נפוצות וקובע תורים — אפשר להעלות לאוויר תוך ימים עד שבועיים, תלוי במורכבות ובאינטגרציות. מומלץ להתחיל קטן ולהרחיב.' },
          { q: 'האם צריך ידע טכני כדי לתחזק את זה?', a: 'לא. אני בונה את המערכת כך שתעבוד לבד, ומגדיר אותה בהתאם לעסק. עדכונים פשוטים (שעות, מחירים, תשובות) אפשר לעשות דרך ממשק נוח, בלי לגעת בקוד.' },
        ],
        sources: [
          { name: 'WhatsApp Business Platform (Meta)', url: 'https://developers.facebook.com/docs/whatsapp' },
          { name: 'Google Calendar API', url: 'https://developers.google.com/calendar' },
        ],
      },
      en: {
        category: 'AI & Automation',
        title: 'Business Automation with AI: Save Hours and Serve Customers 24/7',
        desc: 'What AI-powered business automation is, which processes are worth automating, and how it saves work hours and grows sales — without replacing your team.',
        excerpt: 'A chatbot that answers on its own, automated booking, lead follow-up — how AI does the repetitive work for you, around the clock.',
        tldr: 'AI business automation hands repetitive tasks — first-line customer replies, scheduling, lead follow-up and content — to a robotic teammate that works 24/7. The result: fewer hours on repetitive work, instant responses that stop customers from leaving, and consistency. The smart move is to start at your biggest pain point (often WhatsApp replies) and expand from there.',
        body: [
          { p: 'Most small businesses lose time and money on the same repetitive tasks: answering the same questions over and over, booking appointments by phone, chasing leads. AI-powered automation takes that repetitive part and runs it on its own — so you are free for the work that actually moves the business.' },
          { h2: 'What AI business automation actually is' },
          { p: 'It is a combination of smart tools (a chatbot, a scheduling system, integrations) that run a whole process with no manual work. For example: a customer sends a WhatsApp message → the bot replies, understands what they need, books them a slot in your calendar and sends a reminder — all automatically. AI is what lets the bot understand free language, not just a menu of buttons.' },
          { h2: 'Which processes are most worth automating' },
          { ul: [
            'First-line customer replies — FAQs, opening hours, prices, availability — 24/7.',
            'Scheduling and booking — the customer books into your calendar themselves, with no back-and-forth calls.',
            'Lead follow-up — tagging, an automatic follow-up message, and an alert when a hot lead needs attention.',
            'Content — drafts for posts, replies, product descriptions — fast and in a consistent tone.',
          ] },
          { h2: 'Why it is worth real money' },
          { p: 'Two things: time and customers. Every hour the bot answers for you is an hour you get back. And more importantly — response speed. A customer who gets an answer in seconds stays; one who waits an hour has already gone to a competitor. An instant reply, even at 3am, is often the difference between a lead that closes and one that is lost.' },
          { h2: 'Where to start' },
          { p: 'You do not need to automate everything at once. Start at your biggest pain point — usually WhatsApp replies — put a smart bot there, measure how much time and how many leads it returns, and expand from there to booking and follow-up. That way you see a fast return without a huge project.' },
          { cta: 'Want to see which processes in your business can be automated?' },
        ],
        faq: [
          { q: 'Does AI automation replace employees?', a: 'No. It takes the repetitive, draining work off your team (answering the same questions, manual scheduling) so they are free for what needs a human — closing deals, personal care and complex cases. The goal is to empower the team, not replace it.' },
          { q: 'How long does it take to implement automation?', a: 'One focused process — say a WhatsApp bot that answers FAQs and books appointments — can go live in a few days to two weeks, depending on complexity and integrations. It is best to start small and expand.' },
          { q: 'Do I need technical knowledge to maintain it?', a: 'No. I build the system to run on its own and configure it to your business. Simple updates (hours, prices, answers) can be made through a friendly interface, without touching code.' },
        ],
        sources: [
          { name: 'WhatsApp Business Platform (Meta)', url: 'https://developers.facebook.com/docs/whatsapp' },
          { name: 'Google Calendar API', url: 'https://developers.google.com/calendar' },
        ],
      },
      ar: {
        category: 'الأتمتة والذكاء الاصطناعي',
        title: 'أتمتة الأعمال بالذكاء الاصطناعي: وفّر ساعات وقدّم خدمة 24/7',
        desc: 'ما هي أتمتة الأعمال المدعومة بالذكاء الاصطناعي، وأيّ العمليات يستحقّ أتمتتها، وكيف توفّر ساعات عمل وتزيد المبيعات — دون استبدال فريقك.',
        excerpt: 'روبوت محادثة يجيب وحده، حجز مواعيد تلقائي، متابعة العملاء المحتملين — كيف يؤدّي الذكاء الاصطناعي العمل المتكرّر عنك، على مدار الساعة.',
        tldr: 'أتمتة الأعمال بالذكاء الاصطناعي تُسند المهام المتكرّرة — الردّ الأوّلي على العملاء، وحجز المواعيد، ومتابعة العملاء المحتملين، وإنشاء المحتوى — إلى زميل روبوتي يعمل 24/7. النتيجة: ساعات أقل على العمل المتكرّر، وردود فورية تمنع مغادرة العملاء، وثبات. الأذكى البدء من أكبر نقطة ألم (غالباً ردود واتساب) والتوسّع منها.',
        body: [
          { p: 'معظم الأعمال الصغيرة تخسر وقتاً ومالاً على المهام المتكرّرة نفسها: الإجابة على الأسئلة ذاتها مراراً، وحجز المواعيد هاتفياً، وملاحقة العملاء المحتملين. الأتمتة المدعومة بالذكاء الاصطناعي تأخذ هذا الجزء المتكرّر وتُشغّله وحده — لتتفرّغ للعمل الذي يحرّك عملك فعلاً.' },
          { h2: 'ما هي أتمتة الأعمال بالذكاء الاصطناعي فعلاً' },
          { p: 'هي مزيج من أدوات ذكية (روبوت محادثة، نظام حجز، تكاملات) تُنفّذ عملية كاملة دون تدخّل يدوي. مثلاً: يرسل عميل رسالة على واتساب ← يردّ الروبوت، ويفهم حاجته، ويحجز له موعداً في تقويمك ويرسل تذكيراً — كلّه تلقائياً. الذكاء الاصطناعي هو ما يتيح للروبوت فهم اللغة الحرّة، لا مجرّد قائمة أزرار.' },
          { h2: 'أيّ العمليات يستحقّ أتمتتها أكثر' },
          { ul: [
            'الردّ الأوّلي على العملاء — أسئلة شائعة، ساعات العمل، الأسعار، التوفّر — 24/7.',
            'التنسيق وحجز المواعيد — العميل يحجز بنفسه في تقويمك، دون مكالمات ذهاب وإياب.',
            'متابعة العملاء المحتملين — تصنيف، ورسالة متابعة تلقائية، وتنبيه حين يحتاج عميل مهتمّ إلى اهتمام.',
            'إنشاء المحتوى — مسوّدات للمنشورات والردود ووصف المنتجات — بسرعة وبنبرة موحّدة.',
          ] },
          { h2: 'لماذا يستحقّ مالاً حقيقياً' },
          { p: 'أمران: الوقت والعملاء. كل ساعة يجيب فيها الروبوت عنك هي ساعة تعود إليك. والأهمّ — سرعة الاستجابة. العميل الذي يحصل على ردّ خلال ثوانٍ يبقى؛ والذي ينتظر ساعة يكون قد توجّه لمنافس. الردّ الفوري، حتى الثالثة فجراً، هو غالباً الفرق بين عميل يُغلق وآخر يُفقد.' },
          { h2: 'من أين تبدأ' },
          { p: 'لا حاجة لأتمتة كل شيء في يوم. ابدأ من أكبر نقطة ألم — غالباً ردود واتساب — وضع هناك روبوتاً ذكياً، وقِس كم من الوقت والعملاء يعيده، ثمّ توسّع نحو الحجز والمتابعة. هكذا ترى عائداً سريعاً دون مشروع ضخم.' },
          { cta: 'تريد أن ترى أيّ عمليات في عملك يمكن أتمتتها؟' },
        ],
        faq: [
          { q: 'هل تستبدل الأتمتة بالذكاء الاصطناعي الموظّفين؟', a: 'لا. إنها تُزيل عن الفريق العمل المتكرّر والمُرهِق (الإجابة على الأسئلة نفسها، الحجز اليدوي) ليتفرّغوا لما يحتاج إنساناً — إغلاق الصفقات، والاهتمام الشخصي، والحالات المعقّدة. الهدف تمكين الفريق لا استبداله.' },
          { q: 'كم يستغرق تطبيق الأتمتة في العمل؟', a: 'عملية مركّزة واحدة — مثل بوت واتساب يجيب على الأسئلة الشائعة ويحجز المواعيد — يمكن إطلاقها خلال أيام إلى أسبوعين، حسب التعقيد والتكاملات. يُفضّل البدء صغيراً والتوسّع.' },
          { q: 'هل أحتاج معرفة تقنية لصيانته؟', a: 'لا. أبني النظام ليعمل وحده وأضبطه حسب عملك. التحديثات البسيطة (الساعات، الأسعار، الإجابات) يمكن إجراؤها عبر واجهة سهلة، دون لمس الكود.' },
        ],
        sources: [
          { name: 'WhatsApp Business Platform (Meta)', url: 'https://developers.facebook.com/docs/whatsapp' },
          { name: 'Google Calendar API', url: 'https://developers.google.com/calendar' },
        ],
      },
    },
  },
  {
    slug: 'bot-whatsapp-esek',
    i18n: {
      he: {
        category: 'אוטומציה ו-AI',
        title: 'בוט וואטסאפ לעסק: לענות ללקוחות אוטומטית 24/7',
        desc: 'איך בוט וואטסאפ חכם עונה ללקוחות שלכם אוטומטית, קובע תורים ומסנן לידים — בערוץ שבו הישראלים באמת מתקשרים.',
        excerpt: 'וואטסאפ הוא הערוץ מספר 1 בישראל. בוט חכם עונה שם במקומכם, מסביב לשעון, ולא מפספס אף לקוח.',
        tldr: 'בוט וואטסאפ לעסק עונה ללקוחות אוטומטית בערוץ שהם כבר משתמשים בו: שאלות נפוצות, מחירים, זמינות, קביעת תור והפניה לנציג כשצריך. הוא נבנה על WhatsApp Business Platform הרשמי, עונה תוך שניות 24/7, ומעביר אליכם רק את הפניות שדורשות בן אדם. התוצאה: אפס לידים שאבדו כי אף אחד לא ענה בזמן.',
        body: [
          { p: 'בישראל אנשים לא ממלאים טפסים — הם שולחים וואטסאפ. זה הופך את וואטסאפ לזירת המכירה החשובה ביותר לעסק מקומי, ובדיוק שם רוב העסקים מפספסים: הודעה שנשלחת ב-21:00 מקבלת מענה למחרת, והלקוח כבר הלך. בוט וואטסאפ פותר בדיוק את זה.' },
          { h2: 'מה בוט וואטסאפ באמת עושה' },
          { p: 'הבוט עונה אוטומטית להודעות נכנסות: הוא מבין שפה חופשית (לא רק תפריט), משיב על שאלות נפוצות, מוסר מחירים וזמינות, קובע תור ביומן, ואם הפנייה מורכבת — מעביר אתכם עם כל ההקשר. הכל בתוך וואטסאפ, בלי שהלקוח יורד לאתר או ממלא טופס.' },
          { h2: 'למה דווקא וואטסאפ' },
          { ul: [
            'זה הערוץ שבו הלקוחות כבר נמצאים — אין חיכוך, אין הורדת אפליקציה.',
            'שיעורי פתיחה של הודעות וואטסאפ גבוהים בהרבה ממייל.',
            'תשובה מיידית = לקוח שנשאר. שעה של השהיה = לקוח שפנה למתחרה.',
            'הכל מתועד בשיחה אחת — קל להמשיך את הקשר.',
          ] },
          { h2: 'רשמי מול "פתרונות עוקפים"' },
          { p: 'חשוב לבנות את הבוט על WhatsApp Business Platform הרשמי של מטא — לא על כלים אפורים שמסתכנים בחסימת המספר שלכם. פתרון רשמי הוא יציב, מאובטח, ומאפשר גם הודעות יזומות (תזכורות, אישורי תור) בהתאם למדיניות. זה ההבדל בין נכס אמין לבין סיכון עסקי.' },
          { h2: 'איך משלבים את זה בעסק' },
          { p: 'מחברים את מספר הוואטסאפ העסקי, מגדירים את התשובות והתהליכים (שאלות נפוצות, יומן, הפניות), ומחברים ליומן ולמערכת הלקוחות. מכאן הבוט עובד לבד, ואתם מקבלים רק את מה שבאמת דורש אתכם.' },
          { cta: 'רוצים בוט וואטסאפ שעונה ללקוחות במקומכם?' },
        ],
        faq: [
          { q: 'האם הבוט יכול לקבוע תורים ביומן שלי?', a: 'כן. אפשר לחבר אותו ליומן (למשל Google Calendar) כך שהלקוח בוחר שעה פנויה בתוך שיחת הוואטסאפ, מקבל אישור, ואתם מקבלים את הפגישה ביומן אוטומטית — כולל תזכורת לפני.' },
          { q: 'מה קורה כשהבוט לא יודע לענות?', a: 'הוא מזהה שזה מקרה שדורש בן אדם ומעביר אליכם את השיחה עם כל ההקשר, או משאיר את פרטי הלקוח לחזרה. הלקוח אף פעם לא נתקע — תמיד יש מסלול לנציג אנושי.' },
          { q: 'האם זה בטוח ולא יחסום לי את המספר?', a: 'כן, כשבונים על WhatsApp Business Platform הרשמי של מטא ופועלים לפי המדיניות. אני בונה על התשתית הרשמית בדיוק כדי שהמספר שלכם יישאר יציב ומאובטח.' },
        ],
        sources: [
          { name: 'WhatsApp Business Platform (Meta)', url: 'https://developers.facebook.com/docs/whatsapp' },
          { name: 'WhatsApp Business — Meta', url: 'https://business.whatsapp.com/' },
        ],
      },
      en: {
        category: 'AI & Automation',
        title: 'A WhatsApp Bot for Your Business: Answer Customers Automatically 24/7',
        desc: 'How a smart WhatsApp bot answers your customers automatically, books appointments and filters leads — on the channel people actually use.',
        excerpt: 'WhatsApp is the #1 channel in Israel. A smart bot answers there for you, around the clock, and never misses a customer.',
        tldr: 'A WhatsApp bot answers customers automatically on the channel they already use: FAQs, prices, availability, booking, and hand-off to a human when needed. Built on the official WhatsApp Business Platform, it replies within seconds 24/7 and passes you only the conversations that need a person. The result: zero leads lost because no one replied in time.',
        body: [
          { p: 'People do not fill out forms — they send a WhatsApp message. That makes WhatsApp the most important sales arena for a local business, and it is exactly where most businesses drop the ball: a message sent at 9pm gets a reply the next day, and the customer is already gone. A WhatsApp bot solves precisely that.' },
          { h2: 'What a WhatsApp bot actually does' },
          { p: 'The bot answers incoming messages automatically: it understands free language (not just a menu), replies to FAQs, gives prices and availability, books a slot in your calendar, and if the request is complex — hands it to you with full context. All inside WhatsApp, without the customer having to visit a site or fill a form.' },
          { h2: 'Why WhatsApp specifically' },
          { ul: [
            'It is the channel customers are already on — no friction, no app to install.',
            'WhatsApp message open rates are far higher than email.',
            'An instant reply = a customer who stays. An hour’s delay = a customer who went to a competitor.',
            'Everything is logged in one conversation — easy to continue the relationship.',
          ] },
          { h2: 'Official vs. "workaround" tools' },
          { p: 'It is important to build the bot on Meta’s official WhatsApp Business Platform — not on grey-area tools that risk getting your number banned. An official solution is stable, secure, and also allows proactive messages (reminders, booking confirmations) within policy. That is the difference between a reliable asset and a business risk.' },
          { h2: 'How it fits into your business' },
          { p: 'You connect your business WhatsApp number, define the answers and flows (FAQs, calendar, hand-offs), and connect it to your calendar and CRM. From there the bot runs on its own, and you receive only what genuinely needs you.' },
          { cta: 'Want a WhatsApp bot that answers customers for you?' },
        ],
        faq: [
          { q: 'Can the bot book appointments in my calendar?', a: 'Yes. It can connect to your calendar (e.g. Google Calendar) so the customer picks an open slot inside the WhatsApp chat, gets a confirmation, and the meeting lands in your calendar automatically — including a reminder beforehand.' },
          { q: 'What happens when the bot cannot answer?', a: 'It recognises a case that needs a human and hands you the conversation with full context, or captures the customer’s details for a callback. The customer is never stuck — there is always a path to a person.' },
          { q: 'Is it safe — will it get my number banned?', a: 'Yes, when built on Meta’s official WhatsApp Business Platform and operated within policy. I build on the official infrastructure precisely so your number stays stable and secure.' },
        ],
        sources: [
          { name: 'WhatsApp Business Platform (Meta)', url: 'https://developers.facebook.com/docs/whatsapp' },
          { name: 'WhatsApp Business — Meta', url: 'https://business.whatsapp.com/' },
        ],
      },
      ar: {
        category: 'الأتمتة والذكاء الاصطناعي',
        title: 'بوت واتساب لعملك: أجب العملاء تلقائياً على مدار الساعة',
        desc: 'كيف يجيب بوت واتساب ذكي عملاءك تلقائياً، ويحجز المواعيد ويفرز العملاء المحتملين — على القناة التي يستخدمها الناس فعلاً.',
        excerpt: 'واتساب هو القناة رقم 1. بوت ذكي يجيب هناك عنك، على مدار الساعة، ولا يفوّت أيّ عميل.',
        tldr: 'بوت واتساب يجيب العملاء تلقائياً على القناة التي يستخدمونها أصلاً: أسئلة شائعة، أسعار، توفّر، حجز، وتحويل إلى إنسان عند الحاجة. مبنيّ على منصّة واتساب للأعمال الرسمية، يردّ خلال ثوانٍ 24/7 ويمرّر إليك فقط المحادثات التي تحتاج إنساناً. النتيجة: صفر عملاء ضائعين لأن أحداً لم يردّ في الوقت.',
        body: [
          { p: 'الناس لا يملؤون النماذج — يرسلون رسالة واتساب. هذا يجعل واتساب أهمّ ساحة بيع للعمل المحلّي، وهو بالضبط حيث يُخفق معظم الأعمال: رسالة تُرسل في التاسعة مساءً تُجاب في اليوم التالي، ويكون العميل قد غادر. بوت واتساب يحلّ هذا تحديداً.' },
          { h2: 'ماذا يفعل بوت واتساب فعلاً' },
          { p: 'يجيب البوت على الرسائل الواردة تلقائياً: يفهم اللغة الحرّة (لا مجرّد قائمة)، ويردّ على الأسئلة الشائعة، ويعطي الأسعار والتوفّر، ويحجز موعداً في تقويمك، وإن كان الطلب معقّداً — يحوّله إليك مع كامل السياق. كلّه داخل واتساب، دون أن ينتقل العميل إلى موقع أو يملأ نموذجاً.' },
          { h2: 'لماذا واتساب تحديداً' },
          { ul: [
            'إنها القناة التي يوجد فيها العملاء أصلاً — بلا احتكاك ولا تطبيق للتثبيت.',
            'معدّلات فتح رسائل واتساب أعلى بكثير من البريد الإلكتروني.',
            'ردّ فوري = عميل يبقى. تأخّر ساعة = عميل توجّه لمنافس.',
            'كل شيء موثّق في محادثة واحدة — يسهل متابعة العلاقة.',
          ] },
          { h2: 'الرسمي مقابل "الحلول الالتفافية"' },
          { p: 'من المهمّ بناء البوت على منصّة واتساب للأعمال الرسمية من ميتا — لا على أدوات رمادية تخاطر بحظر رقمك. الحلّ الرسمي مستقرّ وآمن، ويتيح أيضاً رسائل استباقية (تذكيرات، تأكيدات حجز) ضمن السياسة. هذا الفرق بين أصل موثوق ومخاطرة تجارية.' },
          { h2: 'كيف يندمج في عملك' },
          { p: 'تربط رقم واتساب الخاص بعملك، وتحدّد الإجابات والمسارات (أسئلة شائعة، تقويم، تحويلات)، وتربطه بتقويمك ونظام عملائك. من هنا يعمل البوت وحده، وتستلم فقط ما يحتاجك حقّاً.' },
          { cta: 'تريد بوت واتساب يجيب العملاء عنك؟' },
        ],
        faq: [
          { q: 'هل يستطيع البوت حجز المواعيد في تقويمي؟', a: 'نعم. يمكن ربطه بتقويمك (مثل Google Calendar) ليختار العميل موعداً متاحاً داخل محادثة واتساب، ويحصل على تأكيد، ويظهر الموعد في تقويمك تلقائياً — مع تذكير مسبق.' },
          { q: 'ماذا يحدث حين لا يعرف البوت الإجابة؟', a: 'يميّز الحالة التي تحتاج إنساناً ويحوّل إليك المحادثة مع كامل السياق، أو يحفظ بيانات العميل للمعاودة. العميل لا يعلق أبداً — هناك دائماً مسار إلى شخص حقيقي.' },
          { q: 'هل هو آمن ولن يحظر رقمي؟', a: 'نعم، عند البناء على منصّة واتساب للأعمال الرسمية من ميتا والعمل ضمن السياسة. أبني على البنية الرسمية تحديداً ليبقى رقمك مستقرّاً وآمناً.' },
        ],
        sources: [
          { name: 'WhatsApp Business Platform (Meta)', url: 'https://developers.facebook.com/docs/whatsapp' },
          { name: 'WhatsApp Business — Meta', url: 'https://business.whatsapp.com/' },
        ],
      },
    },
  },
  {
    slug: 'zimun-torim-otomati',
    i18n: {
      he: {
        category: 'אוטומציה ו-AI',
        title: 'זימון תורים אוטומטי: איך למלא את היומן בלי טלפונים',
        desc: 'איך מערכת זימון תורים אוטומטית נותנת ללקוחות לקבוע לבד, מפחיתה ביטולים עם תזכורות, וחוסכת לכם את משחק הטלפונים.',
        excerpt: 'הפסיקו לתאם תורים בהודעות הלוך-ושוב. תנו ללקוח לבחור שעה פנויה לבד — והיומן מתמלא בזמן שאתם עובדים.',
        tldr: 'מערכת זימון תורים אוטומטית מציגה ללקוח את הזמנים הפנויים שלכם, נותנת לו לבחור ולאשר לבד, מוסיפה את הפגישה ליומן ושולחת תזכורות אוטומטיות. התוצאה: פחות טלפונים, פחות ביטולים ("no-show"), ויומן שמתמלא 24/7 — גם כשאתם עסוקים או ישנים.',
        body: [
          { p: 'תיאום תורים ידני הוא בור זמן: הודעה, "מתי פנוי?", תשובה, "לא מתאים לי", וחוזר חלילה. בזמן הזה לקוחות מתייאשים והולכים. מערכת זימון אוטומטית מוחקת את כל הריקושטים — הלקוח רואה מה פנוי ובוחר לבד.' },
          { h2: 'איך זה עובד' },
          { p: 'הלקוח מקבל קישור (או קובע ישירות בתוך וואטסאפ/האתר), רואה רק את השעות שבאמת פנויות ביומן שלכם, בוחר, ומקבל אישור מיידי. הפגישה נכנסת ליומן שלכם אוטומטית, ולפני המועד יוצאת תזכורת — לו ולכם.' },
          { h2: 'למה זה חוסך כסף' },
          { ul: [
            'פחות זמן על תיאומים — היומן מתמלא בלי שתיגעו בטלפון.',
            'פחות ביטולים ואי-הגעות — תזכורות אוטומטיות מזכירות ללקוח, ומאפשרות לו לבטל מראש כדי לפנות את המקום.',
            'זמינות 24/7 — לקוח יכול לקבוע תור בחצות, כשהמתחרה שלכם לא זמין.',
            'אפס טעויות כפל-הזמנה — המערכת חוסמת שעה שכבר נתפסה.',
          ] },
          { h2: 'למי זה מתאים במיוחד' },
          { p: 'לכל עסק מבוסס-תורים: מספרות וקוסמטיקה, קליניקות ומטפלים, יועצים, מוסכים, שירותי בית. בכל מקום שבו "השעה שלכם היא המוצר" — כל תור שאבד בגלל תיאום מסורבל הוא הכנסה שאבדה.' },
          { h2: 'לחבר להכול' },
          { p: 'הכי חזק כשמחברים את זה לשאר האוטומציה: בוט הוואטסאפ קובע את התור, המערכת שולחת תזכורת, ואחרי הפגישה יוצאת בקשת ביקורת. ככה תור אחד הופך לתהליך שלם שרץ לבד.' },
          { cta: 'רוצים יומן שמתמלא לבד? בואו נחבר לכם זימון אוטומטי' },
        ],
        faq: [
          { q: 'האם המערכת מתחברת ליומן הקיים שלי?', a: 'כן. היא מסתנכרנת עם היומן שלכם (למשל Google Calendar) ומציגה ללקוח רק שעות שבאמת פנויות, כך שאין כפל-הזמנות. כל תור חדש נכנס אוטומטית ליומן.' },
          { q: 'האם זה מפחית אי-הגעות (no-show)?', a: 'כן. תזכורות אוטומטיות לפני המועד מפחיתות משמעותית אי-הגעות, ומאפשרות ללקוח לבטל מבעוד מועד — כך שהשעה מתפנה למישהו אחר במקום להתבזבז.' },
          { q: 'האם הלקוח צריך להוריד אפליקציה?', a: 'לא. הלקוח קובע דרך קישור בדפדפן או ישירות בתוך שיחת וואטסאפ — בלי הרשמה ובלי אפליקציה. כמה שפחות חיכוך, יותר תורים נסגרים.' },
        ],
        sources: [
          { name: 'Google Calendar API', url: 'https://developers.google.com/calendar' },
          { name: 'WhatsApp Business Platform (Meta)', url: 'https://developers.facebook.com/docs/whatsapp' },
        ],
      },
      en: {
        category: 'AI & Automation',
        title: 'Automated Appointment Booking: Fill Your Calendar Without Phone Calls',
        desc: 'How an automated booking system lets customers schedule themselves, cuts no-shows with reminders, and saves you the phone tag.',
        excerpt: 'Stop booking appointments in back-and-forth messages. Let the customer pick an open slot themselves — and your calendar fills while you work.',
        tldr: 'An automated booking system shows customers your open times, lets them pick and confirm themselves, adds the meeting to your calendar and sends automatic reminders. The result: fewer calls, fewer no-shows, and a calendar that fills 24/7 — even while you are busy or asleep.',
        body: [
          { p: 'Manual booking is a time pit: a message, "when are you free?", a reply, "that does not work for me", and round it goes. Meanwhile customers give up and leave. An automated booking system erases all that ping-pong — the customer sees what is open and picks for themselves.' },
          { h2: 'How it works' },
          { p: 'The customer gets a link (or books right inside WhatsApp/your site), sees only the times genuinely open in your calendar, picks one, and gets an instant confirmation. The meeting drops into your calendar automatically, and before it a reminder goes out — to them and to you.' },
          { h2: 'Why it saves money' },
          { ul: [
            'Less time on scheduling — the calendar fills without you touching the phone.',
            'Fewer cancellations and no-shows — automatic reminders nudge the customer and let them cancel ahead to free the slot.',
            '24/7 availability — a customer can book at midnight, when your competitor is unavailable.',
            'Zero double-booking errors — the system blocks a slot that is already taken.',
          ] },
          { h2: 'Who it fits especially' },
          { p: 'Any appointment-based business: salons and beauty, clinics and therapists, consultants, garages, home services. Anywhere "your time is the product" — every appointment lost to clunky scheduling is lost revenue.' },
          { h2: 'Connect it to everything' },
          { p: 'It is strongest when connected to the rest of your automation: the WhatsApp bot books the slot, the system sends the reminder, and after the meeting a review request goes out. That way one appointment becomes a whole process that runs on its own.' },
          { cta: 'Want a calendar that fills itself? Let us set up automated booking' },
        ],
        faq: [
          { q: 'Does it connect to my existing calendar?', a: 'Yes. It syncs with your calendar (e.g. Google Calendar) and shows the customer only genuinely open times, so there is no double-booking. Every new appointment lands in your calendar automatically.' },
          { q: 'Does it reduce no-shows?', a: 'Yes. Automatic reminders before the appointment cut no-shows significantly, and let the customer cancel ahead — so the slot frees up for someone else instead of being wasted.' },
          { q: 'Does the customer need to install an app?', a: 'No. The customer books via a browser link or right inside a WhatsApp chat — no sign-up, no app. The less friction, the more appointments close.' },
        ],
        sources: [
          { name: 'Google Calendar API', url: 'https://developers.google.com/calendar' },
          { name: 'WhatsApp Business Platform (Meta)', url: 'https://developers.facebook.com/docs/whatsapp' },
        ],
      },
      ar: {
        category: 'الأتمتة والذكاء الاصطناعي',
        title: 'حجز المواعيد التلقائي: كيف تملأ جدولك دون مكالمات',
        desc: 'كيف يتيح نظام حجز المواعيد التلقائي للعملاء الحجز بأنفسهم، ويقلّل الإلغاءات بالتذكيرات، ويوفّر عليك تبادل المكالمات.',
        excerpt: 'توقّف عن تنسيق المواعيد برسائل ذهاب وإياب. دع العميل يختار موعداً متاحاً بنفسه — ويمتلئ جدولك وأنت تعمل.',
        tldr: 'نظام حجز المواعيد التلقائي يعرض للعميل أوقاتك المتاحة، ويتيح له الاختيار والتأكيد بنفسه، ويضيف الموعد إلى تقويمك ويرسل تذكيرات تلقائية. النتيجة: مكالمات أقل، وحالات تخلّف أقل، وجدول يمتلئ 24/7 — حتى وأنت مشغول أو نائم.',
        body: [
          { p: 'التنسيق اليدوي للمواعيد حفرة وقت: رسالة، "متى أنت متاح؟"، ردّ، "لا يناسبني"، وتعود الكرّة. في هذه الأثناء ييأس العملاء ويغادرون. نظام الحجز التلقائي يمحو كل هذا التراشق — يرى العميل المتاح ويختار بنفسه.' },
          { h2: 'كيف يعمل' },
          { p: 'يحصل العميل على رابط (أو يحجز مباشرة داخل واتساب/موقعك)، ويرى فقط الأوقات المتاحة فعلاً في تقويمك، ويختار، ويحصل على تأكيد فوري. يدخل الموعد تقويمك تلقائياً، وقبله يخرج تذكير — له ولك.' },
          { h2: 'لماذا يوفّر المال' },
          { ul: [
            'وقت أقل على التنسيق — يمتلئ الجدول دون أن تلمس الهاتف.',
            'إلغاءات وتخلّف أقل — التذكيرات التلقائية تنبّه العميل وتتيح له الإلغاء مسبقاً لتحرير الموعد.',
            'توفّر 24/7 — يستطيع العميل الحجز منتصف الليل، حين لا يكون منافسك متاحاً.',
            'صفر أخطاء حجز مزدوج — يحظر النظام موعداً محجوزاً بالفعل.',
          ] },
          { h2: 'لمن يناسب خصوصاً' },
          { p: 'أيّ عمل قائم على المواعيد: صالونات وتجميل، عيادات ومعالجون، مستشارون، ورش، خدمات منزلية. حيثما يكون "وقتك هو المنتج" — كل موعد يُفقد بسبب تنسيق مرهِق هو دخل ضائع.' },
          { h2: 'اربطه بكل شيء' },
          { p: 'يكون أقوى عند ربطه ببقيّة الأتمتة: بوت واتساب يحجز الموعد، والنظام يرسل التذكير، وبعد اللقاء يخرج طلب تقييم. هكذا يتحوّل موعد واحد إلى عملية كاملة تعمل وحدها.' },
          { cta: 'تريد جدولاً يمتلئ وحده؟ لنُعدّ لك حجزاً تلقائياً' },
        ],
        faq: [
          { q: 'هل يتصل بتقويمي الحالي؟', a: 'نعم. يتزامن مع تقويمك (مثل Google Calendar) ويعرض للعميل فقط الأوقات المتاحة فعلاً، فلا حجز مزدوج. كل موعد جديد يدخل تقويمك تلقائياً.' },
          { q: 'هل يقلّل حالات التخلّف عن الحضور؟', a: 'نعم. التذكيرات التلقائية قبل الموعد تقلّل التخلّف بشكل كبير، وتتيح للعميل الإلغاء مسبقاً — فيتحرّر الموعد لشخص آخر بدل أن يُهدر.' },
          { q: 'هل يحتاج العميل لتثبيت تطبيق؟', a: 'لا. يحجز العميل عبر رابط في المتصفّح أو مباشرة داخل محادثة واتساب — بلا تسجيل وبلا تطبيق. كلّما قلّ الاحتكاك، أُغلقت مواعيد أكثر.' },
        ],
        sources: [
          { name: 'Google Calendar API', url: 'https://developers.google.com/calendar' },
          { name: 'WhatsApp Business Platform (Meta)', url: 'https://developers.facebook.com/docs/whatsapp' },
        ],
      },
    },
  },

  // === Migrated articles — now fully trilingual (he / en / ar) ===============
  {
    slug: 'kama-ole-atar-tadmit',
    i18n: {
      he: {
        category: 'מחירים',
        title: 'כמה עולה אתר תדמית ב-2026? מדריך מחירים מלא לעסקים',
        desc: 'כמה באמת עולה אתר תדמית לעסק? פירוק מלא של טווחי המחירים, מה משפיע על העלות, ואיפה כדאי (ולא כדאי) לחסוך.',
        excerpt: 'מדריך מחירים שקוף: כמה עולה אתר תדמית, מה מייקר ומה מוזיל, ואיך לבחור נכון בלי לזרוק כסף.',
        tldr: 'מחיר אתר תדמית נגזר בעיקר ממורכבות: דף נחיתה בודד הוא הזול, אתר 3–6 עמודים הוא הבחירה הנפוצה לעסק קטן, ואתר רב-לשוני או חנות מייקרים. מה שמשפיע: עיצוב מותאם מול תבנית, כמות התוכן והשפות, פיצ׳רים ותחזוקה. הזול-מדי כמעט תמיד יקר בטווח הארוך.',
        body: [
          { p: 'אחת השאלות הראשונות שכל בעל עסק שואל היא פשוט: "כמה זה יעלה לי?". התשובה הכנה היא שזה תלוי — אבל זה לא אומר שאי אפשר לתת טווחים ברורים. במדריך הזה אני מפרק את מחירי בניית אתרים ב-2026, כדי שתדעו בדיוק על מה אתם משלמים.' },
          { h2: 'טווחי מחירים לפי סוג אתר' },
          { p: 'המחיר נגזר בעיקר מהמורכבות. הנה החלוקה שאני עובד לפיה:' },
          { ul: [
            'אתר דף נחיתה (Landing Page): עמוד אחד ממוקד המרה — הזול והמהיר ביותר, מתאים לקמפיין או שירות בודד.',
            'אתר תדמית קלאסי (3–6 עמודים): בית, אודות, שירותים, גלריה, צור קשר — הבחירה הנפוצה לעסק קטן.',
            'אתר תדמית מורחב + בלוג / רב-לשוני: כשצריך תוכן שוטף, כמה שפות או אזור אישי — התוכן והמערכת מייקרים.',
            'חנות אונליין / מערכת: קטלוג, סליקה, ניהול הזמנות — הפרויקט המורכב ביותר וגם היקר.',
          ] },
          { h2: 'מה באמת משפיע על המחיר?' },
          { p: 'שני אתרים עם אותו מספר עמודים יכולים לעלות אחרת לגמרי. הגורמים העיקריים:' },
          { ul: [
            'עיצוב מותאם אישית מול תבנית מוכנה — עיצוב ייחודי דורש יותר עבודה אבל מבדל אתכם.',
            'כמות התוכן והשפות — אתר דו-לשוני (עברית + ערבית) מכפיל חלק מהעבודה.',
            'פיצ׳רים: טופס חכם, זימון תורים, אזור לקוחות, אינטגרציות (וואטסאפ, יומן, תשלומים).',
            'תמיכה ותחזוקה אחרי ההשקה — האם זו עסקה חד-פעמית או ליווי מתמשך.',
          ] },
          { h2: 'זול מדי? שימו לב לעלויות הנסתרות' },
          { p: 'אתר "ב-500 שקל" נשמע מפתה, אבל לרוב מסתתרות שם עלויות: תבנית גנרית שנראית כמו של כולם, אתר איטי שפוגע בדירוג בגוגל, אפס SEO, ואפס תמיכה כשמשהו נשבר. אתר הוא נכס עסקי — לא הוצאה חד-פעמית. אתר איטי ולא מותאם לנייד עולה לכם בלקוחות שעוזבים לפני שהעמוד בכלל נטען.' },
          { h2: 'איפה כן כדאי לחסוך' },
          { p: 'לא חייבים הכול ביום הראשון. אפשר להתחיל באתר תדמית ממוקד ומהיר, ולהוסיף בהמשך בלוג, חנות או אזור לקוחות כשהעסק גדל. ככה משלמים לפי הצורך האמיתי במקום על פיצ׳רים שלא בשימוש.' },
          { cta: 'קבלו הצעת מחיר שקופה לעסק שלכם' },
        ],
      },
      en: {
        category: 'Pricing',
        title: 'How Much Does a Business Website Cost in 2026? A Full Pricing Guide',
        desc: 'What a business website really costs: a full breakdown of the price ranges, what drives the cost up, and where it is (and is not) smart to save.',
        excerpt: 'A transparent pricing guide: what a business website costs, what makes it more (or less) expensive, and how to choose without wasting money.',
        tldr: 'A website’s price is driven mostly by complexity: a single landing page is the cheapest, a 3–6 page site is the common choice for a small business, and a multilingual site or store costs more. What moves the price: custom design vs. a template, the amount of content and languages, features, and maintenance. Too-cheap is almost always expensive in the long run.',
        body: [
          { p: 'One of the first questions every business owner asks is simply: "how much will this cost me?". The honest answer is that it depends — but that does not mean clear ranges are impossible. In this guide I break down website pricing in 2026 so you know exactly what you are paying for.' },
          { h2: 'Price ranges by type of site' },
          { p: 'Price is driven mostly by complexity. Here is the breakdown I work with:' },
          { ul: [
            'Landing page: a single conversion-focused page — the cheapest and fastest, ideal for a campaign or a single service.',
            'Classic business site (3–6 pages): home, about, services, gallery, contact — the common choice for a small business.',
            'Extended site + blog / multilingual: when you need ongoing content, several languages or a client area — the content and system add cost.',
            'Online store / system: catalogue, payments, order management — the most complex project and the most expensive.',
          ] },
          { h2: 'What really drives the price?' },
          { p: 'Two sites with the same number of pages can cost completely differently. The main factors:' },
          { ul: [
            'Custom design vs. a ready-made template — a unique design takes more work but sets you apart.',
            'Amount of content and languages — a bilingual site (e.g. Hebrew + Arabic) doubles part of the work.',
            'Features: a smart form, appointment booking, a client area, integrations (WhatsApp, calendar, payments).',
            'Support and maintenance after launch — whether it is a one-off or an ongoing partnership.',
          ] },
          { h2: 'Too cheap? Watch the hidden costs' },
          { p: 'A "$150 website" sounds tempting, but the costs are usually hiding: a generic template that looks like everyone else’s, a slow site that hurts your Google ranking, zero SEO, and zero support when something breaks. A website is a business asset — not a one-off expense. A slow, non-mobile-friendly site costs you customers who leave before the page even loads.' },
          { h2: 'Where it is smart to save' },
          { p: 'You do not need everything on day one. You can start with a focused, fast business site and add a blog, store or client area later as the business grows. That way you pay for real needs instead of features that go unused.' },
          { cta: 'Get a transparent quote for your business' },
        ],
      },
      ar: {
        category: 'الأسعار',
        title: 'كم يكلّف موقع تعريفي في 2026؟ دليل الأسعار الكامل للأعمال',
        desc: 'كم يكلّف موقع تعريفي للعمل حقّاً؟ تفصيل كامل لنطاقات الأسعار، وما يرفع التكلفة، وأين يُفضّل (ولا يُفضّل) التوفير.',
        excerpt: 'دليل أسعار شفّاف: كم يكلّف الموقع التعريفي، ما يرفع التكلفة وما يخفّضها، وكيف تختار بذكاء دون إهدار المال.',
        tldr: 'سعر الموقع يتحدّد أساساً بالتعقيد: صفحة هبوط واحدة هي الأرخص، وموقع من 3–6 صفحات هو الخيار الشائع للعمل الصغير، والموقع متعدّد اللغات أو المتجر أغلى. ما يؤثّر: التصميم المخصّص مقابل القالب، وكمّية المحتوى واللغات، والميزات، والصيانة. الرخيص أكثر من اللازم مكلف غالباً على المدى البعيد.',
        body: [
          { p: 'من أوّل الأسئلة التي يطرحها كل صاحب عمل: "كم سيكلّفني هذا؟". الجواب الصريح أنّ الأمر يعتمد — لكن هذا لا يمنع إعطاء نطاقات واضحة. في هذا الدليل أُفصّل أسعار بناء المواقع في 2026 لتعرف بالضبط على ماذا تدفع.' },
          { h2: 'نطاقات الأسعار حسب نوع الموقع' },
          { p: 'السعر يتحدّد أساساً بالتعقيد. إليك التقسيم الذي أعمل وفقه:' },
          { ul: [
            'صفحة هبوط (Landing Page): صفحة واحدة مركّزة على التحويل — الأرخص والأسرع، مناسبة لحملة أو خدمة واحدة.',
            'موقع تعريفي كلاسيكي (3–6 صفحات): رئيسية، من نحن، خدمات، معرض صور، تواصل — الخيار الشائع للعمل الصغير.',
            'موقع موسّع + مدوّنة / متعدّد اللغات: عند الحاجة لمحتوى مستمر أو عدّة لغات أو منطقة شخصية — المحتوى والنظام يرفعان التكلفة.',
            'متجر إلكتروني / نظام: كتالوج، دفع، إدارة طلبات — المشروع الأكثر تعقيداً والأغلى.',
          ] },
          { h2: 'ما الذي يؤثّر حقّاً على السعر؟' },
          { p: 'موقعان بنفس عدد الصفحات قد يختلفان تماماً في التكلفة. العوامل الرئيسية:' },
          { ul: [
            'تصميم مخصّص مقابل قالب جاهز — التصميم الفريد يتطلّب جهداً أكثر لكنه يميّزك.',
            'كمّية المحتوى واللغات — موقع ثنائي اللغة (عبري + عربي) يضاعف جزءاً من العمل.',
            'الميزات: نموذج ذكي، حجز مواعيد، منطقة عملاء، تكاملات (واتساب، تقويم، مدفوعات).',
            'الدعم والصيانة بعد الإطلاق — هل هي صفقة لمرّة واحدة أم مرافقة مستمرة.',
          ] },
          { h2: 'رخيص أكثر من اللازم؟ انتبه للتكاليف الخفية' },
          { p: 'موقع "بـ150 شيكل" يبدو مغرياً، لكن التكاليف غالباً مخبّأة: قالب عام يشبه الجميع، موقع بطيء يضرّ بترتيبك في جوجل، ولا SEO، ولا دعم عندما يتعطّل شيء. الموقع أصل تجاري — وليس مصروفاً لمرّة واحدة. الموقع البطيء غير المتوافق مع الجوّال يكلّفك عملاء يغادرون قبل أن تُحمّل الصفحة أصلاً.' },
          { h2: 'أين يُفضّل التوفير' },
          { p: 'لست مضطرّاً لكل شيء من اليوم الأوّل. يمكنك البدء بموقع تعريفي مركّز وسريع، ثمّ إضافة مدوّنة أو متجر أو منطقة عملاء لاحقاً مع نمو العمل. هكذا تدفع مقابل الحاجات الحقيقية بدلاً من ميزات لا تُستخدم.' },
          { cta: 'احصل على عرض سعر شفّاف لعملك' },
        ],
      },
    },
  },
  {
    slug: 'atar-tadmit-mul-hanut-online',
    i18n: {
      he: {
        category: 'עסקים',
        title: 'אתר תדמית או חנות אונליין? המדריך לבחירה הנכונה לעסק',
        desc: 'לא בטוחים אם אתם צריכים אתר תדמית או חנות אונליין? השוואה מעשית שתעזור לכם להחליט לפי סוג העסק והמטרות.',
        excerpt: 'תדמית מול חנות: מה ההבדל האמיתי, כמה זה עולה, ואיזה מהם מתאים לעסק שלכם דווקא עכשיו.',
        tldr: 'אתר תדמית מציג את העסק ומניע לפנייה (לידים) — מושלם לנותני שירות. חנות אונליין מאפשרת ללקוח לקנות לבד 24/7 — השקעה גדולה יותר שפותחת ערוץ מכירה. הכלל: מוכרים מוצר לתשלום אונליין → חנות; המטרה פניות → תדמית. אפשר גם להתחיל בתדמית ולהוסיף חנות קטנה בהמשך.',
        body: [
          { p: 'הרבה בעלי עסקים מתלבטים: "אני צריך סתם אתר, או חנות שאפשר לקנות בה?". הבחירה הזו משפיעה על התקציב, על הזמן ועל האופן שבו הלקוחות יתקשרו אתכם. בואו נעשה סדר.' },
          { h2: 'מה זה אתר תדמית' },
          { p: 'אתר תדמית מציג את העסק: מי אתם, מה אתם מציעים, למה לבחור בכם, ואיך יוצרים קשר. המטרה שלו היא לבנות אמון ולהניע לפנייה — טלפון, וואטסאפ או טופס. הוא מושלם לנותני שירות: יועצים, מטפלים, בעלי מקצוע, מסעדות ועסקים מקומיים.' },
          { h2: 'מה זה חנות אונליין' },
          { p: 'חנות אונליין (E-commerce) מאפשרת ללקוח לבחור מוצר, לשלם ולסיים עסקה — הכול לבד, 24/7. היא כוללת קטלוג, עגלת קניות, סליקה וניהול הזמנות ומלאי. זו השקעה גדולה יותר, אבל היא פותחת ערוץ מכירה שעובד גם כשאתם ישנים.' },
          { h2: 'איך לבחור — 3 שאלות' },
          { ul: [
            'האם אתם מוכרים מוצר פיזי/דיגיטלי שאפשר לשלם עליו אונליין? אם כן — חנות.',
            'האם המטרה העיקרית היא לידים ופניות (ולא מכירה ישירה)? אם כן — תדמית.',
            'מה התקציב והלוח זמנים? תדמית מהיר וזול יותר; חנות דורשת יותר תכנון ותקציב.',
          ] },
          { h2: 'הפתרון האמצעי' },
          { p: 'לא חייבים לבחור קיצוני. אפשר לבנות אתר תדמית מעולה, ולהוסיף לו "חנות קטנה" של כמה מוצרים או כפתור הזמנה/תשלום, בלי להקים מערכת מסחר מלאה. ככה מתחילים חכם ומרחיבים כשיש ביקוש אמיתי.' },
          { p: 'בכל מקרה — שני הסוגים חייבים להיות מהירים, מותאמים לנייד ובנויים ל-SEO, אחרת הלקוחות פשוט לא ימצאו אתכם בגוגל.' },
          { cta: 'לא בטוחים מה מתאים? בואו נתייעץ' },
        ],
      },
      en: {
        category: 'Business',
        title: 'Brochure Site or Online Store? The Guide to Choosing Right',
        desc: 'Not sure whether you need a brochure site or an online store? A practical comparison to help you decide by your type of business and goals.',
        excerpt: 'Brochure vs. store: the real difference, what it costs, and which one fits your business right now.',
        tldr: 'A brochure site presents the business and drives inquiries (leads) — perfect for service providers. An online store lets customers buy on their own 24/7 — a bigger investment that opens a sales channel. The rule: selling a product for online payment → store; goal is inquiries → brochure. You can also start with a brochure and add a small store later.',
        body: [
          { p: 'Many business owners hesitate: "do I just need a website, or a store people can buy from?". This choice affects your budget, your timeline, and how customers reach you. Let us sort it out.' },
          { h2: 'What a brochure site is' },
          { p: 'A brochure site presents the business: who you are, what you offer, why choose you, and how to get in touch. Its goal is to build trust and drive an inquiry — a call, WhatsApp, or a form. It is perfect for service providers: consultants, therapists, tradespeople, restaurants and local businesses.' },
          { h2: 'What an online store is' },
          { p: 'An online store (e-commerce) lets a customer pick a product, pay and complete the purchase — all on their own, 24/7. It includes a catalogue, cart, payments, and order and inventory management. It is a bigger investment, but it opens a sales channel that works even while you sleep.' },
          { h2: 'How to choose — 3 questions' },
          { ul: [
            'Do you sell a physical/digital product that can be paid for online? If yes — a store.',
            'Is the main goal leads and inquiries (not a direct sale)? If yes — a brochure site.',
            'What is the budget and timeline? A brochure site is faster and cheaper; a store needs more planning and budget.',
          ] },
          { h2: 'The middle path' },
          { p: 'You do not have to pick an extreme. You can build an excellent brochure site and add a "small shop" of a few products or an order/pay button, without setting up a full commerce system. That way you start smart and expand when there is real demand.' },
          { p: 'Either way — both types must be fast, mobile-friendly and built for SEO, or customers simply will not find you on Google.' },
          { cta: 'Not sure which fits? Let us talk it through' },
        ],
      },
      ar: {
        category: 'أعمال',
        title: 'موقع تعريفي أم متجر إلكتروني؟ دليل الاختيار الصحيح',
        desc: 'لست متأكّداً إن كنت تحتاج موقعاً تعريفياً أم متجراً إلكترونياً؟ مقارنة عملية تساعدك على القرار حسب نوع عملك وأهدافك.',
        excerpt: 'تعريفي مقابل متجر: الفرق الحقيقي، وكم يكلّف، وأيّهما يناسب عملك الآن تحديداً.',
        tldr: 'الموقع التعريفي يعرض العمل ويحفّز على التواصل (leads) — مثالي لمقدّمي الخدمات. المتجر الإلكتروني يتيح للعميل الشراء بنفسه 24/7 — استثمار أكبر يفتح قناة بيع. القاعدة: تبيع منتجاً بدفع إلكتروني → متجر؛ الهدف استفسارات → تعريفي. ويمكن البدء بتعريفي وإضافة متجر صغير لاحقاً.',
        body: [
          { p: 'يتردّد كثير من أصحاب الأعمال: "هل أحتاج مجرّد موقع، أم متجراً يمكن الشراء منه؟". هذا الاختيار يؤثّر على الميزانية والوقت وطريقة تواصل العملاء معك. لنُرتّب الأمور.' },
          { h2: 'ما هو الموقع التعريفي' },
          { p: 'الموقع التعريفي يعرض العمل: من أنتم، ماذا تقدّمون، لماذا يختاركم العميل، وكيف يتواصل. هدفه بناء الثقة والحثّ على التواصل — هاتف أو واتساب أو نموذج. وهو مثالي لمقدّمي الخدمات: مستشارون، معالجون، أصحاب مهن، مطاعم وأعمال محلّية.' },
          { h2: 'ما هو المتجر الإلكتروني' },
          { p: 'المتجر الإلكتروني (E-commerce) يتيح للعميل اختيار منتج والدفع وإتمام الصفقة — كلّه بنفسه، على مدار الساعة. يشمل كتالوجاً وسلّة شراء ودفعاً وإدارة طلبات ومخزون. إنه استثمار أكبر، لكنه يفتح قناة بيع تعمل حتى وأنت نائم.' },
          { h2: 'كيف تختار — 3 أسئلة' },
          { ul: [
            'هل تبيع منتجاً ماديّاً/رقميّاً يمكن الدفع مقابله إلكترونياً؟ إن كان نعم — متجر.',
            'هل الهدف الأساسي هو الاستفسارات والتواصل (لا البيع المباشر)؟ إن كان نعم — تعريفي.',
            'ما الميزانية والجدول الزمني؟ التعريفي أسرع وأرخص؛ المتجر يتطلّب تخطيطاً وميزانية أكبر.',
          ] },
          { h2: 'الحلّ الوسط' },
          { p: 'لست مضطرّاً لاختيار متطرّف. يمكنك بناء موقع تعريفي ممتاز وإضافة "متجر صغير" من بضعة منتجات أو زرّ طلب/دفع، دون إقامة نظام تجارة كامل. هكذا تبدأ بذكاء وتتوسّع عند وجود طلب حقيقي.' },
          { p: 'في كل الأحوال — يجب أن يكون النوعان سريعين ومتوافقين مع الجوّال ومبنيّين لـSEO، وإلّا فلن يجدك العملاء ببساطة على جوجل.' },
          { cta: 'لست متأكّداً ما يناسبك؟ لنتشاور' },
        ],
      },
    },
  },
  {
    slug: 'lama-esek-tzarich-atar',
    i18n: {
      he: {
        category: 'עסקים',
        title: '5 סיבות שהעסק שלך חייב אתר — גם אם יש לך אינסטגרם',
        desc: 'יש לכם דף עסקי באינסטגרם או פייסבוק וזה עובד? מעולה. הנה למה אתר משלכם עדיין הכרחי בדיוק בגלל זה.',
        excerpt: 'רשתות חברתיות הן שכירות. אתר הוא נכס בבעלותכם. 5 סיבות למה עסק חייב אתר משלו.',
        tldr: 'עמוד ברשת חברתית שייך לפלטפורמה — שינוי אלגוריתם או חסימה ומחקים את הקהל שלכם. אתר הוא נכס בבעלותכם: הוא מופיע בחיפוש בגוגל (שם לקוחות מחפשים שירות), משדר אמינות, נותן לכם שליטה מלאה בחוויה ובמסר, ועובד 24/7. הכי חכם: אתר במרכז, והרשתות מפנות אליו.',
        body: [
          { p: 'המשפט שאני שומע הכי הרבה: "יש לי אינסטגרם עם עוקבים, בשביל מה לי אתר?". התשובה חשובה, כי היא ההבדל בין לבנות על קרקע שלכם לבין לשכור דירה שבעל הבית יכול לפנות אתכם ממנה בכל רגע.' },
          { h2: '1. האתר שלכם — הבעלות שלכם' },
          { p: 'עמוד אינסטגרם שייך לאינסטגרם. שינוי אלגוריתם, חסימה בטעות או ירידה בחשיפה — וכל הקהל שבניתם נעלם. אתר הוא נכס דיגיטלי שבבעלותכם המלאה, אף אחד לא יכול לקחת לכם אותו.' },
          { h2: '2. לקוחות מחפשים בגוגל, לא רק בפיד' },
          { p: 'כשמישהו צריך "בונה אתרים בכרמיאל" או "מסעדה בעכו" — הוא מקליד בגוגל. בלי אתר, אתם פשוט לא קיימים בחיפוש הזה, ומפספסים את הלקוח בדיוק ברגע שהוא הכי מוכן לקנות.' },
          { h2: '3. אמינות ומקצועיות' },
          { p: 'אתר מסודר משדר עסק רציני. לקוח שמתלבט בין שני עסקים יבחר לרוב בזה שיש לו אתר מקצועי — זה אות לכך שאתם כאן לאורך זמן.' },
          { h2: '4. אתם שולטים בחוויה ובמסר' },
          { p: 'ברשת אתם כלואים בתבנית של הפלטפורמה. באתר אתם מחליטים מה הלקוח רואה קודם, איך הוא יוצר קשר, ואיזו פעולה הוא מבצע. זה מגדיל דרמטית את אחוז ההמרה.' },
          { h2: '5. האתר עובד בשבילכם 24/7' },
          { p: 'טופס יצירת קשר, כפתור וואטסאפ, שאלות נפוצות — האתר עונה ללקוחות גם ב-3 בלילה. במקום להסביר שוב ושוב את אותם דברים בהודעות, הכול כתוב, ברור וזמין.' },
          { p: 'הכי חכם? לחבר את הכול: אתר במרכז, והרשתות מפנות אליו תנועה. ככה בונים נוכחות דיגיטלית שהיא באמת שלכם.' },
          { cta: 'בואו נבנה לכם בית דיגיטלי משלכם' },
        ],
      },
      en: {
        category: 'Business',
        title: '5 Reasons Your Business Needs a Website — Even If You Have Instagram',
        desc: 'You have a business page on Instagram or Facebook and it works? Great. Here is why your own website is still essential — precisely because of that.',
        excerpt: 'Social networks are rented. A website is an asset you own. 5 reasons every business needs its own site.',
        tldr: 'A social page belongs to the platform — an algorithm change or a ban and your audience is gone. A website is an asset you own: it shows up in Google search (where customers look for a service), signals credibility, gives you full control of the experience and message, and works 24/7. The smart move: a website at the centre, with social pointing to it.',
        body: [
          { p: 'The line I hear most: "I have Instagram with followers, what do I need a website for?". The answer matters, because it is the difference between building on your own land and renting an apartment the landlord can evict you from at any moment.' },
          { h2: '1. Your website — your ownership' },
          { p: 'An Instagram page belongs to Instagram. An algorithm change, an accidental ban or a drop in reach — and the entire audience you built disappears. A website is a digital asset you fully own; no one can take it from you.' },
          { h2: '2. Customers search Google, not just the feed' },
          { p: 'When someone needs a "web designer in Karmiel" or a "restaurant in Akko" — they type it into Google. Without a website, you simply do not exist in that search, and you miss the customer exactly when they are most ready to buy.' },
          { h2: '3. Credibility and professionalism' },
          { p: 'A polished website signals a serious business. A customer choosing between two businesses will usually pick the one with a professional site — a sign that you are here for the long run.' },
          { h2: '4. You control the experience and the message' },
          { p: 'On social you are trapped in the platform’s template. On a website you decide what the customer sees first, how they get in touch, and what action they take. That dramatically raises your conversion rate.' },
          { h2: '5. Your website works for you 24/7' },
          { p: 'A contact form, a WhatsApp button, an FAQ — the website answers customers even at 3am. Instead of explaining the same things over and over in messages, it is all written, clear and available.' },
          { p: 'The smartest move? Connect it all: a website at the centre, with social sending traffic to it. That is how you build a digital presence that is truly yours.' },
          { cta: 'Let us build you a digital home of your own' },
        ],
      },
      ar: {
        category: 'أعمال',
        title: '5 أسباب تجعل عملك بحاجة لموقع — حتى لو كان لديك إنستغرام',
        desc: 'لديك صفحة عمل على إنستغرام أو فيسبوك وتعمل جيّداً؟ رائع. إليك لماذا يبقى موقعك الخاص ضرورياً — لهذا السبب بالذات.',
        excerpt: 'الشبكات الاجتماعية إيجار. الموقع أصل تملكه. 5 أسباب تجعل كل عمل بحاجة لموقعه الخاص.',
        tldr: 'الصفحة على شبكة اجتماعية ملك للمنصّة — تغيير في الخوارزمية أو حظر ويختفي جمهورك. الموقع أصل تملكه: يظهر في بحث جوجل (حيث يبحث العملاء عن الخدمة)، ويوحي بالمصداقية، ويمنحك تحكّماً كاملاً في التجربة والرسالة، ويعمل 24/7. الأذكى: الموقع في المركز والشبكات توجّه إليه.',
        body: [
          { p: 'أكثر جملة أسمعها: "لديّ إنستغرام بمتابعين، لماذا أحتاج موقعاً؟". الجواب مهم، لأنه الفرق بين البناء على أرضك وبين استئجار شقّة يمكن لصاحبها إخراجك منها في أي لحظة.' },
          { h2: '1. موقعك — ملكك أنت' },
          { p: 'صفحة إنستغرام ملك لإنستغرام. تغيير في الخوارزمية أو حظر بالخطأ أو انخفاض في الوصول — ويختفي كل الجمهور الذي بنيته. الموقع أصل رقمي تملكه بالكامل، لا أحد يستطيع أخذه منك.' },
          { h2: '2. العملاء يبحثون في جوجل، لا في الخلاصة فقط' },
          { p: 'حين يحتاج أحدهم "مصمّم مواقع في كرمئيل" أو "مطعم في عكّا" — يكتبها في جوجل. بدون موقع، أنت ببساطة غير موجود في ذلك البحث، وتفوّت العميل في اللحظة التي يكون فيها الأكثر استعداداً للشراء.' },
          { h2: '3. المصداقية والاحترافية' },
          { p: 'الموقع المرتّب يوحي بعمل جادّ. العميل المتردّد بين عملين يختار غالباً صاحب الموقع الاحترافي — إشارة إلى أنك هنا للأمد الطويل.' },
          { h2: '4. أنت تتحكّم بالتجربة والرسالة' },
          { p: 'على الشبكات أنت محصور في قالب المنصّة. على الموقع تقرّر ما يراه العميل أوّلاً، وكيف يتواصل، وأيّ إجراء ينفّذ. هذا يرفع نسبة التحويل بشكل كبير.' },
          { h2: '5. موقعك يعمل لصالحك 24/7' },
          { p: 'نموذج تواصل، زرّ واتساب، أسئلة شائعة — الموقع يجيب العملاء حتى الثالثة فجراً. بدل شرح الأمور نفسها مراراً في الرسائل، كلّ شيء مكتوب وواضح ومتاح.' },
          { p: 'الأذكى؟ اربط كل شيء: الموقع في المركز والشبكات توجّه إليه الزيارات. هكذا تبني حضوراً رقمياً هو حقّاً ملكك.' },
          { cta: 'لنبنِ لك بيتاً رقمياً خاصّاً بك' },
        ],
      },
    },
  },
  {
    slug: 'seo-mekomi-tzafon',
    i18n: {
      he: {
        category: 'SEO מקומי',
        title: 'SEO מקומי: איך העסק שלך יופיע ראשון בגוגל בצפון',
        desc: 'מדריך SEO מקומי מעשי לעסקים בצפון — איך לטפס בתוצאות החיפוש של גוגל בלי לשלם על פרסום.',
        excerpt: 'איך גורמים לגוגל להציג את העסק שלכם ראשון כשמחפשים שירות באזור שלכם — בלי לשלם על מודעות.',
        tldr: 'SEO מקומי בונים מ-4 אבני יסוד: פרופיל עסק מלא בגוגל, ביקורות אמיתיות שמזכירות עיר ושירות, עמוד ייעודי לכל אזור שירות, ואתר מהיר ומותאם לנייד. עקביות שבועית (עדכון, ביקורת, פוסט) היא מה שמזיז את הדירוג — לא תקציב פרסום.',
        body: [
          { p: 'רוב העסקים המקומיים מתחרים על אותו דבר: להופיע גבוה בגוגל כשלקוח מהאזור מחפש שירות. הבשורה הטובה — SEO מקומי הוא אחד הכלים הכי חזקים לצמיחה אורגנית, בלי לשלם שקל על פרסום. הנה איך זה עובד.' },
          { h2: 'מה זה בכלל SEO מקומי' },
          { p: 'SEO מקומי הוא כל מה שגורם לגוגל להבין איפה אתם, מה אתם עושים, ולמי כדאי להציג אתכם. כשמישהו בכרמיאל מחפש "מעצב אתרים", גוגל מנסה להציג לו עסקים רלוונטיים באזור שלו — ואתם רוצים להיות שם.' },
          { h2: '1. פרופיל עסק בגוגל (Google Business Profile)' },
          { p: 'זה הבסיס. פרופיל מלא, עם קטגוריה נכונה, שעות, תמונות ותיאור — הוא מה שמופיע במפה ובצד הימני של החיפוש. עדכנו אותו באופן קבוע: פוסטים, תמונות ותשובות לפניות. פרופיל "חי" מדורג גבוה יותר.' },
          { h2: '2. ביקורות Google' },
          { p: 'ביקורות הן מנוע הדירוג המקומי החזק ביותר. בקשו ביקורת מכל לקוח מרוצה, ובקשו שיזכיר את השירות והעיר בטקסט. ענו על כל ביקורת — גם זה סיגנל לגוגל שאתם פעילים.' },
          { h2: '3. עמודים מקומיים באתר' },
          { p: 'עמוד ייעודי לכל אזור שירות ("בניית אתרים בעכו", "בניית אתרים בכרמיאל") עוזר לגוגל לקשר אתכם לכל עיר. חשוב שהתוכן יהיה ייחודי ואמיתי לכל עמוד — לא העתק-הדבק.' },
          { h2: '4. אתר מהיר ומותאם לנייד' },
          { p: 'גוגל מדרג לפי מהירות וחוויית משתמש. אתר איטי או שנראה שבור בנייד יידחק למטה, כמה שלא תשקיעו בשאר. מהירות היא לא מותרות — היא תנאי סף.' },
          { h2: '5. עקביות מעל הכול' },
          { p: 'SEO מקומי הוא מרתון, לא ספרינט. עדכון פרופיל, ביקורת חדשה, פוסט או מאמר — כל שבוע. העקביות הזו היא בדיוק מה שהופך גרף חיפושים יורד לגרף עולה, לאורך זמן ובלי תקציב פרסום.' },
          { cta: 'רוצים אתר שבנוי מהיסוד ל-SEO מקומי?' },
        ],
        sources: [
          { name: 'Google — Local SEO / Business Profile', url: 'https://developers.google.com/search/docs/appearance/google-business-profile' },
        ],
      },
      en: {
        category: 'Local SEO',
        title: 'Local SEO: How to Get Your Business to the Top of Google in Your Area',
        desc: 'A practical local SEO guide for businesses — how to climb Google’s search results in your region without paying for ads.',
        excerpt: 'How to make Google show your business first when people search for a service in your area — without paying for ads.',
        tldr: 'Local SEO is built from 4 foundations: a complete Google Business Profile, real reviews that mention the city and service, a dedicated page per service area, and a fast, mobile-friendly site. Weekly consistency (an update, a review, a post) is what moves the ranking — not an ad budget.',
        body: [
          { p: 'Most local businesses compete for the same thing: showing up high on Google when a nearby customer searches for a service. The good news — local SEO is one of the strongest tools for organic growth, without paying a cent for ads. Here is how it works.' },
          { h2: 'What local SEO even is' },
          { p: 'Local SEO is everything that helps Google understand where you are, what you do, and who to show you to. When someone in Karmiel searches "web designer", Google tries to show them relevant businesses in their area — and you want to be there.' },
          { h2: '1. Google Business Profile' },
          { p: 'This is the foundation. A complete profile — with the right category, hours, photos and description — is what appears on the map and on the right side of the search. Update it regularly: posts, photos and replies to inquiries. A "live" profile ranks higher.' },
          { h2: '2. Google reviews' },
          { p: 'Reviews are the strongest local ranking engine. Ask every happy customer for a review, and ask them to mention the service and the city in the text. Reply to every review — that too signals to Google that you are active.' },
          { h2: '3. Local pages on your site' },
          { p: 'A dedicated page per service area ("web design in Akko", "web design in Karmiel") helps Google connect you to each city. It is important that the content is unique and genuine for each page — not copy-paste.' },
          { h2: '4. A fast, mobile-friendly site' },
          { p: 'Google ranks by speed and user experience. A slow site, or one that looks broken on mobile, gets pushed down no matter how much you invest in the rest. Speed is not a luxury — it is a baseline requirement.' },
          { h2: '5. Consistency above all' },
          { p: 'Local SEO is a marathon, not a sprint. A profile update, a new review, a post or an article — every week. That consistency is exactly what turns a declining search graph into a rising one, over time and with no ad budget.' },
          { cta: 'Want a site built from the ground up for local SEO?' },
        ],
        sources: [
          { name: 'Google — Local SEO / Business Profile', url: 'https://developers.google.com/search/docs/appearance/google-business-profile' },
        ],
      },
      ar: {
        category: 'SEO محلّي',
        title: 'السيو المحلّي: كيف يظهر عملك أوّلاً في جوجل بمنطقتك',
        desc: 'دليل عملي للسيو المحلّي للأعمال — كيف تتصدّر نتائج بحث جوجل في منطقتك دون الدفع مقابل الإعلانات.',
        excerpt: 'كيف تجعل جوجل يعرض عملك أوّلاً عند البحث عن خدمة في منطقتك — دون الدفع مقابل الإعلانات.',
        tldr: 'السيو المحلّي يُبنى من 4 ركائز: ملف نشاط تجاري كامل على جوجل، وتقييمات حقيقية تذكر المدينة والخدمة، وصفحة مخصّصة لكل منطقة خدمة، وموقع سريع ومتوافق مع الجوّال. الاستمرارية الأسبوعية (تحديث، تقييم، منشور) هي ما يحرّك الترتيب — لا ميزانية الإعلانات.',
        body: [
          { p: 'معظم الأعمال المحلّية تتنافس على الشيء نفسه: الظهور عالياً في جوجل حين يبحث عميل قريب عن خدمة. الخبر الجيّد — السيو المحلّي من أقوى أدوات النمو العضوي، دون دفع شيكل واحد للإعلانات. إليك كيف يعمل.' },
          { h2: 'ما هو السيو المحلّي أصلاً' },
          { p: 'السيو المحلّي هو كل ما يساعد جوجل على فهم أين أنت، وماذا تفعل، ولمن يجب أن يعرضك. حين يبحث أحدهم في كرمئيل عن "مصمّم مواقع"، يحاول جوجل عرض أعمال ذات صلة في منطقته — وأنت تريد أن تكون هناك.' },
          { h2: '1. ملف النشاط التجاري على جوجل (Google Business Profile)' },
          { p: 'هذا هو الأساس. ملف كامل — بالفئة الصحيحة والساعات والصور والوصف — هو ما يظهر على الخريطة وعلى يمين البحث. حدّثه باستمرار: منشورات وصور وردود على الاستفسارات. الملف "الحيّ" يُرتّب أعلى.' },
          { h2: '2. تقييمات جوجل' },
          { p: 'التقييمات هي أقوى محرّك للترتيب المحلّي. اطلب تقييماً من كل عميل راضٍ، واطلب منه ذكر الخدمة والمدينة في النص. ردّ على كل تقييم — فهذا أيضاً إشارة لجوجل بأنك نشط.' },
          { h2: '3. صفحات محلّية في موقعك' },
          { p: 'صفحة مخصّصة لكل منطقة خدمة ("بناء مواقع في عكّا"، "بناء مواقع في كرمئيل") تساعد جوجل على ربطك بكل مدينة. المهم أن يكون المحتوى فريداً وحقيقياً لكل صفحة — لا نسخاً ولصقاً.' },
          { h2: '4. موقع سريع ومتوافق مع الجوّال' },
          { p: 'جوجل يرتّب حسب السرعة وتجربة المستخدم. الموقع البطيء، أو الذي يبدو معطّلاً على الجوّال، يُدفع للأسفل مهما استثمرت في الباقي. السرعة ليست رفاهية — بل شرط أساسي.' },
          { h2: '5. الاستمرارية فوق كل شيء' },
          { p: 'السيو المحلّي ماراثون لا سباق سريع. تحديث ملف، تقييم جديد، منشور أو مقال — كل أسبوع. هذه الاستمرارية هي بالضبط ما يحوّل منحنى البحث الهابط إلى صاعد، مع الوقت وبلا ميزانية إعلانات.' },
          { cta: 'تريد موقعاً مبنيّاً من الأساس للسيو المحلّي؟' },
        ],
        sources: [
          { name: 'Google — Local SEO / Business Profile', url: 'https://developers.google.com/search/docs/appearance/google-business-profile' },
        ],
      },
    },
  },
  {
    slug: 'wordpress-mul-react',
    i18n: {
      he: {
        category: 'טכנולוגיה',
        title: 'וורדפרס מול אתר בהתאמה אישית (React): מה עדיף לעסק שלך?',
        desc: 'וורדפרס או אתר בהתאמה אישית ב-React? השוואה כנה של מהירות, אבטחה, גמישות ועלות — כדי שתבחרו נכון.',
        excerpt: 'וורדפרס מהיר להקים אבל כבד; אתר בהתאמה אישית מהיר וייחודי אבל דורש מפתח. איך בוחרים?',
        tldr: 'וורדפרס מהיר להקים ונוח לעריכה עצמאית, אבל תוספים מכבידים ודורשים עדכוני אבטחה. אתר בהתאמה אישית (React) מהיר יותר, מאובטח יותר וייחודי, אך דורש מפתח. אתר תוכן שמתעדכן יומיומית → וורדפרס עשוי להתאים; אתר מהיר, ממיר ובולט → התאמה אישית משתלמת לאורך זמן.',
        body: [
          { p: 'כשמתחילים לחשוב על אתר, שתי המילים שחוזרות הן "וורדפרס" ו"אתר בהתאמה אישית". שתיהן לגיטימיות — אבל הן פותרות בעיות שונות. הנה השוואה כנה שתעזור לכם להחליט לפי מה שחשוב לעסק שלכם.' },
          { h2: 'מה זה וורדפרס' },
          { p: 'וורדפרס היא מערכת ניהול תוכן (CMS) שמריצה חלק גדול מהאינטרנט. בונים איתה אתר מהר יחסית בעזרת תבניות ותוספים (plugins). היתרון: מהירות הקמה ועריכת תוכן עצמאית. החיסרון: תוספים רבים מכבידים על האתר, דורשים עדכוני אבטחה תכופים, ולעיתים האתר נראה "כמו כולם".' },
          { h2: 'מה זה אתר בהתאמה אישית (React)' },
          { p: 'אתר בהתאמה אישית נבנה מהיסוד בקוד (למשל React / Next.js). כל פיקסל וכל פונקציה נבנים בדיוק לצרכים שלכם. היתרון: מהירות גבוהה מאוד, אבטחה טובה יותר (פחות "דלתות" פתוחות), עיצוב ייחודי וחוויית משתמש מלוטשת. החיסרון: דורש מפתח כדי לבנות ולעדכן שינויים מבניים.' },
          { h2: 'השוואה מהירה' },
          { ul: [
            'מהירות: אתר בהתאמה אישית כמעט תמיד מהיר יותר — וזה משפיע ישירות על דירוג בגוגל ועל המרות.',
            'אבטחה: פחות תוספים = פחות פרצות. אתר מותאם אישית בטוח יותר כברירת מחדל.',
            'גמישות עיצוב: בהתאמה אישית אין גבול; בוורדפרס מוגבלים לתבנית ולתוספים.',
            'עריכת תוכן: וורדפרס נוח לעריכה עצמאית; באתר מותאם אפשר להוסיף מערכת ניהול תוכן לפי הצורך.',
            'עלות לאורך זמן: וורדפרס זול בהקמה אך צובר עלויות תוספים ותחזוקה; מותאם אישית יקר יותר בהתחלה אך יציב וזול לתחזוקה.',
          ] },
          { h2: 'אז מה לבחור?' },
          { p: 'אם אתם צריכים אתר תוכן שמתעדכן יומיומית ורוצים לערוך לבד — וורדפרס יכול להתאים. אם אתם רוצים אתר מהיר, ייחודי, מאובטח וממיר שמייצג עסק שרוצה לבלוט — אתר בהתאמה אישית ישתלם לכם הרבה יותר לאורך זמן. אני בונה בהתאמה אישית בדיוק בגלל היתרונות האלה, ומוסיף מערכת ניהול תוכן כשצריך.' },
          { cta: 'לא בטוחים מה מתאים? בואו נתייעץ' },
        ],
      },
      en: {
        category: 'Technology',
        title: 'WordPress vs. a Custom Site (React): Which Is Better for Your Business?',
        desc: 'WordPress or a custom React site? An honest comparison of speed, security, flexibility and cost — so you choose right.',
        excerpt: 'WordPress is quick to set up but heavy; a custom site is fast and unique but needs a developer. How do you choose?',
        tldr: 'WordPress is quick to set up and easy to edit yourself, but plugins add weight and require security updates. A custom site (React) is faster, more secure and unique, but needs a developer. A content site updated daily → WordPress may fit; a fast, converting, standout site → a custom build pays off over time.',
        body: [
          { p: 'When you start thinking about a website, two words keep coming up: "WordPress" and "a custom site". Both are legitimate — but they solve different problems. Here is an honest comparison to help you decide by what matters for your business.' },
          { h2: 'What WordPress is' },
          { p: 'WordPress is a content management system (CMS) that runs a large share of the web. You build a site with it relatively fast using themes and plugins. The upside: quick setup and self-service content editing. The downside: many plugins weigh the site down, require frequent security updates, and sometimes the site ends up looking "like everyone else’s".' },
          { h2: 'What a custom site (React) is' },
          { p: 'A custom site is built from the ground up in code (e.g. React / Next.js). Every pixel and every function is built precisely to your needs. The upside: very high speed, better security (fewer open "doors"), a unique design and a polished user experience. The downside: it needs a developer to build and to make structural changes.' },
          { h2: 'Quick comparison' },
          { ul: [
            'Speed: a custom site is almost always faster — which directly affects Google ranking and conversions.',
            'Security: fewer plugins = fewer holes. A custom site is safer by default.',
            'Design flexibility: with custom there is no limit; with WordPress you are bound to the theme and plugins.',
            'Content editing: WordPress is convenient to edit yourself; a custom site can add a CMS as needed.',
            'Cost over time: WordPress is cheap to set up but accrues plugin and maintenance costs; custom is pricier upfront but stable and cheap to maintain.',
          ] },
          { h2: 'So what should you choose?' },
          { p: 'If you need a content site updated daily and want to edit it yourself — WordPress can fit. If you want a fast, unique, secure, converting site that represents a business that wants to stand out — a custom site will pay off far more over time. I build custom precisely for these advantages, and add a content management system when needed.' },
          { cta: 'Not sure which fits? Let us talk it through' },
        ],
      },
      ar: {
        category: 'تقنية',
        title: 'ووردبريس مقابل موقع مخصّص (React): أيّهما أفضل لعملك؟',
        desc: 'ووردبريس أم موقع مخصّص بـReact؟ مقارنة صادقة للسرعة والأمان والمرونة والتكلفة — لتختار بشكل صحيح.',
        excerpt: 'ووردبريس سريع الإقامة لكنه ثقيل؛ الموقع المخصّص سريع وفريد لكنه يتطلّب مطوّراً. كيف تختار؟',
        tldr: 'ووردبريس سريع الإقامة وسهل التحرير بنفسك، لكن الإضافات تثقله وتتطلّب تحديثات أمان. الموقع المخصّص (React) أسرع وأكثر أماناً وفريد، لكنه يتطلّب مطوّراً. موقع محتوى يُحدّث يومياً → قد يناسبه ووردبريس؛ موقع سريع ومحوِّل وبارز → المخصّص يستحقّ على المدى البعيد.',
        body: [
          { p: 'حين تبدأ التفكير في موقع، تتكرّر كلمتان: "ووردبريس" و"موقع مخصّص". كلاهما مشروع — لكنهما يحلّان مشكلتين مختلفتين. إليك مقارنة صادقة تساعدك على القرار حسب ما يهمّ عملك.' },
          { h2: 'ما هو ووردبريس' },
          { p: 'ووردبريس نظام إدارة محتوى (CMS) يُشغّل جزءاً كبيراً من الإنترنت. تبني به موقعاً بسرعة نسبياً بمساعدة القوالب والإضافات (plugins). الميزة: سرعة الإقامة وتحرير المحتوى ذاتياً. العيب: كثرة الإضافات تثقل الموقع، وتتطلّب تحديثات أمان متكرّرة، وأحياناً يبدو الموقع "كالجميع".' },
          { h2: 'ما هو الموقع المخصّص (React)' },
          { p: 'الموقع المخصّص يُبنى من الأساس بالكود (مثل React / Next.js). كل بكسل وكل وظيفة يُبنيان تماماً حسب حاجتك. الميزة: سرعة عالية جدّاً، وأمان أفضل (أبواب مفتوحة أقل)، وتصميم فريد وتجربة مستخدم مصقولة. العيب: يتطلّب مطوّراً للبناء ولإجراء تغييرات بنيوية.' },
          { h2: 'مقارنة سريعة' },
          { ul: [
            'السرعة: الموقع المخصّص أسرع دائماً تقريباً — وهذا يؤثّر مباشرة على الترتيب في جوجل وعلى التحويلات.',
            'الأمان: إضافات أقل = ثغرات أقل. الموقع المخصّص أكثر أماناً بشكل افتراضي.',
            'مرونة التصميم: في المخصّص لا حدود؛ في ووردبريس أنت مقيّد بالقالب والإضافات.',
            'تحرير المحتوى: ووردبريس مريح للتحرير ذاتياً؛ الموقع المخصّص يمكن أن يضيف نظام إدارة محتوى حسب الحاجة.',
            'التكلفة على المدى: ووردبريس رخيص في الإقامة لكنه يراكم تكاليف إضافات وصيانة؛ المخصّص أغلى في البداية لكنه مستقرّ ورخيص الصيانة.',
          ] },
          { h2: 'إذن ماذا تختار؟' },
          { p: 'إن كنت تحتاج موقع محتوى يُحدّث يومياً وتريد التحرير بنفسك — قد يناسبك ووردبريس. وإن كنت تريد موقعاً سريعاً وفريداً وآمناً ومحوِّلاً يمثّل عملاً يريد أن يبرز — فالموقع المخصّص سيستحقّ أكثر بكثير على المدى البعيد. أنا أبني مخصّصاً لهذه المزايا بالذات، وأضيف نظام إدارة محتوى عند الحاجة.' },
          { cta: 'لست متأكّداً ما يناسبك؟ لنتشاور' },
        ],
      },
    },
  },
  {
    slug: 'kama-zman-lokeach-livnot-atar',
    i18n: {
      he: {
        category: 'תהליך',
        title: 'כמה זמן לוקח לבנות אתר? ציר זמן ריאלי משיחה ועד עלייה לאוויר',
        desc: 'כמה זמן באמת לוקח לבנות אתר? פירוק שלב-אחר-שלב של התהליך וטווחי זמן ריאליים לפי סוג האתר.',
        excerpt: 'משיחת אפיון ועד עלייה לאוויר — כמה זמן כל שלב לוקח, ומה מזרז או מעכב את הפרויקט.',
        tldr: 'בניית אתר עוברת 5 שלבים: אפיון (1–3 ימים), עיצוב (3–7), פיתוח (5–14), תוכן ובדיקות (2–4), ועלייה לאוויר (יום). דף נחיתה: 3–5 ימים; אתר תדמית: שבוע-שבועיים; אתר רב-לשוני: 2–4 שבועות; חנות: חודש עד שלושה. תוכן מוכן מראש ומשוב מהיר מזרזים; שינויי כיוון מעכבים.',
        body: [
          { p: '"מתי האתר יהיה מוכן?" — שאלה הוגנת לגמרי. התשובה תלויה בהיקף, אבל התהליך עצמו די קבוע. הנה ציר הזמן הריאלי, שלב אחר שלב.' },
          { h2: 'שלב 1: אפיון ותכנון (1–3 ימים)' },
          { p: 'נשב (או נדבר בוואטסאפ) ונגדיר: מה מטרת האתר, אילו עמודים צריך, מי הקהל ומה הפעולה שאנחנו רוצים שהמבקר יעשה. ככל שהשלב הזה ברור יותר, כל השאר זורם מהר יותר.' },
          { h2: 'שלב 2: עיצוב (3–7 ימים)' },
          { p: 'בונים מראה ותחושה — צבעים, פונטים, מבנה העמודים. אתם מאשרים לפני שכותבים שורת קוד אחת, כדי שלא יהיו הפתעות.' },
          { h2: 'שלב 3: פיתוח (5–14 ימים)' },
          { p: 'הופכים את העיצוב לאתר עובד, מהיר ומותאם לנייד. כאן נכנסים גם טפסים, אינטגרציות (וואטסאפ, יומן) ו-SEO טכני.' },
          { h2: 'שלב 4: תוכן ובדיקות (2–4 ימים)' },
          { p: 'מכניסים טקסטים ותמונות, ובודקים הכל: תצוגה בכל מכשיר, מהירות, קישורים, טפסים. מתקנים פרטים אחרונים.' },
          { h2: 'שלב 5: עלייה לאוויר (1 יום)' },
          { p: 'מחברים דומיין, אחסון ו-SSL, מעלים לאוויר ומגישים לגוגל. האתר חי.' },
          { h2: 'טווחי זמן לפי סוג אתר' },
          { ul: [
            'דף נחיתה: 3–5 ימים.',
            'אתר תדמית (3–6 עמודים): שבוע עד שבועיים.',
            'אתר מורחב / רב-לשוני: 2–4 שבועות.',
            'חנות אונליין / מערכת: חודש עד שלושה.',
          ] },
          { p: 'מה מזרז? תוכן ותמונות מוכנים מראש, ומשוב מהיר בשלבי האישור. מה מעכב? שינויי כיוון באמצע והמתנה לתכנים. אצלי — לוח זמנים ברור מראש, בלי הפתעות.' },
          { cta: 'רוצים אתר מוכן בזמן? בואו נתחיל' },
        ],
      },
      en: {
        category: 'Process',
        title: 'How Long Does It Take to Build a Website? A Realistic Timeline',
        desc: 'How long a website really takes to build: a step-by-step breakdown of the process and realistic timeframes by type of site.',
        excerpt: 'From the kickoff call to launch — how long each stage takes, and what speeds up or slows down the project.',
        tldr: 'Building a website goes through 5 stages: discovery (1–3 days), design (3–7), development (5–14), content and testing (2–4), and launch (1 day). Landing page: 3–5 days; brochure site: one to two weeks; multilingual site: 2–4 weeks; store: one to three months. Ready-made content and fast feedback speed it up; changes of direction slow it down.',
        body: [
          { p: '"When will the site be ready?" — a completely fair question. The answer depends on scope, but the process itself is fairly fixed. Here is the realistic timeline, stage by stage.' },
          { h2: 'Stage 1: discovery and planning (1–3 days)' },
          { p: 'We sit down (or talk on WhatsApp) and define: the site’s goal, which pages are needed, who the audience is, and the action we want the visitor to take. The clearer this stage, the faster everything else flows.' },
          { h2: 'Stage 2: design (3–7 days)' },
          { p: 'We build the look and feel — colours, fonts, page structure. You approve before a single line of code is written, so there are no surprises.' },
          { h2: 'Stage 3: development (5–14 days)' },
          { p: 'We turn the design into a working, fast, mobile-friendly site. This is also where forms, integrations (WhatsApp, calendar) and technical SEO come in.' },
          { h2: 'Stage 4: content and testing (2–4 days)' },
          { p: 'We add the text and images, and test everything: rendering on every device, speed, links, forms. We fix the last details.' },
          { h2: 'Stage 5: launch (1 day)' },
          { p: 'We connect the domain, hosting and SSL, push it live and submit to Google. The site is live.' },
          { h2: 'Timeframes by type of site' },
          { ul: [
            'Landing page: 3–5 days.',
            'Brochure site (3–6 pages): one to two weeks.',
            'Extended / multilingual site: 2–4 weeks.',
            'Online store / system: one to three months.',
          ] },
          { p: 'What speeds it up? Content and images ready in advance, and fast feedback at the approval stages. What slows it down? Changes of direction mid-way and waiting on content. With me — a clear timeline set upfront, no surprises.' },
          { cta: 'Want a site ready on time? Let us start' },
        ],
      },
      ar: {
        category: 'العملية',
        title: 'كم يستغرق بناء موقع؟ جدول زمني واقعي من المكالمة حتى الإطلاق',
        desc: 'كم يستغرق بناء موقع حقّاً؟ تفصيل خطوة بخطوة للعملية وأطر زمنية واقعية حسب نوع الموقع.',
        excerpt: 'من مكالمة التوصيف حتى الإطلاق — كم يستغرق كل مرحلة، وما يُسرّع أو يُعطّل المشروع.',
        tldr: 'بناء الموقع يمرّ بـ5 مراحل: التوصيف (1–3 أيام)، التصميم (3–7)، التطوير (5–14)، المحتوى والفحص (2–4)، والإطلاق (يوم). صفحة هبوط: 3–5 أيام؛ موقع تعريفي: أسبوع إلى أسبوعين؛ موقع متعدّد اللغات: 2–4 أسابيع؛ متجر: شهر إلى ثلاثة. المحتوى الجاهز مسبقاً والملاحظات السريعة تُسرّع؛ تغييرات الاتجاه تُعطّل.',
        body: [
          { p: '"متى يجهز الموقع؟" — سؤال عادل تماماً. الجواب يعتمد على الحجم، لكن العملية نفسها ثابتة نسبياً. إليك الجدول الزمني الواقعي، مرحلة بمرحلة.' },
          { h2: 'المرحلة 1: التوصيف والتخطيط (1–3 أيام)' },
          { p: 'نجلس (أو نتحدّث عبر واتساب) ونحدّد: هدف الموقع، وأيّ صفحات نحتاج، ومن الجمهور، والإجراء الذي نريد أن ينفّذه الزائر. كلّما كانت هذه المرحلة أوضح، تدفّق كل ما بعدها أسرع.' },
          { h2: 'المرحلة 2: التصميم (3–7 أيام)' },
          { p: 'نبني الشكل والإحساس — الألوان والخطوط وبنية الصفحات. تعتمد التصميم قبل كتابة سطر كود واحد، حتى لا تكون هناك مفاجآت.' },
          { h2: 'المرحلة 3: التطوير (5–14 يوماً)' },
          { p: 'نحوّل التصميم إلى موقع عامل وسريع ومتوافق مع الجوّال. هنا تدخل أيضاً النماذج والتكاملات (واتساب، تقويم) والسيو التقني.' },
          { h2: 'المرحلة 4: المحتوى والفحص (2–4 أيام)' },
          { p: 'ندخل النصوص والصور، ونفحص كل شيء: العرض على كل جهاز، والسرعة، والروابط، والنماذج. ونصلح التفاصيل الأخيرة.' },
          { h2: 'المرحلة 5: الإطلاق (يوم واحد)' },
          { p: 'نربط الدومين والاستضافة وشهادة SSL، ونرفعه للهواء ونقدّمه لجوجل. الموقع حيّ.' },
          { h2: 'أطر زمنية حسب نوع الموقع' },
          { ul: [
            'صفحة هبوط: 3–5 أيام.',
            'موقع تعريفي (3–6 صفحات): أسبوع إلى أسبوعين.',
            'موقع موسّع / متعدّد اللغات: 2–4 أسابيع.',
            'متجر إلكتروني / نظام: شهر إلى ثلاثة.',
          ] },
          { p: 'ما الذي يُسرّع؟ محتوى وصور جاهزة مسبقاً، وملاحظات سريعة في مراحل الاعتماد. وما الذي يُعطّل؟ تغييرات الاتجاه في المنتصف والانتظار للمحتوى. معي — جدول زمني واضح من البداية، بلا مفاجآت.' },
          { cta: 'تريد موقعاً جاهزاً في الوقت؟ لنبدأ' },
        ],
      },
    },
  },
];
