import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { ARTICLES } from './blog-content.mjs';
import { reviewArticles } from './blog/editorial.mjs';
import { UI, esc, prefix, shell, cover } from './blog/ui.mjs';
const posts=reviewArticles(ARTICLES);
const url=(l,a)=>`${prefix(l)}/blog/${a.slug}/`;
const minutes=loc=>Math.max(1,Math.ceil(JSON.stringify(loc.body).split(/\s+/).length/180));
function card(a,l){const loc=a.i18n[l],t=UI[l];return `<a class="post-card" data-card data-topic="${a.topic}" href="${url(l,a)}">${cover(a.topic)}<div class="card-body"><div class="eyebrow">${t.topics[a.topic]} <span>· ${minutes(loc)} ${t.min}</span></div><h3>${esc(loc.title)}</h3><p>${esc(loc.excerpt)}</p><span class="read">${t.read} <span aria-hidden="true">↗</span></span></div></a>`;}
function index(l){const t=UI[l],feature=posts[0],loc=feature.i18n[l];return shell(l,{title:t.brand,description:t.lead,path:`${prefix(l)}/blog/`,schema:[{'@context':'https://schema.org','@type':'Blog',name:t.brand,url:`https://www.vasia.dev${prefix(l)}/blog/`,inLanguage:l}],body:`<main id="content" class="wide"><section class="journal-hero"><p class="eyebrow">${t.eyebrow} <span class="live-dot"></span></p><h1>${t.brand}</h1><p class="lead">${t.lead}</p></section><a class="feature" href="${url(l,feature)}"><div class="feature-copy"><span class="pill">${t.featured}</span><p class="eyebrow">01 / ${t.topics[feature.topic]}</p><h2>${esc(loc.title)}</h2><p>${esc(loc.excerpt)}</p><span class="read">${t.read} ↗</span></div>${cover(feature.topic,true)}</a><section class="browse" aria-labelledby="browse-title"><div class="section-heading"><h2 id="browse-title">${t.articles}</h2><span id="result-count" aria-live="polite">${posts.length} ${t.count}</span></div><div class="filter-panel" data-filter-root><label class="search"><span aria-hidden="true">⌕</span><input type="search" id="article-search" placeholder="${t.search}" aria-label="${t.search}"></label><div class="filters" role="group" aria-label="${t.articles}"><button data-filter="all" aria-pressed="true">${t.all}</button>${Object.entries(t.topics).map(([id,label])=>`<button data-filter="${id}" aria-pressed="false">${label}</button>`).join('')}</div></div><div class="cards" data-results data-count-label="${t.count}">${posts.map(a=>card(a,l)).join('')}</div><p class="empty" id="empty-results" hidden>${t.empty}</p></section><aside class="editorial-note"><span class="note-icon" aria-hidden="true">↗</span><div><h2>${t.sources}</h2><p>${t.sourceNote}</p><span>${t.checked}: <time datetime="2026-10-01">01.10.2026</time></span></div></aside></main>`});}
function article(a,l){const t=UI[l],loc=a.i18n[l],refs=loc.sources;let section=0;const toc=loc.body.filter(b=>b.h2);const body=loc.body.map(b=>{
 if(b.h2)return `<h2 id="section-${++section}">${esc(b.h2)}</h2>`;
 if(b.p)return `<p>${esc(b.p)}${(b.refs||[]).map(id=>` <a class="cite" href="#source-${id}" aria-label="${t.sources}: ${esc(refs.find(s=>s.id===id).name)}">[${refs.findIndex(s=>s.id===id)+1}]</a>`).join('')}</p>`;
 if(b.checklist)return `<p class="muted small">${t.practice}</p><div class="checklist">${b.checklist.map((v,i)=>`<label><input type="checkbox"><span>${esc(v)}</span></label>`).join('')}</div>`;return '';
 }).join('');const related=posts.filter(p=>p.slug!==a.slug).sort((x,y)=>Number(y.topic===a.topic)-Number(x.topic===a.topic)).slice(0,3);
 return shell(l,{title:loc.title,description:loc.desc,path:url(l,a),schema:[{'@context':'https://schema.org','@type':'BlogPosting',headline:loc.title,description:loc.desc,dateModified:'2026-10-01',inLanguage:l,author:{'@type':'Person',name:'Waseem Abu Akel',url:'https://www.vasia.dev/'},citation:refs.map(s=>s.url),mainEntityOfPage:`https://www.vasia.dev${url(l,a)}`}],body:`<div class="reading-progress" aria-hidden="true"><span id="reading-progress"></span></div><main id="content" class="wide"><header class="article-hero"><a class="back" href="${prefix(l)}/blog/">${t.back}</a><p class="eyebrow">${t.topics[a.topic]} · ${minutes(loc)} ${t.min}</p><h1>${esc(loc.title)}</h1><p class="lead">${esc(loc.excerpt)}</p><div class="byline"><img src="/assets/waseem-profile.webp" width="42" height="42" alt="Waseem"><span>Waseem Abu Akel <small>${t.checked} · 01.10.2026</small></span></div></header><figure class="article-visual">${cover(a.topic,true)}<figcaption>${t.image}</figcaption></figure><div class="reading-layout"><aside class="reading-tools"><nav aria-label="${t.toc}"><h2>${t.toc}</h2>${toc.map((b,i)=>`<a href="#section-${i+1}">${esc(b.h2)}</a>`).join('')}<a href="#sources">${t.sources}</a></nav><div class="tools"><button id="text-size" aria-pressed="false">Aa · ${t.bigger}</button><button id="copy-link" data-success="${t.copied}" data-failure="${t.copyFailed}">${t.copy}</button><span id="copy-status" role="status"></span></div></aside><div class="paper"><article id="article-body">${body}</article><section id="sources" class="sources"><h2>${t.sources}</h2><p class="small muted">${t.sourceNote}</p><ol>${refs.map(s=>`<li id="source-${s.id}"><a href="${s.url}" target="_blank" rel="noopener noreferrer">${esc(s.name)} ↗</a><span dir="ltr">${new URL(s.url).hostname}</span></li>`).join('')}</ol></section><aside class="question"><h2>${t.question}</h2><a class="button" data-contact-location="article" href="https://wa.me/972534260632?text=${encodeURIComponent(loc.title+' — https://www.vasia.dev'+url(l,a))}" target="_blank" rel="noopener noreferrer">${t.ask} ↗</a></aside></div></div><section class="related"><h2>${t.related}</h2><div class="cards">${related.map(p=>card(p,l)).join('')}</div></section></main>`});}
for(const l of ['he','en','ar']){const dir=resolve('public',prefix(l).slice(1),'blog');mkdirSync(dir,{recursive:true});writeFileSync(resolve(dir,'index.html'),index(l));for(const a of posts){const d=resolve(dir,a.slug);mkdirSync(d,{recursive:true});writeFileSync(resolve(d,'index.html'),article(a,l));}}console.log('Generated journal: 3 indexes, 39 reviewed guides.');
