import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import ts from 'typescript';
import { UI, esc, prefix, shell } from './blog/ui.mjs';
// Reuse approved portfolio disclosures and source descriptions verbatim.
const source=readFileSync('src/features/video-ads/content.ts','utf8');
const {outputText}=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}});
const {videoAdsCopy}=await import('data:text/javascript;base64,'+Buffer.from(outputText).toString('base64'));
const copy={
 he:{title:'עבודות שמדברות בצבע.',intro:'וידאו, עיצוב ואתרים מתוך תיק העבודות. בחרו תחום, פתחו תמונה וגלו את הסיפור מאחוריה.',all:'הכול',video:'וידאו וסושיאל',web:'אתרים',brand:'מיתוג',items:'עבודות',open:'להגדלת התמונה',close:'סגירה',story:'לסיפור הפרויקט',empty:'אין עבודות בקטגוריה הזו.',storiesTitle:'מהרעיון לתוצר.',storiesLead:'המטרה, חומרי המקור וההחלטות שהפכו אותם לעבודה שאפשר לראות.',goal:'המטרה',process:'העבודה',delivery:'התוצר',material:'חומרי המקור',watch:'לצפייה בעבודה',talk:'רוצים עבודה כזו לעסק שלכם?',cta:'בואו נדבר',demo:'קונספט לתיק עבודות — לא פרויקט לקוח',studioGoal:'להדגים אתר תדמית שמציג שירותים ועבודות באופן ברור.',studioProcess:'הפרדה בין היכרות, הצגת שירותים ועבודות, עם מבנה תוכן שניתן לעריכה ב־WordPress.',studioDelivery:'אתר הדגמה ב־WordPress עם Gutenberg. התצוגה בגלריה היא הדמיית עיצוב; הדמו המקושר מאפשר לבחון את האתר עצמו.'},
 en:{title:'Work in full colour.',intro:'Video, design and websites from the portfolio. Pick a category, open an image and explore the story behind it.',all:'All',video:'Video & social',web:'Websites',brand:'Branding',items:'works',open:'Enlarge image',close:'Close',story:'Read the project story',empty:'No work in this category.',storiesTitle:'From idea to finished work.',storiesLead:'The purpose, source material and decisions behind work you can actually explore.',goal:'The goal',process:'The work',delivery:'The deliverable',material:'Source material',watch:'Explore the work',talk:'Want something like this for your business?',cta:'Let’s talk',demo:'Portfolio concept — not a client commission',studioGoal:'Demonstrate a business website that clearly presents services and work.',studioProcess:'Separate introduction, services and work into an editable WordPress content structure.',studioDelivery:'A WordPress demonstration site using Gutenberg. The gallery image is a design mockup; the linked demo lets you explore the website itself.'},
 ar:{title:'شغل بيحكي بالألوان.',intro:'فيديو وتصميم ومواقع من معرض الأعمال. اختار مجال، افتح الصورة واكتشف القصة وراها.',all:'الكل',video:'فيديو وسوشيال',web:'مواقع',brand:'هوية بصرية',items:'أعمال',open:'تكبير الصورة',close:'إغلاق',story:'اقرأ قصة المشروع',empty:'ما في أعمال بهالتصنيف.',storiesTitle:'من الفكرة للشغل الجاهز.',storiesLead:'الهدف، المواد الأصلية والقرارات اللي صارت شغل بتقدر تشوفه.',goal:'الهدف',process:'الشغل',delivery:'التسليم',material:'المواد الأصلية',watch:'شوف الشغل',talk:'بدك شغل هيك لمصلحتك؟',cta:'خلّينا نحكي',demo:'فكرة لمعرض الأعمال — مش طلب من زبون',studioGoal:'عرض فكرة موقع تعريفي بيوضح الخدمات والأعمال.',studioProcess:'تقسيم التعريف والخدمات والأعمال بمحتوى قابل للتعديل على WordPress.',studioDelivery:'موقع تجريبي بـWordPress وGutenberg. صورة المعرض نموذج للتصميم؛ الرابط بيفتح الموقع التجريبي نفسه.'}
};
const works=[
 ['ninnyo-friday','NINNYO FLOWERS','video','/assets/video-ads/ninnyo-friday-thumbnail.webp','ninnyo-friday'],
 ['greentouch','GreenTouch','video','/assets/video-ads/greentouch-thumbnail.webp','greentouch'],
 ['wordpress-studio','Waseem Studio','web','/assets/wordpress-portfolio.svg','wordpress-studio'],
 ['ninnyo-roses','NINNYO · Red roses','video','/assets/video-ads/ninnyo-red-roses-thumbnail.webp','ninnyo-friday'],
 ['souvlaki','Souvlaki','web','/assets/souvlaki.webp',null],
 ['vocaband','Vocaband','web','/assets/vocaband.webp',null],
 ['ninnyo-12','NINNYO · Friday 12s','video','/assets/video-ads/ninnyo-friday-12s-thumbnail.webp','ninnyo-friday'],
 ['vasia','Vasia','brand','/brand/vasia-share.png',null],
 ['wordpress-shop','Waseem Shop','web','/assets/wordpress-shop.svg','wordpress-studio'],
];
const storyIds=['ninnyo-friday','greentouch','wordpress-studio'];
const dest=(l,id)=>`${prefix(l)}/stories/${id}/`;
function data(l,id){const t=copy[l];if(id==='wordpress-studio')return{title:'Waseem Studio',image:'/assets/wordpress-portfolio.svg',disclosure:t.demo,goal:t.studioGoal,process:t.studioProcess,delivery:t.studioDelivery,source:'WordPress · Gutenberg',link:'https://waseemstudiodemo.wordpress.com/'};const p=videoAdsCopy[l].projects[id];return{title:p.project,image:works.find(w=>w[0]===id)[3],disclosure:p.disclosure,goal:p.purpose,process:p.edit,delivery:p.format,source:p.source,link:`/video-ads?lang=${l}#${id}`};}
function storyCard(l,id){const d=data(l,id),t=copy[l];return `<a class="post-card" href="${dest(l,id)}"><div class="art-image"><img src="${d.image}" alt="${esc(d.title)}" width="640" height="480" loading="lazy"></div><div class="card-body"><p class="eyebrow">${t.story}</p><h2>${esc(d.title)}</h2><p>${esc(d.goal)}</p><span class="read">${t.story} ↗</span></div></a>`;}
function write(l,path,title,description,body){const dir=resolve('public',prefix(l).slice(1),path);mkdirSync(dir,{recursive:true});writeFileSync(resolve(dir,'index.html'),shell(l,{title,description,path:`${prefix(l)}/${path}/`,body}));}
for(const l of ['he','en','ar']){const t=copy[l],u=UI[l];
 write(l,'gallery',t.title,t.intro,`<main id="content" class="wide"><section class="journal-hero"><p class="eyebrow">VASIA / SELECTED WORK</p><h1>${t.title}</h1><p class="lead">${t.intro}</p></section><div class="section-heading"><h2>${u.gallery}</h2><span id="result-count" aria-live="polite">${works.length} ${t.items}</span></div><div class="filters" style="margin-bottom:28px" role="group" aria-label="${u.gallery}">${['all','video','web','brand'].map(c=>`<button data-filter="${c}" aria-pressed="${c==='all'}">${t[c]}</button>`).join('')}</div><div class="gallery-grid" data-results data-count-label="${t.items}">${works.map(([id,name,cat,img,story])=>`<article class="art-card" data-card data-topic="${cat}"><button data-gallery-open data-src="${img}" data-title="${name}" data-story="${story?dest(l,story):cat==='brand'?'/brand':`/?lang=${l}#projects`}" aria-label="${t.open}: ${name}"><div class="art-image"><img src="${img}" width="640" height="480" loading="lazy" alt="${name}"></div><div class="art-caption"><div><h2>${name}</h2><small>${t[cat]}</small></div><span aria-hidden="true">↗</span></div></button></article>`).join('')}</div><p id="empty-results" class="empty" hidden>${t.empty}</p><section class="related"><h2>${u.stories}</h2><div class="cards">${storyIds.map(id=>storyCard(l,id)).join('')}</div></section></main><dialog id="gallery-modal" aria-labelledby="gallery-modal-title"><div class="modal-head"><h2 id="gallery-modal-title"></h2><button data-close aria-label="${t.close}">×</button></div><img alt=""><div class="modal-footer"><p class="muted small">${u.image}</p><a class="button">${t.watch} ↗</a></div></dialog>`);
 write(l,'stories',t.storiesTitle,t.storiesLead,`<main id="content" class="wide"><section class="journal-hero"><p class="eyebrow">VASIA / PROJECT STORIES</p><h1>${t.storiesTitle}</h1><p class="lead">${t.storiesLead}</p></section><div class="cards">${storyIds.map(id=>storyCard(l,id)).join('')}</div></main>`);
 for(const id of storyIds){const d=data(l,id);write(l,`stories/${id}`,d.title,d.goal,`<main id="content" class="wide"><header class="article-hero"><a class="back" href="${prefix(l)}/stories/">${u.stories}</a><p class="eyebrow">PROJECT STORY</p><h1>${esc(d.title)}</h1><p class="lead">${esc(d.goal)}</p></header><div class="story-layout"><figure class="story-image"><img src="${d.image}" alt="${esc(d.title)}" width="640" height="640"></figure><div class="story-body"><p class="pill">${esc(d.disclosure)}</p>${[[t.material,d.source],[t.process,d.process],[t.delivery,d.delivery]].map(([h,p])=>`<section><h2>${h}</h2><p>${esc(p)}</p></section>`).join('')}<a class="button" href="${d.link}">${t.watch} ↗</a></div></div><section class="question"><h2>${t.talk}</h2><a class="button" data-contact-location="project_story" href="https://wa.me/972534260632?text=${encodeURIComponent(d.title+' — https://www.vasia.dev'+dest(l,id))}" target="_blank" rel="noopener noreferrer">${t.cta} ↗</a></section></main>`);}
}
console.log('Generated multilingual gallery and 3 project stories.');
